# Automatically generated using gen_constants.py

slot_data_names = [
	"add_hints_to_archipelago",
	"auto_enable_cheats",
	"chosen_ccl_mumbo_location",
	"chosen_eggs",
	"chosen_goals",
	"chosen_groggy_location",
	"chosen_moggy_location",
	"chosen_move_silo_costs",
	"chosen_soggy_location",
	"death_link",
	"dialog_character",
	"easy_canary",
	"extra_bass_clefs",
	"extra_cheato_pages",
	"extra_cheats",
	"extra_doubloons",
	"extra_egg_nests",
	"extra_empty_honeycombs",
	"extra_feather_nests",
	"extra_jiggies",
	"extra_mumbo_tokens",
	"extra_note_nests",
	"extra_treble_clefs",
	"golden_egg_nests",
	"hint_clarity",
	"instant_transform",
	"jiggywiggys_challenge_costs",
	"jiggywiggys_challenges",
	"logic_tricks",
	"max_mumbo_tokens",
	"move_hints",
	"move_silo_costs",
	"open_back_doors",
	"open_gi_front_door",
	"open_hag1",
	"open_warp_silos",
	"preset_jiggywiggys_challenge_costs",
	"preset_logic_tricks",
	"preset_victory_goals",
	"progressive_aiming",
	"progressive_aiming_list",
	"progressive_bash_attack",
	"progressive_beak_buster",
	"progressive_eggs",
	"progressive_flight",
	"progressive_flight_list",
	"progressive_shoes",
	"progressive_shoes_list",
	"progressive_water_training",
	"progressive_water_training_list",
	"replace_excess_jiggies",
	"replace_excess_mumbo_tokens",
	"replace_excess_note_nests",
	"shuffle_beans",
	"shuffle_big_top_tickets",
	"shuffle_bk_moves",
	"shuffle_boss_entrances",
	"shuffle_bt_moves",
	"shuffle_cheato_pages",
	"shuffle_cheato_rewards",
	"shuffle_chuffy",
	"shuffle_doubloons",
	"shuffle_glowbos",
	"shuffle_green_relics",
	"shuffle_honeyb_rewards",
	"shuffle_honeycombs",
	"shuffle_jiggywiggys_super_special_challenge",
	"shuffle_jinjos",
	"shuffle_nests",
	"shuffle_note_nests",
	"shuffle_signs",
	"shuffle_stop_n_swop",
	"shuffle_train_stations",
	"shuffle_treble_clefs",
	"shuffle_warp_pads",
	"shuffle_warp_silos",
	"shuffle_world_entrances",
	"shuffle_world_order",
	"sign_hints",
	"skip_klungo",
	"slip_traps",
	"speedup_minigames",
	"squish_traps",
	"starting_eggs",
	"tag_link",
	"tip_traps",
	"tower_of_tragedy",
	"transform_traps",
	"trip_traps",
	"victory_goals"
]

option_name_to_id = {
	"death_link": 0,
	"tag_link": 1,
	"preset_victory_goals": 2,
	"victory_goals_hag_1": 3,
	"victory_goals_targitzan": 4,
	"victory_goals_old_king_coal": 5,
	"victory_goals_mr_patch": 6,
	"victory_goals_lord_woo_fak_fak": 7,
	"victory_goals_terry": 8,
	"victory_goals_weldar": 9,
	"victory_goals_chilly_willy": 10,
	"victory_goals_chilli_billi": 11,
	"victory_goals_mingy_jongo": 12,
	"victory_goals_mt_kickball": 13,
	"victory_goals_ordnance_storage": 14,
	"victory_goals_hoop_hurry": 15,
	"victory_goals_dodgem_dome": 16,
	"victory_goals_saucer_of_peril": 17,
	"victory_goals_balloon_burst": 18,
	"victory_goals_mini_sub_challenge": 19,
	"victory_goals_chompas_belly": 20,
	"victory_goals_clinkers_cavern": 21,
	"victory_goals_twinkly_packing": 22,
	"victory_goals_hfp_kickball": 23,
	"victory_goals_pot_o_gold": 24,
	"victory_goals_zubbas": 25,
	"victory_goals_trash_can": 26,
	"victory_goals_canary_mary": 27,
	"victory_goals_tower_of_tragedy": 28,
	"victory_goals_white_jinjo_family": 29,
	"victory_goals_orange_jinjo_family": 30,
	"victory_goals_yellow_jinjo_family": 31,
	"victory_goals_brown_jinjo_family": 32,
	"victory_goals_green_jinjo_family": 33,
	"victory_goals_red_jinjo_family": 34,
	"victory_goals_blue_jinjo_family": 35,
	"victory_goals_purple_jinjo_family": 36,
	"victory_goals_black_jinjo_family": 37,
	"extra_mumbo_tokens": 38,
	"max_mumbo_tokens": 39,
	"replace_excess_mumbo_tokens": 40,
	"open_hag1": 41,
	"preset_logic_tricks_easy_tricks": 42,
	"preset_logic_tricks_easy_tedious_tricks": 43,
	"preset_logic_tricks_easy_glitches": 44,
	"preset_logic_tricks_hard_tricks": 45,
	"preset_logic_tricks_hard_tedious_tricks": 46,
	"preset_logic_tricks_hard_glitches": 47,
	"preset_logic_tricks_frame_perfect": 48,
	"logic_tricks_beak_barge_jump": 49,
	"logic_tricks_beak_buster_fall": 50,
	"logic_tricks_beak_buster_jump": 51,
	"logic_tricks_bill_drill_jump": 52,
	"logic_tricks_breegull_bash_fall": 53,
	"logic_tricks_air_rat_a_tat_grab": 54,
	"logic_tricks_breegull_bash_grab": 55,
	"logic_tricks_dragunda_sidle": 56,
	"logic_tricks_easy_jumps": 57,
	"logic_tricks_gi_extra_loggo_moves": 58,
	"logic_tricks_ground_rat_a_tat_rap_fall": 59,
	"logic_tricks_ground_rat_a_tat_rap_jump": 60,
	"logic_tricks_pack_whack_fall": 61,
	"logic_tricks_pack_whack_jump": 62,
	"logic_tricks_pack_whack_slope_jump": 63,
	"logic_tricks_roll_jump": 64,
	"logic_tricks_sack_pack_air_jump": 65,
	"logic_tricks_sack_pack_fall": 66,
	"logic_tricks_shack_pack_air_jump": 67,
	"logic_tricks_shack_pack_fall": 68,
	"logic_tricks_snooze_pack_fall": 69,
	"logic_tricks_taxi_pack_fall": 70,
	"logic_tricks_slope_jump": 71,
	"logic_tricks_dive_skip": 72,
	"logic_tricks_glide_extension": 73,
	"logic_tricks_rooms_with_limited_lighting": 74,
	"logic_tricks_extra_third_person_egg_shooting": 75,
	"logic_tricks_mumbo_wand_fall": 76,
	"logic_tricks_glide_in_ccl": 77,
	"logic_tricks_beak_bomb_tricks": 78,
	"logic_tricks_damage_boost": 79,
	"logic_tricks_damage_boost_jump": 80,
	"logic_tricks_death_warp": 81,
	"logic_tricks_easy_tedious_jumps": 82,
	"logic_tricks_extra_clockwork_usage": 83,
	"logic_tricks_fall_damage": 84,
	"logic_tricks_gi_quality_control_vent_as_banjo": 85,
	"logic_tricks_gi_guarded_jiggy_without_fighting": 86,
	"logic_tricks_instant_transform_trick": 87,
	"logic_tricks_talon_trot_smuggle": 88,
	"logic_tricks_talon_trot_smuggle_cross_world": 89,
	"logic_tricks_wonderwing_damage_boost": 90,
	"logic_tricks_wonderwing_fall": 91,
	"logic_tricks_wonderwing_jump": 92,
	"logic_tricks_bovina_with_beak_bomb": 93,
	"logic_tricks_tight_timers": 94,
	"logic_tricks_air_rat_a_tat_rap_clip": 95,
	"logic_tricks_eggbarge": 96,
	"logic_tricks_beak_barge_clip": 97,
	"logic_tricks_ground_rat_a_tat_clip": 98,
	"logic_tricks_breegull_bash_clip": 99,
	"logic_tricks_free_shock_spring_pad": 100,
	"logic_tricks_taxi_pack_clip": 101,
	"logic_tricks_pack_whack_clip": 102,
	"logic_tricks_golden_goliath_clip": 103,
	"logic_tricks_glitched_invincibility": 104,
	"logic_tricks_leg_spring_dive": 105,
	"logic_tricks_hard_jumps": 106,
	"logic_tricks_slide_jump": 107,
	"logic_tricks_flap_flip_slide_extension": 108,
	"logic_tricks_extra_attacks": 109,
	"logic_tricks_tightrope_walk": 110,
	"logic_tricks_rhythmic_swimming": 111,
	"logic_tricks_terry_without_egg_aim": 112,
	"logic_tricks_glide_wall_climb": 113,
	"logic_tricks_hard_tedious_jumps": 114,
	"logic_tricks_bovina_with_flap_flip": 115,
	"logic_tricks_rooms_in_the_dark": 116,
	"logic_tricks_bonfire_cavern_flame_sidle": 117,
	"logic_tricks_dodging_stompadon": 118,
	"logic_tricks_beak_bomb_clips": 119,
	"logic_tricks_clip_past_pine_grove_boulder": 120,
	"logic_tricks_clockwork_warp": 121,
	"logic_tricks_clockwork_shot_through_geometry": 122,
	"logic_tricks_talon_trot_slide_jump": 123,
	"logic_tricks_sack_pack_ending_jump": 124,
	"instant_transform": 125,
	"shuffle_bk_moves": 126,
	"shuffle_bt_moves": 127,
	"shuffle_glowbos": 128,
	"shuffle_jinjos": 129,
	"shuffle_treble_clefs": 130,
	"shuffle_note_nests": 131,
	"shuffle_honeycombs": 132,
	"shuffle_honeyb_rewards": 133,
	"shuffle_cheato_pages": 134,
	"shuffle_cheato_rewards": 135,
	"shuffle_stop_n_swop": 136,
	"shuffle_doubloons": 137,
	"shuffle_green_relics": 138,
	"shuffle_big_top_tickets": 139,
	"shuffle_beans": 140,
	"shuffle_warp_silos": 141,
	"shuffle_warp_pads": 142,
	"shuffle_signs": 143,
	"shuffle_jiggywiggys_super_special_challenge": 144,
	"shuffle_nests": 145,
	"shuffle_chuffy": 146,
	"shuffle_train_stations": 147,
	"shuffle_world_order": 148,
	"shuffle_world_entrances": 149,
	"shuffle_boss_entrances": 150,
	"progressive_eggs": 151,
	"progressive_aiming": 152,
	"progressive_flight": 153,
	"progressive_water_training": 154,
	"progressive_beak_buster": 155,
	"progressive_bash_attack": 156,
	"progressive_shoes": 157,
	"progressive_aiming_list_third_person_egg_shooting": 158,
	"progressive_aiming_list_amaze_o_gaze": 159,
	"progressive_aiming_list_egg_aim": 160,
	"progressive_aiming_list_breegull_blaster": 161,
	"progressive_flight_list_flight_pad": 162,
	"progressive_flight_list_beak_bomb": 163,
	"progressive_flight_list_airborne_egg_aiming": 164,
	"progressive_water_training_list_dive": 165,
	"progressive_water_training_list_sub_aqua_egg_aiming": 166,
	"progressive_water_training_list_talon_torpedo": 167,
	"progressive_water_training_list_double_air": 168,
	"progressive_water_training_list_fast_swimming": 169,
	"progressive_shoes_list_stilt_stride": 170,
	"progressive_shoes_list_turbo_trainers": 171,
	"progressive_shoes_list_springy_step_shoes": 172,
	"progressive_shoes_list_claw_clamber_boots": 173,
	"skip_klungo": 174,
	"tower_of_tragedy": 175,
	"speedup_minigames": 176,
	"open_gi_front_door": 177,
	"open_back_doors": 178,
	"easy_canary": 179,
	"sign_hints": 180,
	"move_hints": 181,
	"hint_clarity": 182,
	"add_hints_to_archipelago": 183,
	"replace_excess_jiggies": 184,
	"replace_excess_note_nests": 185,
	"extra_jiggies": 186,
	"extra_note_nests": 187,
	"extra_bass_clefs": 188,
	"extra_treble_clefs": 189,
	"extra_doubloons": 190,
	"extra_empty_honeycombs": 191,
	"extra_cheato_pages": 192,
	"extra_egg_nests": 193,
	"extra_feather_nests": 194,
	"trip_traps": 195,
	"slip_traps": 196,
	"tip_traps": 197,
	"transform_traps": 198,
	"golden_egg_nests": 199,
	"squish_traps": 200,
	"jiggywiggys_challenges": 201,
	"preset_jiggywiggys_challenge_costs": 202,
	"jiggywiggys_challenge_costs_challenge_1": 203,
	"jiggywiggys_challenge_costs_challenge_2": 204,
	"jiggywiggys_challenge_costs_challenge_3": 205,
	"jiggywiggys_challenge_costs_challenge_4": 206,
	"jiggywiggys_challenge_costs_challenge_5": 207,
	"jiggywiggys_challenge_costs_challenge_6": 208,
	"jiggywiggys_challenge_costs_challenge_7": 209,
	"jiggywiggys_challenge_costs_challenge_8": 210,
	"jiggywiggys_challenge_costs_challenge_9": 211,
	"jiggywiggys_challenge_costs_challenge_10": 212,
	"jiggywiggys_challenge_costs_challenge_11": 213,
	"starting_eggs_blue_eggs": 214,
	"starting_eggs_fire_eggs": 215,
	"starting_eggs_grenade_eggs": 216,
	"starting_eggs_ice_eggs": 217,
	"starting_eggs_clockwork_kazooie_eggs": 218,
	"open_warp_silos": 219,
	"move_silo_costs": 220,
	"extra_cheats": 221,
	"auto_enable_cheats_feathers": 222,
	"auto_enable_cheats_eggs": 223,
	"auto_enable_cheats_fallproof": 224,
	"auto_enable_cheats_honeyback": 225,
	"auto_enable_cheats_homing_eggs": 226,
	"dialog_character_alien": 227,
	"dialog_character_alien_child": 228,
	"dialog_character_all": 229,
	"dialog_character_banjo": 230,
	"dialog_character_banjo_kazooie": 231,
	"dialog_character_bargasaurus": 232,
	"dialog_character_beehive": 233,
	"dialog_character_bigga_foot": 234,
	"dialog_character_big_al": 235,
	"dialog_character_blobbelda": 236,
	"dialog_character_boggy": 237,
	"dialog_character_bottles": 238,
	"dialog_character_bottles_dead": 239,
	"dialog_character_bovina": 240,
	"dialog_character_canary_mary": 241,
	"dialog_character_captain_blackeye": 242,
	"dialog_character_captain_blubber": 243,
	"dialog_character_cheato": 244,
	"dialog_character_chief_bloatazin": 245,
	"dialog_character_chilli_billi": 246,
	"dialog_character_chilly_willy": 247,
	"dialog_character_chompa": 248,
	"dialog_character_chris_p_bacon": 249,
	"dialog_character_conga": 250,
	"dialog_character_dilberta": 251,
	"dialog_character_dingpot": 252,
	"dialog_character_dino_kid1": 253,
	"dialog_character_dino_kid2": 254,
	"dialog_character_dino_scrit_big": 255,
	"dialog_character_dino_scrit_small": 256,
	"dialog_character_dippy": 257,
	"dialog_character_evil_bottles": 258,
	"dialog_character_george": 259,
	"dialog_character_gi_announcer": 260,
	"dialog_character_glowbo": 261,
	"dialog_character_gobi": 262,
	"dialog_character_goggles": 263,
	"dialog_character_groggy": 264,
	"dialog_character_grunty": 265,
	"dialog_character_guffo": 266,
	"dialog_character_heggy": 267,
	"dialog_character_honeycomb": 268,
	"dialog_character_honey_b": 269,
	"dialog_character_humba": 270,
	"dialog_character_jamjars": 271,
	"dialog_character_jiggy": 272,
	"dialog_character_jiggywiggy": 273,
	"dialog_character_jiggywiggy_disciple": 274,
	"dialog_character_jinjo_black": 275,
	"dialog_character_jinjo_blue": 276,
	"dialog_character_jinjo_brown": 277,
	"dialog_character_jinjo_green": 278,
	"dialog_character_jinjo_orange": 279,
	"dialog_character_jinjo_purple": 280,
	"dialog_character_jinjo_red": 281,
	"dialog_character_jinjo_white": 282,
	"dialog_character_jinjo_yellow": 283,
	"dialog_character_jolly": 284,
	"dialog_character_kazooie": 285,
	"dialog_character_king_jingaling": 286,
	"dialog_character_king_jingaling_dead": 287,
	"dialog_character_klungo": 288,
	"dialog_character_loggo": 289,
	"dialog_character_lord_woo_fak_fak": 290,
	"dialog_character_merry_maggie": 291,
	"dialog_character_mildred": 292,
	"dialog_character_mingella": 293,
	"dialog_character_mingy_jongo": 294,
	"dialog_character_minjo_black": 295,
	"dialog_character_minjo_blue": 296,
	"dialog_character_minjo_brown": 297,
	"dialog_character_minjo_green": 298,
	"dialog_character_minjo_orange": 299,
	"dialog_character_minjo_purple": 300,
	"dialog_character_minjo_red": 301,
	"dialog_character_minjo_white": 302,
	"dialog_character_minjo_yellow": 303,
	"dialog_character_moggy": 304,
	"dialog_character_mrs_boggy": 305,
	"dialog_character_mrs_bottles": 306,
	"dialog_character_mr_fit": 307,
	"dialog_character_mr_patch": 308,
	"dialog_character_mumbo": 309,
	"dialog_character_old_king_coal": 310,
	"dialog_character_oogle_boogle": 311,
	"dialog_character_pawno": 312,
	"dialog_character_pig1": 313,
	"dialog_character_prospector": 314,
	"dialog_character_rabbit_worker1": 315,
	"dialog_character_rocknut": 316,
	"dialog_character_roysten": 317,
	"dialog_character_sabreman": 318,
	"dialog_character_safe": 319,
	"dialog_character_salty_joe": 320,
	"dialog_character_soggy": 321,
	"dialog_character_speccy": 322,
	"dialog_character_ssslumber": 323,
	"dialog_character_stonies1": 324,
	"dialog_character_styracosaurus_mom": 325,
	"dialog_character_sub": 326,
	"dialog_character_targitzan": 327,
	"dialog_character_terry": 328,
	"dialog_character_tiptup": 329,
	"dialog_character_ufo": 330,
	"dialog_character_unga_bunga": 331,
	"dialog_character_unogopaz": 332,
	"dialog_character_washer": 333,
	"dialog_character_weldar": 334,
	"dialog_character_yellow_dodgem": 335,
	"dialog_character_yellow_stony": 336,
	"dialog_character_zubba": 337,
	"chosen_ccl_mumbo_location": 338,
	"chosen_eggs": 339,
	"chosen_goals_hag_1": 340,
	"chosen_goals_targitzan": 341,
	"chosen_goals_old_king_coal": 342,
	"chosen_goals_mr_patch": 343,
	"chosen_goals_lord_woo_fak_fak": 344,
	"chosen_goals_terry": 345,
	"chosen_goals_weldar": 346,
	"chosen_goals_chilly_willy": 347,
	"chosen_goals_chilli_billi": 348,
	"chosen_goals_mingy_jongo": 349,
	"chosen_goals_mt_kickball": 350,
	"chosen_goals_ordnance_storage": 351,
	"chosen_goals_hoop_hurry": 352,
	"chosen_goals_dodgem_dome": 353,
	"chosen_goals_saucer_of_peril": 354,
	"chosen_goals_balloon_burst": 355,
	"chosen_goals_mini_sub_challenge": 356,
	"chosen_goals_chompas_belly": 357,
	"chosen_goals_clinkers_cavern": 358,
	"chosen_goals_twinkly_packing": 359,
	"chosen_goals_hfp_kickball": 360,
	"chosen_goals_pot_o_gold": 361,
	"chosen_goals_zubbas": 362,
	"chosen_goals_trash_can": 363,
	"chosen_goals_canary_mary": 364,
	"chosen_goals_tower_of_tragedy": 365,
	"chosen_goals_white_jinjo_family": 366,
	"chosen_goals_orange_jinjo_family": 367,
	"chosen_goals_yellow_jinjo_family": 368,
	"chosen_goals_brown_jinjo_family": 369,
	"chosen_goals_green_jinjo_family": 370,
	"chosen_goals_red_jinjo_family": 371,
	"chosen_goals_blue_jinjo_family": 372,
	"chosen_goals_purple_jinjo_family": 373,
	"chosen_goals_black_jinjo_family": 374,
	"chosen_groggy_location": 375,
	"chosen_moggy_location": 376,
	"chosen_move_silo_costs_fire_eggs": 377,
	"chosen_move_silo_costs_grenade_eggs": 378,
	"chosen_move_silo_costs_ice_eggs": 379,
	"chosen_move_silo_costs_clockwork_kazooie_eggs": 380,
	"chosen_move_silo_costs_egg_aim": 381,
	"chosen_move_silo_costs_breegull_blaster": 382,
	"chosen_move_silo_costs_grip_grab": 383,
	"chosen_move_silo_costs_bill_drill": 384,
	"chosen_move_silo_costs_beak_bayonet": 385,
	"chosen_move_silo_costs_split_up": 386,
	"chosen_move_silo_costs_pack_whack": 387,
	"chosen_move_silo_costs_airborne_egg_aiming": 388,
	"chosen_move_silo_costs_wing_whack": 389,
	"chosen_move_silo_costs_sub_aqua_egg_aiming": 390,
	"chosen_move_silo_costs_talon_torpedo": 391,
	"chosen_move_silo_costs_springy_step_shoes": 392,
	"chosen_move_silo_costs_taxi_pack": 393,
	"chosen_move_silo_costs_hatch": 394,
	"chosen_move_silo_costs_claw_clamber_boots": 395,
	"chosen_move_silo_costs_snooze_pack": 396,
	"chosen_move_silo_costs_leg_spring": 397,
	"chosen_move_silo_costs_shack_pack": 398,
	"chosen_move_silo_costs_glide": 399,
	"chosen_move_silo_costs_sack_pack": 400,
	"chosen_soggy_location": 401
}

item_name_to_id = {
	"Air Rat-a-tat Rap": 1,
	"Airborne Egg Aiming": 2,
	"Amaze-O-Gaze": 3,
	"Baby T-Rex Roar": 4,
	"Bass Clef": 5,
	"Beak Barge": 6,
	"Beak Bayonet": 7,
	"Beak Bomb": 8,
	"Beak Buster": 9,
	"Bean": 10,
	"Big Top Ticket": 11,
	"Big-O Pants": 12,
	"Bill Drill": 13,
	"Black Jinjo": 14,
	"Blue Eggs": 15,
	"Blue Jinjo": 16,
	"Blue Mystery Egg": 17,
	"Breegull Bash": 18,
	"Breegull Blaster": 19,
	"Brown Jinjo": 20,
	"CCL: Central Cavern Warp Pad": 21,
	"CCL: World Entry And Exit Warp Pad": 22,
	"CK: Bottom Of The Tower Warp Pad": 23,
	"CK: Top Of The Tower Warp Pad": 24,
	"Cauldron Keep": 25,
	"Cheato Page": 26,
	"Cheato Reward: Eggs": 27,
	"Cheato Reward: Fallproof": 28,
	"Cheato Reward: Feathers": 29,
	"Cheato Reward: Honeyback": 30,
	"Cheato Reward: Jukebox": 31,
	"Chuffy": 32,
	"Claw Clamber Boots": 33,
	"Cliff Top Warp Silo": 34,
	"Climb": 35,
	"Clockwork Kazooie Eggs": 36,
	"Cloud Cuckooland": 37,
	"Dive": 38,
	"Double Air": 39,
	"Doubloon": 40,
	"Egg Aim": 41,
	"Egg Nest": 42,
	"Empty Honeycomb": 43,
	"Fast Swimming": 44,
	"Feather Nest": 45,
	"Fire Eggs": 46,
	"Flap Flip": 47,
	"Flight Pad": 48,
	"Flutter": 49,
	"GGM: Inside Wumba's Wigwam Warp Pad": 50,
	"GGM: Near The Train Station Warp Pad": 51,
	"GGM: Outside Mumbo's Skull Warp Pad": 52,
	"GGM: Outside The Crushing Shed Warp Pad": 53,
	"GGM: World Entry And Exit Warp Pad": 54,
	"GI Cleaned Skivvy": 55,
	"GI Floor 1: Entrance Door Warp Pad": 56,
	"GI Floor 2: Outside Wumba's Wigwam Warp Pad": 57,
	"GI Floor 3: Outside Mumbo's Skull Warp Pad": 58,
	"GI Floor 4: Near The Crushers Warp Pad": 59,
	"GI Outside: On The Roof Outside Warp Pad": 60,
	"GI: Train Station": 61,
	"Glide": 62,
	"Glitter Gulch Mine": 63,
	"Golden Egg Nest": 64,
	"Green Jinjo": 65,
	"Green Relic": 66,
	"Grenade Eggs": 67,
	"Grip Grab": 68,
	"Ground Rat-a-tat Rap": 69,
	"Grunty Industries": 70,
	"HAG-1": 71,
	"HFP: Fire Side - Lower Area (Mumbo) Warp Pad": 72,
	"HFP: Fire Side - Upper Area Warp Pad": 73,
	"HFP: Ice Side - Inside Icicle Grotto Warp Pad": 74,
	"HFP: Ice Side - Lower Area (Wumba) Warp Pad": 75,
	"HFP: Ice Side - Upper Area Warp Pad": 76,
	"HFP: Icy Side Train Station": 77,
	"HFP: Lava Side Train Station": 78,
	"Hailfire Peaks": 79,
	"Hatch": 80,
	"Health Upgrade": 81,
	"Homing Eggs": 82,
	"Humba: Bee": 83,
	"Humba: Detonator": 84,
	"Humba: Dragon": 85,
	"Humba: Money Van": 86,
	"Humba: Snowball": 87,
	"Humba: Stony": 88,
	"Humba: Sub": 89,
	"Humba: T-Rex": 90,
	"Humba: Washing Machine": 91,
	"Ice Eggs": 92,
	"Ice Key": 93,
	"IoH: Train Station": 94,
	"JRL: Atlantis Warp Pad": 95,
	"JRL: Big Fish Cavern Warp Pad": 96,
	"JRL: Lockers Cavern Warp Pad": 97,
	"JRL: Sunken Ship Warp Pad": 98,
	"JRL: Town Center Warp Pad": 99,
	"Jiggy": 100,
	"Jinjo Village Warp Silo": 101,
	"Jolly Roger's Lagoon": 102,
	"Leg Spring": 103,
	"MT: Kickball Stadium Lobby Warp Pad": 104,
	"MT: Near Wumba's Wigwam Warp Pad": 105,
	"MT: Outside Mumbo's Skull Warp Pad": 106,
	"MT: Prison Compound Warp Pad": 107,
	"MT: Snake Head": 108,
	"MT: World Entry And Exit Warp Pad": 109,
	"Mayahem Temple": 110,
	"Mumbo Token": 111,
	"Mumbo: EMP": 112,
	"Mumbo: Enlarge": 113,
	"Mumbo: Golden Goliath": 114,
	"Mumbo: Heal": 115,
	"Mumbo: Levitate": 116,
	"Mumbo: Life Force": 117,
	"Mumbo: Oxygenate": 118,
	"Mumbo: Power": 119,
	"Mumbo: Rain Dance": 120,
	"Note Nest": 121,
	"Nothing": 122,
	"Orange Jinjo": 123,
	"Pack Whack": 124,
	"Pine Grove Warp Silo": 125,
	"Pink Mystery Egg": 126,
	"Plateau Warp Silo": 127,
	"Progressive Aiming": 128,
	"Progressive Bash Attack": 129,
	"Progressive Beak Buster": 130,
	"Progressive Eggs": 131,
	"Progressive Flight": 132,
	"Progressive Shoes": 133,
	"Progressive Water Training": 134,
	"Purple Jinjo": 135,
	"Quagmire Warp Silo": 136,
	"Red Jinjo": 137,
	"Roll": 138,
	"Sack Pack": 139,
	"Shack Pack": 140,
	"Slip Trap": 141,
	"Snooze Pack": 142,
	"Split Up": 143,
	"Springy Step Shoes": 144,
	"Squish Trap": 145,
	"Stilt Stride": 146,
	"Sub-Aqua Egg Aiming": 147,
	"TDL: Outside Mumbo's Skull Warp Pad": 148,
	"TDL: Outside Wumba's Wigwam Warp Pad": 149,
	"TDL: Stomping Plains Warp Pad": 150,
	"TDL: Top Of The Mountain Warp Pad": 151,
	"TDL: Train Station": 152,
	"TDL: World Entry And Exit Warp Pad": 153,
	"Tall Jump": 154,
	"Talon Torpedo": 155,
	"Talon Trot": 156,
	"Taxi Pack": 157,
	"Terrydactyland": 158,
	"Third Person Egg Shooting": 159,
	"Tip Trap": 160,
	"Transform Trap": 161,
	"Treble Clef": 162,
	"Trip Trap": 163,
	"Turbo Trainers": 164,
	"WW: Behind The Big Top Tent Warp Pad": 165,
	"WW: Outside Mumbo's Skull Warp Pad": 166,
	"WW: Outside Wumba's Wigwam Warp Pad": 167,
	"WW: Space Zone Warp Pad": 168,
	"WW: Train Station": 169,
	"WW: World Entry And Exit Warp Pad": 170,
	"Wasteland Warp Silo": 171,
	"White Jinjo": 172,
	"Wing Whack": 173,
	"Witchyworld": 174,
	"Wonderwing": 175,
	"Wooded Hollow Warp Silo": 176,
	"Yellow Jinjo": 177
}

location_name_to_id = {
	"CCL: Behind the Trash Can Feather Nest 1": 1,
	"CCL: Behind the Trash Can Feather Nest 2": 2,
	"CCL: Behind the Trash Can Feather Nest 3": 3,
	"CCL: Behind the Trash Can Feather Nest 4": 4,
	"CCL: Blue Skull Exit Note": 5,
	"CCL: By George Feather Nest 1": 6,
	"CCL: By George Feather Nest 2": 7,
	"CCL: By George Feather Nest 3": 8,
	"CCL: By George Feather Nest 4": 9,
	"CCL: Canary Mary Cheato Page": 10,
	"CCL: Canary Mary Jiggy": 11,
	"CCL: Canary Mary Mumbo Token": 12,
	"CCL: Central Cavern Egg Hatched": 13,
	"CCL: Central Cavern Jinjo": 14,
	"CCL: Central Cavern Top Path Egg Nest 1": 15,
	"CCL: Central Cavern Top Path Egg Nest 2": 16,
	"CCL: Central Cavern Under Cheese Wedge Exit Egg Nest 1": 17,
	"CCL: Central Cavern Under Cheese Wedge Exit Egg Nest 2": 18,
	"CCL: Central Cavern Warp Pad Tagged": 19,
	"CCL: Central Cavern on Steps Near Main Entrance Egg Nest": 20,
	"CCL: Central Note 1": 21,
	"CCL: Central Note 2": 22,
	"CCL: Central Note 3": 23,
	"CCL: Cheese Wedge Bean Grown": 24,
	"CCL: Cheese Wedge Bean Planted": 25,
	"CCL: Cheese Wedge Egg Hatched": 26,
	"CCL: Cheese Wedge Exit Note": 27,
	"CCL: Cheese Wedge Jiggy": 28,
	"CCL: Cheese Wedge Jinjo": 29,
	"CCL: Dippy Pool Feather Nest 1": 30,
	"CCL: Dippy Pool Feather Nest 2": 31,
	"CCL: Dippy Pool Feather Nest 3": 32,
	"CCL: Dippy Pool Feather Nest 4": 33,
	"CCL: Dippy Pool Filled": 34,
	"CCL: Dippy Pool Note": 35,
	"CCL: Dirt Patch Bean 1": 36,
	"CCL: Dirt Patch Bean 2": 37,
	"CCL: Dirt Patch Egg Nest": 38,
	"CCL: Dirt Patch Feather Nest": 39,
	"CCL: Dirt Patch Honeycomb": 40,
	"CCL: George Booped": 41,
	"CCL: Glowbo Pool Note": 42,
	"CCL: High Jump Event Feather Nest": 43,
	"CCL: Indoors Pool Glowbo": 44,
	"CCL: Indoors Pool Underwater Signpost": 45,
	"CCL: Inside Cheese Wedge Egg Nest 1": 46,
	"CCL: Inside Cheese Wedge Egg Nest 2": 47,
	"CCL: Jelly Castle Egg Nest 1": 48,
	"CCL: Jelly Castle Egg Nest 2": 49,
	"CCL: Jelly Castle Egg Nest 3": 50,
	"CCL: Jelly Castle Egg Nest 4": 51,
	"CCL: Jelly Castle Jiggy": 52,
	"CCL: Jiggium Plant Jiggy": 53,
	"CCL: Main Entrance Note": 54,
	"CCL: Mingy Jongo Jiggy": 55,
	"CCL: Mingy Jongo Mumbo Token": 56,
	"CCL: Mingy Jongo Skull Jinjo": 57,
	"CCL: Mr Fit Jiggy": 58,
	"CCL: Mr. Fit Footrace Track Note": 59,
	"CCL: Mr. Fit High Jump Event": 60,
	"CCL: Mr. Fit Sack Race Event": 61,
	"CCL: Mr. Fit Sack Race Exit Note": 62,
	"CCL: Near Blue Skull Feather Nest 1": 63,
	"CCL: Near Blue Skull Feather Nest 2": 64,
	"CCL: Near Blue Skull Feather Nest 3": 65,
	"CCL: Near Blue Skull Feather Nest 4": 66,
	"CCL: Near Red Skull Feather Nest 1": 67,
	"CCL: Near Red Skull Feather Nest 2": 68,
	"CCL: Near Red Skull Feather Nest 3": 69,
	"CCL: Near Red Skull Feather Nest 4": 70,
	"CCL: Near Top Superstash Switch Feather Nest 1": 71,
	"CCL: Near Top Superstash Switch Feather Nest 2": 72,
	"CCL: On Rim of Glowbo Pool Signpost": 73,
	"CCL: Outdoors Pool Glowbo": 74,
	"CCL: Outside Cheese Wedge Feather Nest 1": 75,
	"CCL: Outside Cheese Wedge Feather Nest 2": 76,
	"CCL: Outside Cheese Wedge Feather Nest 3": 77,
	"CCL: Outside Cheese Wedge Feather Nest 4": 78,
	"CCL: Pot O' Gold Cheato Page": 79,
	"CCL: Pot O' Gold Honeycomb": 80,
	"CCL: Pot O' Gold Jiggy": 81,
	"CCL: Pot O' Gold Mumbo Token": 82,
	"CCL: Pot o' Gold Activated": 83,
	"CCL: Pot o' Gold Egg Nest 1": 84,
	"CCL: Pot o' Gold Egg Nest 2": 85,
	"CCL: Pot o' Gold Exit Note": 86,
	"CCL: Red Skull Exit Note": 87,
	"CCL: Sack Pack Silo": 88,
	"CCL: Sack Pack Silo Note 1": 89,
	"CCL: Sack Pack Silo Note 2": 90,
	"CCL: Sack Pack Silo Signpost": 91,
	"CCL: Sack Race Bean Grown": 92,
	"CCL: Sack Race Bean Planted": 93,
	"CCL: Sack Race Egg Hatched": 94,
	"CCL: Superstash Jiggy": 95,
	"CCL: Superstash Opened": 96,
	"CCL: Superstash Switch By George Pressed": 97,
	"CCL: Superstash Switch By Superstash Pressed": 98,
	"CCL: Superstash Switch In Trashcan Pressed": 99,
	"CCL: Top Central Cavern Path Superstash Switch Pressed": 100,
	"CCL: Top Entrance Feather Nest 1": 101,
	"CCL: Top Entrance Feather Nest 2": 102,
	"CCL: Top Entrance Note": 103,
	"CCL: Top Superstash Switch Note": 104,
	"CCL: Top-Left of Superstash Egg Nest 1": 105,
	"CCL: Top-Left of Superstash Egg Nest 2": 106,
	"CCL: Trash Can Egg Nest 1": 107,
	"CCL: Trash Can Egg Nest 2": 108,
	"CCL: Trash Can Honeycomb": 109,
	"CCL: Trash Can Jiggy": 110,
	"CCL: Trash Can Jinjo": 111,
	"CCL: Trash Can Mumbo Token": 112,
	"CCL: Treble Clef": 113,
	"CCL: World Entry and Exit Warp Pad Tagged": 114,
	"CCL: Wumba Jinjo": 115,
	"CCL: Wumba's Wigwam Egg Nest 1": 116,
	"CCL: Wumba's Wigwam Egg Nest 2": 117,
	"CCL: Wumba's Wigwam Signpost": 118,
	"CCL: Zubbas Cheato Page": 119,
	"CCL: Zubbas Jiggy": 120,
	"CCL: Zubbas Mumbo Token": 121,
	"CK: Bottom of the Tower Warp Pad Tagged": 122,
	"CK: Defeated HAG-1": 123,
	"CK: Top of the Tower Warp Pad Tagged": 124,
	"CK: Tower Of Tragedy Mumbo Token": 125,
	"Completion Condition": 126,
	"GGM: Beak Bayonet Silo": 127,
	"GGM: Bill Drill Silo": 128,
	"GGM: Both Canary Mary Races Won": 129,
	"GGM: Boulder Jinjo": 130,
	"GGM: Canary Cave Back-Left Egg Nest": 131,
	"GGM: Canary Cave Back-Right Feather Nest": 132,
	"GGM: Canary Cave Front-Left Feather Nest": 133,
	"GGM: Canary Cave Front-Right Egg Nest": 134,
	"GGM: Canary Cave Rocks Broken": 135,
	"GGM: Canary Mary Cheato Page": 136,
	"GGM: Canary Mary Freed": 137,
	"GGM: Canary Mary Jiggy": 138,
	"GGM: Chuffy": 139,
	"GGM: Crushing Shed Button Pressed": 140,
	"GGM: Crushing Shed Egg Nest 1": 141,
	"GGM: Crushing Shed Egg Nest 2": 142,
	"GGM: Crushing Shed Jiggy": 143,
	"GGM: Crushing Shed Jiggy Chunk 1": 144,
	"GGM: Crushing Shed Jiggy Chunk 2": 145,
	"GGM: Crushing Shed Jiggy Chunk 3": 146,
	"GGM: Defeated Chuffy": 147,
	"GGM: Dilberta Jiggy": 148,
	"GGM: Entrance Cheato Page": 149,
	"GGM: Flooded Caves Egg Nest 1": 150,
	"GGM: Flooded Caves Egg Nest 2": 151,
	"GGM: Flooded Caves Jiggy": 152,
	"GGM: Fuel Depot Back-Left Note": 153,
	"GGM: Fuel Depot Back-Right Note": 154,
	"GGM: Fuel Depot Egg Nest 1": 155,
	"GGM: Fuel Depot Egg Nest 2": 156,
	"GGM: Fuel Depot Egg Nest 3": 157,
	"GGM: Fuel Depot Feather Nest 1": 158,
	"GGM: Fuel Depot Feather Nest 2": 159,
	"GGM: Fuel Depot Feather Nest 3": 160,
	"GGM: Fuel Depot Front-Left Note": 161,
	"GGM: Fuel Depot Front-Right Note": 162,
	"GGM: Fuel Depot Rocks Broken": 163,
	"GGM: Generator Cavern Egg Nest": 164,
	"GGM: Generator Cavern Jiggy": 165,
	"GGM: Generator Cavern Signpost": 166,
	"GGM: Gloomy Cavern Near Jail Cell Rocks Broken": 167,
	"GGM: Gloomy Cavern Near Power Hut Rocks Broken": 168,
	"GGM: Gloomy Cavern Signpost": 169,
	"GGM: Gloomy Caverns Jail Cell Feather Nest": 170,
	"GGM: Gloomy Caverns Near Power Hut Egg Nest 1": 171,
	"GGM: Gloomy Caverns Near Power Hut Egg Nest 2": 172,
	"GGM: Gloomy Caverns Near Second Boulder Egg Nest": 173,
	"GGM: Hill by Crushing Shed Note 1": 174,
	"GGM: Hill by Crushing Shed Note 2": 175,
	"GGM: Hill by Crushing Shed Note 3": 176,
	"GGM: Hill by Crushing Shed Note 4": 177,
	"GGM: Inside Chuffy's Wagon Signpost": 178,
	"GGM: Inside Wumba's Wigwam Warp Pad Tagged": 179,
	"GGM: Jail Jinjo": 180,
	"GGM: Levitate Chuffy The Train": 181,
	"GGM: Levitate The Crushing Shed Boulder": 182,
	"GGM: Mine Entrance 2 Boulder Broken": 183,
	"GGM: Mine Entrance 2 Glowbo": 184,
	"GGM: Mine Tracks Jinjo": 185,
	"GGM: Mumbo's Skull Feather Nest 1": 186,
	"GGM: Mumbo's Skull Feather Nest 2": 187,
	"GGM: Mumbo's Skull Feather Nest 3": 188,
	"GGM: Near Bill Drill Silo Egg Nest 1": 189,
	"GGM: Near Bill Drill Silo Egg Nest 2": 190,
	"GGM: Near Entrance Glowbo": 191,
	"GGM: Near Prospector's Hut Bottom-Left Note": 192,
	"GGM: Near Prospector's Hut Bottom-Right Note": 193,
	"GGM: Near Prospector's Hut Middle-Right Note": 194,
	"GGM: Near Prospector's Hut Top-Left Note": 195,
	"GGM: Near Prospector's Hut Top-Right Note": 196,
	"GGM: Near the Train Station Warp Pad Tagged": 197,
	"GGM: Old King Coal Jiggy": 198,
	"GGM: Old King Coal Mumbo Token": 199,
	"GGM: Ordnance Storage Boulder Broken": 200,
	"GGM: Ordnance Storage Jiggy": 201,
	"GGM: Ordnance Storage Lobby Egg Nest 1": 202,
	"GGM: Ordnance Storage Lobby Egg Nest 2": 203,
	"GGM: Ordnance Storage Lobby Egg Nest 3": 204,
	"GGM: Ordnance Storage Mumbo Token": 205,
	"GGM: Ordnance Storage Won": 206,
	"GGM: Outside Mumbo's Skull Bottom-Right Note": 207,
	"GGM: Outside Mumbo's Skull Left Note": 208,
	"GGM: Outside Mumbo's Skull Top-Right Note": 209,
	"GGM: Outside Mumbo's Skull Warp Pad Tagged": 210,
	"GGM: Outside Ordnance Storage Egg Nest 1": 211,
	"GGM: Outside Ordnance Storage Egg Nest 2": 212,
	"GGM: Outside the Crushing Shed Warp Pad Tagged": 213,
	"GGM: Power Hut Basement Jiggy": 214,
	"GGM: Power Hut Feather Nest": 215,
	"GGM: Prospector Boulder Honeycomb": 216,
	"GGM: Prospector's Hut Egg Nest": 217,
	"GGM: Rocks Near Crushing Shed Broken": 218,
	"GGM: Toxic Gas Cave Egg Nest": 219,
	"GGM: Toxic Gas Cave Feather Nest": 220,
	"GGM: Toxic Gas Cave Honeycomb": 221,
	"GGM: Toxic Gas Cave Jinjo": 222,
	"GGM: Toxic Gas Cave Signpost": 223,
	"GGM: Train Station Egg Nest 1": 224,
	"GGM: Train Station Egg Nest 2": 225,
	"GGM: Train Station Feather Nest 1": 226,
	"GGM: Train Station Feather Nest 2": 227,
	"GGM: Train Station Honeycomb": 228,
	"GGM: Treble Clef": 229,
	"GGM: Water Storage Cheato Page": 230,
	"GGM: Water Storage Jinjo": 231,
	"GGM: Water Storage On Top Of Jinjo Tank Egg Nest": 232,
	"GGM: Waterfall Cavern Boulder Broken": 233,
	"GGM: Waterfall Cavern Entrance Opened": 234,
	"GGM: Waterfall Cavern Jiggy": 235,
	"GGM: Waterfall Jiggy": 236,
	"GGM: World Entry and Exit Warp Pad Tagged": 237,
	"GI Elevator Shaft: Floor 2 Egg Nest": 238,
	"GI Elevator Shaft: Floor 3 Egg Nest": 239,
	"GI Elevator Shaft: Floor 4 Egg Nest": 240,
	"GI Elevator Shaft: Signpost 1": 241,
	"GI Elevator Shaft: Signpost 2": 242,
	"GI Floor 1: Air Conditioning Plant In Front of Fan Feather Nest 1": 243,
	"GI Floor 1: Air Conditioning Plant In Front of Fan Feather Nest 2": 244,
	"GI Floor 1: Air Conditioning Plant Near Repair Depot Egg Nest 1": 245,
	"GI Floor 1: Air Conditioning Plant Near Repair Depot Egg Nest 2": 246,
	"GI Floor 1: Air Conditioning Plant Near Waste Disposal Egg Nest": 247,
	"GI Floor 1: Air Conditioning Plant Note 1": 248,
	"GI Floor 1: Air Conditioning Plant Note 2": 249,
	"GI Floor 1: Broke Loggo's Door": 250,
	"GI Floor 1: Claw Clamber Boots Silo": 251,
	"GI Floor 1: Cleaned Skivvy": 252,
	"GI Floor 1: Defeated Tintops": 253,
	"GI Floor 1: Entrance Door Warp Pad Tagged": 254,
	"GI Floor 1: Floor 1 on A/C Unit Note 1": 255,
	"GI Floor 1: Floor 1 on A/C Unit Note 2": 256,
	"GI Floor 1: Guarded Jiggy": 257,
	"GI Floor 1: High Pipe Egg Nest 1": 258,
	"GI Floor 1: High Pipe Egg Nest 2": 259,
	"GI Floor 1: Loggo Cheato Page": 260,
	"GI Floor 1: Near Waste Disposal Feather Nest 1": 261,
	"GI Floor 1: Near Waste Disposal Feather Nest 2": 262,
	"GI Floor 1: Opened Back Door": 263,
	"GI Floor 1: Opened Main Door": 264,
	"GI Floor 1: Opened Trash Compactor Jiggy Door": 265,
	"GI Floor 1: Opened Waste Disposal Plant": 266,
	"GI Floor 1: Repair Depot Cheato Page": 267,
	"GI Floor 1: Repair Depot Egg Nest 1": 268,
	"GI Floor 1: Repair Depot Egg Nest 2": 269,
	"GI Floor 1: Skivvy": 270,
	"GI Floor 1: Snooze Pack Silo": 271,
	"GI Floor 1: Top Pipe Egg Nest": 272,
	"GI Floor 1: Top of Trash Compactor Feather Nest": 273,
	"GI Floor 1: Train Station Big Box Egg Nest": 274,
	"GI Floor 1: Train Station Honeycomb": 275,
	"GI Floor 1: Train Station Medium Box Egg Nest": 276,
	"GI Floor 1: Train Station Note 1": 277,
	"GI Floor 1: Train Station Note 2": 278,
	"GI Floor 1: Train Station Note 3": 279,
	"GI Floor 1: Train Station Small Box Egg Nest": 280,
	"GI Floor 1: Trash Compactor Egg Nest 1": 281,
	"GI Floor 1: Trash Compactor Egg Nest 2": 282,
	"GI Floor 1: Trash Compactor Jiggy": 283,
	"GI Floor 1: Underwater Waste Disposal Plant Jiggy": 284,
	"GI Floor 1: Waste Disposal Jinjo Tank Egg Nest 1": 285,
	"GI Floor 1: Waste Disposal Jinjo Tank Egg Nest 2": 286,
	"GI Floor 1: Waste Disposal Plant Box Jiggy": 287,
	"GI Floor 1: Waste Disposal Plant Jinjo": 288,
	"GI Floor 1: Waste Disposal Plant Note 1": 289,
	"GI Floor 1: Waste Disposal Plant Note 2": 290,
	"GI Floor 1: Waste Disposal Water Pump Egg Nest": 291,
	"GI Floor 1: Waste Disposal Water Pump Feather Nest": 292,
	"GI Floor 1: Weldar Jiggy": 293,
	"GI Floor 1: Weldar Mumbo Token": 294,
	"GI Floor 1: Workers Quarters Signpost": 295,
	"GI Floor 1: Workers' Quarters Egg Nest": 296,
	"GI Floor 1: Workers' Quarters Feather Nest": 297,
	"GI Floor 2: Box Room Shorter Stack Note": 298,
	"GI Floor 2: Box Room Taller Stack Note": 299,
	"GI Floor 2: Broke Grate Near Electromagnet Chamber": 300,
	"GI Floor 2: Broke Grate Near Humba": 301,
	"GI Floor 2: Cleaned Skivvy": 302,
	"GI Floor 2: Delivered Battery Near Floor 3 Exit": 303,
	"GI Floor 2: Delivered Toxic Room Battery": 304,
	"GI Floor 2: EMP Electromagnet": 305,
	"GI Floor 2: Electromagnetic Chamber Egg Nest 1": 306,
	"GI Floor 2: Electromagnetic Chamber Egg Nest 2": 307,
	"GI Floor 2: Electromagnetic Chamber Feather Nest": 308,
	"GI Floor 2: Glowbo": 309,
	"GI Floor 2: In a Box Egg Nest 1": 310,
	"GI Floor 2: In a Box Egg Nest 2": 311,
	"GI Floor 2: Leg Spring Jinjo": 312,
	"GI Floor 2: Leg Spring Room Note 1": 313,
	"GI Floor 2: Leg Spring Room Note 2": 314,
	"GI Floor 2: Leg Spring Room Note 3": 315,
	"GI Floor 2: Leg Spring Silo": 316,
	"GI Floor 2: Near Cheato Page Feather Nest": 317,
	"GI Floor 2: Near Floor 1 Tunnel Egg Nest": 318,
	"GI Floor 2: Near Unscrewable Platform Feather Nest": 319,
	"GI Floor 2: On Scaffolding Egg Nest 1": 320,
	"GI Floor 2: On Scaffolding Egg Nest 2": 321,
	"GI Floor 2: On Scaffolding Egg Nest 3": 322,
	"GI Floor 2: On Scaffolding Egg Nest 4": 323,
	"GI Floor 2: On Scaffolding Egg Nest 5": 324,
	"GI Floor 2: Opened Catwalk Door": 325,
	"GI Floor 2: Opened Electromagnet Chamber": 326,
	"GI Floor 2: Opened Elevator Door": 327,
	"GI Floor 2: Opened Repair Depot": 328,
	"GI Floor 2: Outside Wumba's Wigwam Warp Pad Tagged": 329,
	"GI Floor 2: Skivvy": 330,
	"GI Floor 2: Unscrewed Plate": 331,
	"GI Floor 2: Window Cheato Page": 332,
	"GI Floor 3: Boiler Plant Jinjo": 333,
	"GI Floor 3: Boiler Plant Left Egg Nest": 334,
	"GI Floor 3: Boiler Plant Right Egg Nest": 335,
	"GI Floor 3: Cleaned Skivvy": 336,
	"GI Floor 3: Cleared Twinkly Packing": 337,
	"GI Floor 3: Delivered Battery": 338,
	"GI Floor 3: Glowbo": 339,
	"GI Floor 3: Honeycomb": 340,
	"GI Floor 3: Near Mumbo's Skull Egg Nest": 341,
	"GI Floor 3: Note 1": 342,
	"GI Floor 3: Note 2": 343,
	"GI Floor 3: On Boxes Feather Nest 1": 344,
	"GI Floor 3: On Boxes Feather Nest 2": 345,
	"GI Floor 3: On Crate Egg Nest": 346,
	"GI Floor 3: On High Box Stack Egg Nest": 347,
	"GI Floor 3: Opened Elevator Door": 348,
	"GI Floor 3: Opened Twinkly Packing Door": 349,
	"GI Floor 3: Outside Mumbo's Skull Warp Pad Tagged": 350,
	"GI Floor 3: Skivvy": 351,
	"GI Floor 3: Twinkly Packing Jiggy": 352,
	"GI Floor 3: Twinkly Packing Mumbo Token": 353,
	"GI Floor 3: Under Notes Egg Nest": 354,
	"GI Floor 3: Unscrewed Plate": 355,
	"GI Floor 4: Activated Flight Pads": 356,
	"GI Floor 4: Box Near Crushers Egg Nest": 357,
	"GI Floor 4: Cable Room": 358,
	"GI Floor 4: Cleared Clinker's Cavern": 359,
	"GI Floor 4: Clinker's Cavern Green Room Egg Nest 1": 360,
	"GI Floor 4: Clinker's Cavern Green Room Egg Nest 2": 361,
	"GI Floor 4: Clinker's Cavern Jiggy": 362,
	"GI Floor 4: Clinker's Cavern Mumbo Token": 363,
	"GI Floor 4: Clinker's Cavern Near Window Egg Nest": 364,
	"GI Floor 4: Clinker's Cavern Orange Room Egg Nest": 365,
	"GI Floor 4: Clinker's Cavern Raising Scaffolding Room Bottom Egg Nest": 366,
	"GI Floor 4: Clinker's Cavern Raising Scaffolding Room Top Egg Nest": 367,
	"GI Floor 4: Clinker's Cavern Spiral Scaffolding Room Egg Nest": 368,
	"GI Floor 4: Clinker's Cavern Valve Room Egg Nest": 369,
	"GI Floor 4: Disabled Crushers": 370,
	"GI Floor 4: EMP Wall Crushers": 371,
	"GI Floor 4: Near Battery Door Egg Nest": 372,
	"GI Floor 4: Near Fire Exit Egg Nest 1": 373,
	"GI Floor 4: Near Fire Exit Egg Nest 2": 374,
	"GI Floor 4: Near Fire Exit Egg Nest 3": 375,
	"GI Floor 4: Near Service Elevator Feather Nest 1": 376,
	"GI Floor 4: Near Service Elevator Feather Nest 2": 377,
	"GI Floor 4: Near the Crushers Warp Pad Tagged": 378,
	"GI Floor 4: Opened Cable Room Door": 379,
	"GI Floor 4: Opened Elevator Door": 380,
	"GI Floor 4: Pressed Quality Control Vent Button": 381,
	"GI Floor 4: Quality Control Egg Nest 1": 382,
	"GI Floor 4: Quality Control Egg Nest 2": 383,
	"GI Floor 4: Quality Control Egg Nest 3": 384,
	"GI Floor 4: Quality Control Jiggy": 385,
	"GI Floor 4: Quality Control Pit": 386,
	"GI Floor 4: Sewer Entrance Left Egg Nest 1": 387,
	"GI Floor 4: Sewer Entrance Left Egg Nest 2": 388,
	"GI Floor 4: Sewer Entrance Right Egg Nest 1": 389,
	"GI Floor 4: Sewer Entrance Right Egg Nest 2": 390,
	"GI Floor 4: Spawned Quality Control Jiggy": 391,
	"GI Floor 5: Big Box Stack Egg Nest": 392,
	"GI Floor 5: Box Egg Nest": 393,
	"GI Floor 5: Cleaned Skivvy": 394,
	"GI Floor 5: Jiggy": 395,
	"GI Floor 5: Jinjo": 396,
	"GI Floor 5: Skivvy": 397,
	"GI Floor 5: Small Box Stack Egg Nest": 398,
	"GI Floor 5: Unscrewed Plate": 399,
	"GI Outside: Atop Back Train Tunnel Feather Nest": 400,
	"GI Outside: Atop Front Train Tunnel Feather Nest": 401,
	"GI Outside: Broke Chimney": 402,
	"GI Outside: Broke Floor 1 Window": 403,
	"GI Outside: Broke Upper Middle Window": 404,
	"GI Outside: Broke Upper Side Window": 405,
	"GI Outside: Broke Window Above Front Train Tunnel": 406,
	"GI Outside: Broke Window Near Back Train Tunnel": 407,
	"GI Outside: Chimney Honeycomb": 408,
	"GI Outside: Cleaned Skivvy": 409,
	"GI Outside: Delivered Battery": 410,
	"GI Outside: Jinjo": 411,
	"GI Outside: On the Roof Outside Warp Pad Tagged": 412,
	"GI Outside: Roof Feather Nest 1": 413,
	"GI Outside: Roof Feather Nest 2": 414,
	"GI Outside: Roof Feather Nest 3": 415,
	"GI Outside: Signpost": 416,
	"GI Outside: Skivvy": 417,
	"GI Outside: Train Switch": 418,
	"GI Outside: Treble Clef": 419,
	"GI Worker's Quarters: Cleaned Skivvy": 420,
	"GI Worker's Quarters: Skivvy": 421,
	"GI: Defeated Weldar": 422,
	"GI: Mumbo Transform": 423,
	"GI: Skivvy Workers Jiggy": 424,
	"GI: Washer Transform": 425,
	"HFP: Aliens Jiggy": 426,
	"HFP: Alphette (Alien Kid Near Glowbo)": 427,
	"HFP: Betette (Alien Kid Near Dad)": 428,
	"HFP: Boggy Jiggy": 429,
	"HFP: Boggy's Igloo Note 1": 430,
	"HFP: Boggy's Igloo Note 2": 431,
	"HFP: Boiling Hot Pool Jinjo": 432,
	"HFP: Bottom Hot Pool Signpost": 433,
	"HFP: By Flight Pad Feather Nest 1": 434,
	"HFP: By Flight Pad Feather Nest 2": 435,
	"HFP: By Flight Pad Feather Nest 3": 436,
	"HFP: By Flight Pad Feather Nest 4": 437,
	"HFP: By Lava Side Train Switch Egg Nest": 438,
	"HFP: By Sabreman Egg Nest 1": 439,
	"HFP: By Sabreman Egg Nest 2": 440,
	"HFP: Chilli Billi Crater Egg Nest": 441,
	"HFP: Chilli Billi Mumbo Token": 442,
	"HFP: Chilly Willy Crater Egg Nest": 443,
	"HFP: Chilly Willy Mumbo Token": 444,
	"HFP: Colosseum Cheato Page": 445,
	"HFP: Colosseum Split-Up Jiggy": 446,
	"HFP: Dragon Brothers Jiggy": 447,
	"HFP: Fire Side - Lower Area (Mumbo) Warp Pad Tagged": 448,
	"HFP: Fire Side - Upper Area Warp Pad Tagged": 449,
	"HFP: Gamette (Alien Kid Above Split-Up Pads)": 450,
	"HFP: Glide Silo": 451,
	"HFP: Ice Side - Inside Icicle Grotto Warp Pad Tagged": 452,
	"HFP: Ice Side - Lower Area (Wumba) Warp Pad Tagged": 453,
	"HFP: Ice Side - Upper Area Warp Pad Tagged": 454,
	"HFP: Icicle Grotto Bottom Egg Nest 1": 455,
	"HFP: Icicle Grotto Bottom Egg Nest 2": 456,
	"HFP: Icicle Grotto Bottom Egg Nest 3": 457,
	"HFP: Icicle Grotto Cheato Page": 458,
	"HFP: Icicle Grotto Jinjo": 459,
	"HFP: Icicle Grotto Shock Spring Pad Egg Nest": 460,
	"HFP: Icicle Grotto Top Egg Nest 1": 461,
	"HFP: Icicle Grotto Top Egg Nest 2": 462,
	"HFP: Icy Side Glowbo": 463,
	"HFP: Icy Side Lower Warp Pad Egg Nest": 464,
	"HFP: Icy Side Pillar Cheato Page": 465,
	"HFP: Icy Side Station Jiggy": 466,
	"HFP: Icy Side Train Station Egg Nest": 467,
	"HFP: Icy Side Train Station Feather Nest": 468,
	"HFP: Icy Side Train Switch": 469,
	"HFP: Inside the Volcano Honeycomb": 470,
	"HFP: Inside the Volcano Jiggy": 471,
	"HFP: Kickball Colosseum Egg Nest 1": 472,
	"HFP: Kickball Colosseum Egg Nest 2": 473,
	"HFP: Kickball Colosseum Egg Nest 3": 474,
	"HFP: Kickball Colosseum Egg Nest 4": 475,
	"HFP: Kickball Colosseum Feather Nest 1": 476,
	"HFP: Kickball Colosseum Feather Nest 2": 477,
	"HFP: Kickball Jiggy": 478,
	"HFP: Kickball Mumbo Token": 479,
	"HFP: Lava Side Glowbo": 480,
	"HFP: Lava Side Honeycomb": 481,
	"HFP: Lava Side Lower Warp Pad Egg Nest 1": 482,
	"HFP: Lava Side Lower Warp Pad Egg Nest 2": 483,
	"HFP: Lava Side Train Station Egg Nest 1": 484,
	"HFP: Lava Side Train Station Egg Nest 2": 485,
	"HFP: Lava Side Train Switch": 486,
	"HFP: Lava Side: Near Ladder Note 1": 487,
	"HFP: Lava Side: Near Ladder Note 2": 488,
	"HFP: Lava Side: Top Path Note 1": 489,
	"HFP: Lava Side: Top Path Note 2": 490,
	"HFP: Lava Waterfall Jinjo": 491,
	"HFP: Lower Icy Side Warp Pad Note 1": 492,
	"HFP: Lower Icy Side Warp Pad Note 2": 493,
	"HFP: Mega Glowbo": 494,
	"HFP: Mildred Ice Cube Jinjo": 495,
	"HFP: Mumbo's Skull Feather Nest 1": 496,
	"HFP: Mumbo's Skull Feather Nest 2": 497,
	"HFP: Near Bottom Icicle Grotto Entrance Feather Nest 1": 498,
	"HFP: Near Bottom Icicle Grotto Entrance Feather Nest 2": 499,
	"HFP: Near Icy Side Pillar Egg Nest 1": 500,
	"HFP: Near Icy Side Pillar Egg Nest 2": 501,
	"HFP: Near Top Hot Pool Egg Nest 1": 502,
	"HFP: Near Top Hot Pool Egg Nest 2": 503,
	"HFP: Oil Drill Jiggy": 504,
	"HFP: Oil Drill Note 1": 505,
	"HFP: Oil Drill Note 2": 506,
	"HFP: On Shelter Near Entrance Feather Nest": 507,
	"HFP: Path to Mumbo's Skull Note 1": 508,
	"HFP: Path to Mumbo's Skull Note 2": 509,
	"HFP: Path to Shack Pack Note 1": 510,
	"HFP: Path to Shack Pack Note 2": 511,
	"HFP: Sabreman Jiggy": 512,
	"HFP: Sabreman Tent Egg Nest": 513,
	"HFP: Shack Pack Silo": 514,
	"HFP: Stomping Plains Jiggy": 515,
	"HFP: Top Hot Pool Signpost": 516,
	"HFP: Train Station Honeycomb": 517,
	"HFP: Treble Clef": 518,
	"HFP: Upper Icy Side Warp Pad Note 1": 519,
	"HFP: Upper Icy Side Warp Pad Note 2": 520,
	"HFP: Volcano Signpost 1": 521,
	"HFP: Volcano Signpost 2": 522,
	"HFP: Volcano Signpost 3": 523,
	"HFP: Windy Hole Jinjo": 524,
	"HFP: Wumba's Wigwam Feather Nest 1": 525,
	"HFP: Wumba's Wigwam Feather Nest 2": 526,
	"IoH Dragon Transform": 527,
	"IoH: Amaze-O-Gaze Goggles": 528,
	"IoH: Another Digger Tunnel Egg Nest 1": 529,
	"IoH: Another Digger Tunnel Egg Nest 2": 530,
	"IoH: Behind Jiggywiggy's Temple Signpost 1": 531,
	"IoH: Behind Jiggywiggy's Temple Signpost 2": 532,
	"IoH: Behind Jiggywiggy's Temple Signpost 3": 533,
	"IoH: Black Jinjo Family Jiggy": 534,
	"IoH: Black Jinjo Family Mumbo Token": 535,
	"IoH: Blue Jinjo Family Jiggy": 536,
	"IoH: Blue Jinjo Family Mumbo Token": 537,
	"IoH: Blue Mystery Egg Hatched": 538,
	"IoH: Bottles' House Egg Nest 1": 539,
	"IoH: Bottles' House Egg Nest 2": 540,
	"IoH: Bottles' House Feather Nest 1": 541,
	"IoH: Bottles' House Feather Nest 2": 542,
	"IoH: Bottles' House: Gate Opened": 543,
	"IoH: Brown Jinjo Family Jiggy": 544,
	"IoH: Brown Jinjo Family Mumbo Token": 545,
	"IoH: Cliff Top Bridge Switch Pressed": 546,
	"IoH: Cliff Top Feather Nest 1": 547,
	"IoH: Cliff Top Feather Nest 2": 548,
	"IoH: Cliff Top Feather Nest 3": 549,
	"IoH: Cliff Top Feather Nest 4": 550,
	"IoH: Cliff Top Glowbo": 551,
	"IoH: Cliff Top Jinjo": 552,
	"IoH: Cliff Top Near JRL Egg Nest": 553,
	"IoH: Cliff Top Near Path to Plateau Egg Nest 1": 554,
	"IoH: Cliff Top Near Path to Plateau Egg Nest 2": 555,
	"IoH: Cliff Top Signpost": 556,
	"IoH: Cliff Top Silo Tagged": 557,
	"IoH: Clockwork Kazooie Eggs Silo": 558,
	"IoH: Clockwork Silo Bottom Note": 559,
	"IoH: Clockwork Silo Top Note": 560,
	"IoH: Fire Eggs Silo": 561,
	"IoH: Green Jinjo Family Jiggy": 562,
	"IoH: Green Jinjo Family Mumbo Token": 563,
	"IoH: Grenade Eggs Silo": 564,
	"IoH: Grey Jinjo Family House Signpost": 565,
	"IoH: Honey B's Reward 1": 566,
	"IoH: Honey B's Reward 2": 567,
	"IoH: Honey B's Reward 3": 568,
	"IoH: Honey B's Reward 4": 569,
	"IoH: Honey B's Reward 5": 570,
	"IoH: Ice Eggs Silo": 571,
	"IoH: Ice Key": 572,
	"IoH: Inside the Digger Tunnel Egg Nest": 573,
	"IoH: Jiggywiggy's Temple Signpost 1": 574,
	"IoH: Jiggywiggy's Temple Signpost 2": 575,
	"IoH: Jiggywiggy's Temple Signpost 3": 576,
	"IoH: Jiggywiggy's Temple Signpost 4": 577,
	"IoH: Jiggywiggy's Temple Signpost 5": 578,
	"IoH: Jiggywiggy's Temple Signpost 6": 579,
	"IoH: Jiggywiggy's Temple Signpost 7": 580,
	"IoH: Jiggywiggy's Temple Signpost 8": 581,
	"IoH: Jinjo Village By Silo Egg Nest 1": 582,
	"IoH: Jinjo Village By Silo Egg Nest 2": 583,
	"IoH: Jinjo Village By Silo Feather Nest 1": 584,
	"IoH: Jinjo Village By Silo Feather Nest 2": 585,
	"IoH: Jinjo Village Near Shortcut Egg Nest 1": 586,
	"IoH: Jinjo Village Near Shortcut Egg Nest 2": 587,
	"IoH: Jinjo Village Outside Bottle's House Feather Nest 1": 588,
	"IoH: Jinjo Village Outside Bottle's House Feather Nest 2": 589,
	"IoH: Jinjo Village Silo Tagged": 590,
	"IoH: Jinjo Village Top Row of Houses Egg Nest 1": 591,
	"IoH: Jinjo Village Top Row of Houses Egg Nest 2": 592,
	"IoH: Jinjo Village Top Row of Houses Feather Nest 1": 593,
	"IoH: Jinjo Village Top Row of Houses Feather Nest 2": 594,
	"IoH: King Jingaling Jiggy": 595,
	"IoH: Orange Jinjo Family Jiggy": 596,
	"IoH: Orange Jinjo Family Mumbo Token": 597,
	"IoH: Outside HFP Note 1": 598,
	"IoH: Outside HFP Note 2": 599,
	"IoH: Outside HFP Note 3": 600,
	"IoH: Outside HFP Note 4": 601,
	"IoH: Party At Bottles'": 602,
	"IoH: Pine Grove Egg Nest 1": 603,
	"IoH: Pine Grove Egg Nest 2": 604,
	"IoH: Pine Grove Egg Nest 3": 605,
	"IoH: Pine Grove Feather Nest 1": 606,
	"IoH: Pine Grove Feather Nest 2": 607,
	"IoH: Pine Grove Feather Nest 3": 608,
	"IoH: Pine Grove Note 1": 609,
	"IoH: Pine Grove Note 2": 610,
	"IoH: Pine Grove Signpost 1": 611,
	"IoH: Pine Grove Signpost 2": 612,
	"IoH: Pine Grove Signpost 3": 613,
	"IoH: Pine Grove Silo Tagged": 614,
	"IoH: Pine Grove Underwater Note 1": 615,
	"IoH: Pine Grove Underwater Note 2": 616,
	"IoH: Pink Mystery Egg Hatched": 617,
	"IoH: Plateau Dirt Pile Feather Nest 1": 618,
	"IoH: Plateau Dirt Pile Feather Nest 2": 619,
	"IoH: Plateau GGM Sign Note 1": 620,
	"IoH: Plateau GGM Sign Note 2": 621,
	"IoH: Plateau Honey B. Note 1": 622,
	"IoH: Plateau Honey B. Note 2": 623,
	"IoH: Plateau Honeycomb": 624,
	"IoH: Plateau Jinjo": 625,
	"IoH: Plateau Near Cliff Top Entrance Feather Nest": 626,
	"IoH: Plateau Near GGM Entrance Egg Nest 1": 627,
	"IoH: Plateau Near GGM Entrance Egg Nest 2": 628,
	"IoH: Plateau Near GGM Entrance Egg Nest 3": 629,
	"IoH: Plateau Near GGM Entrance Egg Nest 4": 630,
	"IoH: Plateau Silo Tagged": 631,
	"IoH: Plateau: Fire Switch": 632,
	"IoH: Plateau: Path to Cliff Top Opened": 633,
	"IoH: Purple Jinjo Family Jiggy": 634,
	"IoH: Purple Jinjo Family Mumbo Token": 635,
	"IoH: Quagmire Back Feather Nest": 636,
	"IoH: Quagmire Egg Nest 1": 637,
	"IoH: Quagmire Egg Nest 2": 638,
	"IoH: Quagmire Egg Nest 3": 639,
	"IoH: Quagmire High Feather Nest": 640,
	"IoH: Quagmire Left Feather Nest": 641,
	"IoH: Quagmire Silo Tagged": 642,
	"IoH: Quagmire Spring Pad Switch Pressed": 643,
	"IoH: Red Jinjo Family Jiggy": 644,
	"IoH: Red Jinjo Family Mumbo Token": 645,
	"IoH: Train Switch": 646,
	"IoH: Treble Clef": 647,
	"IoH: Wasteland Behind CCL Bubble Feather Nest": 648,
	"IoH: Wasteland CCL Area Note 1": 649,
	"IoH: Wasteland CCL Area Note 2": 650,
	"IoH: Wasteland Jinjo": 651,
	"IoH: Wasteland Near Crevice to CCL Feather Nest": 652,
	"IoH: Wasteland Near Digger Tunnel Egg Nest 1": 653,
	"IoH: Wasteland Near Digger Tunnel Egg Nest 2": 654,
	"IoH: Wasteland Near Digger Tunnel Egg Nest 3": 655,
	"IoH: Wasteland Next to Quagmire Entrance Feather Nest": 656,
	"IoH: Wasteland Signpost": 657,
	"IoH: Wasteland Silo Tagged": 658,
	"IoH: Wasteland TDL Entrance Feather Nest 1": 659,
	"IoH: Wasteland TDL Entrance Feather Nest 2": 660,
	"IoH: White Jinjo Family Jiggy": 661,
	"IoH: White Jinjo Family Mumbo Token": 662,
	"IoH: Wooded Hollow Behind Heggy's Egg Shed Signpost": 663,
	"IoH: Wooded Hollow Jiggywiggy Challenge 1": 664,
	"IoH: Wooded Hollow Jiggywiggy Challenge 10": 665,
	"IoH: Wooded Hollow Jiggywiggy Challenge 2": 666,
	"IoH: Wooded Hollow Jiggywiggy Challenge 3": 667,
	"IoH: Wooded Hollow Jiggywiggy Challenge 4": 668,
	"IoH: Wooded Hollow Jiggywiggy Challenge 5": 669,
	"IoH: Wooded Hollow Jiggywiggy Challenge 6": 670,
	"IoH: Wooded Hollow Jiggywiggy Challenge 7": 671,
	"IoH: Wooded Hollow Jiggywiggy Challenge 8": 672,
	"IoH: Wooded Hollow Jiggywiggy Challenge 9": 673,
	"IoH: Wooded Hollow Jiggywiggy's Super Special Challenge": 674,
	"IoH: Wooded Hollow Jinjo": 675,
	"IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 1": 676,
	"IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 2": 677,
	"IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 3": 678,
	"IoH: Wooded Hollow Outside Bottles' House Feather Nest 1": 679,
	"IoH: Wooded Hollow Outside Bottles' House Feather Nest 2": 680,
	"IoH: Wooded Hollow Outside Heggy's Egg Shed Egg Nest 1": 681,
	"IoH: Wooded Hollow Outside Heggy's Egg Shed Egg Nest 2": 682,
	"IoH: Wooded Hollow Path to Plateau Signpost": 683,
	"IoH: Wooded Hollow Right of Jiggywiggy's Temple Egg Nest 1": 684,
	"IoH: Wooded Hollow Right of Jiggywiggy's Temple Egg Nest 2": 685,
	"IoH: Wooded Hollow Silo Tagged": 686,
	"IoH: Wumba's Wigwam Egg Nest 1": 687,
	"IoH: Wumba's Wigwam Egg Nest 2": 688,
	"IoH: Yellow Jinjo Family Jiggy": 689,
	"IoH: Yellow Jinjo Family Mumbo Token": 690,
	"IoH: Yellow Mystery Egg Hatched": 691,
	"JRL: Alcove Doubloon 1": 692,
	"JRL: Alcove Doubloon 2": 693,
	"JRL: Alcove Doubloon 3": 694,
	"JRL: Ancient Swimming Baths Cheato Page": 695,
	"JRL: Atlantis Egg Nest 1": 696,
	"JRL: Atlantis Egg Nest 2": 697,
	"JRL: Atlantis Egg Nest 3": 698,
	"JRL: Atlantis Honeycomb": 699,
	"JRL: Atlantis Seemee Fish Egg Nest": 700,
	"JRL: Atlantis Warp Pad Tagged": 701,
	"JRL: Big Fish Cavern Warp Pad Tagged": 702,
	"JRL: Big Fish Jinjo": 703,
	"JRL: Blubber Jinjo": 704,
	"JRL: Blubber's Hire Note 1": 705,
	"JRL: Blubber's Hire Note 2": 706,
	"JRL: Blubber's Hire Note 3": 707,
	"JRL: Blubber's Signpost": 708,
	"JRL: Blubbul Note 1": 709,
	"JRL: Blubbul Note 2": 710,
	"JRL: Captain Blackeye Doubloon 1": 711,
	"JRL: Captain Blackeye Doubloon 2": 712,
	"JRL: Chris P. Bacon Jiggy": 713,
	"JRL: Davie Jones Locker Egg Nest 1": 714,
	"JRL: Davie Jones Locker Egg Nest 2": 715,
	"JRL: Davie Jones Locker Egg Nest 3": 716,
	"JRL: Davie Jones Locker Egg Nest 4": 717,
	"JRL: Electric Eel's Lair Entrance Note 1": 718,
	"JRL: Electric Eel's Lair Entrance Note 2": 719,
	"JRL: Inside the Big Fish Feather Nest 1": 720,
	"JRL: Inside the Big Fish Feather Nest 2": 721,
	"JRL: Jolly's Gunpowder Feather Nest 1": 722,
	"JRL: Jolly's Gunpowder Feather Nest 2": 723,
	"JRL: Jolly's Near Blackeye Egg Nest 1": 724,
	"JRL: Jolly's Near Blackeye Egg Nest 2": 725,
	"JRL: Jolly's Near Sub-Aqua Egg Aiming Silo Feather Nest 1": 726,
	"JRL: Jolly's Near Sub-Aqua Egg Aiming Silo Feather Nest 2": 727,
	"JRL: Jolly's Note 1": 728,
	"JRL: Jolly's Note 2": 729,
	"JRL: Jolly's Note 3": 730,
	"JRL: Lagoon Alcove Jinjo": 731,
	"JRL: Lockers Cavern Warp Pad Tagged": 732,
	"JRL: Lockers Egg Nest 1": 733,
	"JRL: Lockers Egg Nest 2": 734,
	"JRL: Lockers Egg Nest 3": 735,
	"JRL: Merry Maggie Jiggy": 736,
	"JRL: Mini-Sub Challenge Jiggy": 737,
	"JRL: Mini-Sub Challenge Mumbo Token": 738,
	"JRL: Mumbo Skull Doubloon 1": 739,
	"JRL: Mumbo Skull Doubloon 2": 740,
	"JRL: Mumbo Skull Doubloon 3": 741,
	"JRL: Mumbo Skull Doubloon 4": 742,
	"JRL: Near Alcove Jinjo Doubloon 1": 743,
	"JRL: Near Alcove Jinjo Doubloon 2": 744,
	"JRL: Near Alcove Jinjo Doubloon 3": 745,
	"JRL: Near Alcove Jinjo Doubloon 4": 746,
	"JRL: Near Big Fish Warp Pad Egg Nest 1": 747,
	"JRL: Near Big Fish Warp Pad Egg Nest 2": 748,
	"JRL: Outside Blubber's Note": 749,
	"JRL: Outside Jolly's Note": 750,
	"JRL: Outside Pawno's Note": 751,
	"JRL: Pawno Cheato Page": 752,
	"JRL: Pawno Jiggy": 753,
	"JRL: Pawno's Emporium Egg Nest 1": 754,
	"JRL: Pawno's Emporium Egg Nest 2": 755,
	"JRL: Pawno's Emporium Egg Nest 3": 756,
	"JRL: Pawno's Emporium Glowbo": 757,
	"JRL: Pawno's Emporium Note 1": 758,
	"JRL: Pawno's Emporium Note 2": 759,
	"JRL: Pawno's Emporium Note 3": 760,
	"JRL: Pig Pool Jiggy": 761,
	"JRL: Sea Bottom Seemee Fish Egg Nest": 762,
	"JRL: Sea Bottom Seemee Fish Feather Nest": 763,
	"JRL: Seaweed Sanctum Bottom Floor Feather Nest": 764,
	"JRL: Seaweed Sanctum Jinjo": 765,
	"JRL: Seaweed Sanctum Second Floor Egg Nest 1": 766,
	"JRL: Seaweed Sanctum Second Floor Egg Nest 2": 767,
	"JRL: Seaweed Sanctum Signpost": 768,
	"JRL: Seaweed Sanctum Top Floor Feather Nest": 769,
	"JRL: Seemee Cheato Page": 770,
	"JRL: Seemee Honeycomb": 771,
	"JRL: Seemee Jiggy": 772,
	"JRL: Silo Doubloon 1": 773,
	"JRL: Silo Doubloon 2": 774,
	"JRL: Silo Doubloon 3": 775,
	"JRL: Silo Doubloon 4": 776,
	"JRL: Smuggler's Cavern Egg Nest 1": 777,
	"JRL: Smuggler's Cavern Egg Nest 2": 778,
	"JRL: Smuggler's Cavern Jiggy": 779,
	"JRL: Smuggler's Cavern Signpost": 780,
	"JRL: Sub-Aqua Egg Aiming Silo": 781,
	"JRL: Sunken Ship Egg Nest 1": 782,
	"JRL: Sunken Ship Egg Nest 2": 783,
	"JRL: Sunken Ship Jinjo": 784,
	"JRL: Sunken Ship Warp Pad Tagged": 785,
	"JRL: Talon Torpedo Silo": 786,
	"JRL: Temple of the Fishes Egg Nest 1": 787,
	"JRL: Temple of the Fishes Egg Nest 2": 788,
	"JRL: Temple of the Fishes Egg Nest 3": 789,
	"JRL: Temple of the Fishes Egg Nest 4": 790,
	"JRL: Tiptup Jiggy": 791,
	"JRL: Town Center Blubbul Egg Nest": 792,
	"JRL: Town Center Pole Doubloon 1": 793,
	"JRL: Town Center Pole Doubloon 2": 794,
	"JRL: Town Center Pole Doubloon 3": 795,
	"JRL: Town Center Pole Doubloon 4": 796,
	"JRL: Town Center Pole Doubloon 5": 797,
	"JRL: Town Center Pole Doubloon 6": 798,
	"JRL: Town Center Warp Pad Tagged": 799,
	"JRL: Toxic Pool Doubloon 1": 800,
	"JRL: Toxic Pool Doubloon 2": 801,
	"JRL: Toxic Pool Doubloon 3": 802,
	"JRL: Toxic Pool Doubloon 4": 803,
	"JRL: Treble Clef": 804,
	"JRL: UFO Jiggy": 805,
	"JRL: Under Wumba's Wigwam Glowbo": 806,
	"JRL: Underground Doubloon 1": 807,
	"JRL: Underground Doubloon 2": 808,
	"JRL: Underground Doubloon 3": 809,
	"JRL: Waste Pipe Alcove Signpost": 810,
	"JRL: Waste Pipe Honeycomb": 811,
	"JRL: Wing Whack Silo": 812,
	"JRL: Woo Fak Fak Jiggy": 813,
	"JRL: Woo Fak Fak Mumbo Token": 814,
	"JRL: Wumba's Wigwam Feather Nest": 815,
	"MT Kickball Round 1 Won": 816,
	"MT Kickball Round 2 Won": 817,
	"MT Kickball Round 3 Won": 818,
	"MT: Bovina Egg Nest 1": 819,
	"MT: Bovina Egg Nest 2": 820,
	"MT: Bovina Honeycomb": 821,
	"MT: Bovina Jiggy": 822,
	"MT: Break Flight Pad Boulder": 823,
	"MT: Breegull Blaster Silo": 824,
	"MT: Bridge Jinjo": 825,
	"MT: Egg Aim Silo": 826,
	"MT: Entrance Honeycomb": 827,
	"MT: First Stairs Note 1": 828,
	"MT: First Stairs Note 2": 829,
	"MT: First Stairs Note 3": 830,
	"MT: First Stairs Note 4": 831,
	"MT: Golden Goliath Jiggy": 832,
	"MT: Golden Goliath Signpost": 833,
	"MT: Grip Grab Silo": 834,
	"MT: In Front of Jade Snake Grove Feather Nest 1": 835,
	"MT: In Front of Jade Snake Grove Feather Nest 2": 836,
	"MT: In Front of Prison Compound Egg Nest 1": 837,
	"MT: In Front of Prison Compound Egg Nest 2": 838,
	"MT: Jade Snake Grove Above Code Chamber Egg Nest": 839,
	"MT: Jade Snake Grove Cheato Page": 840,
	"MT: Jade Snake Grove Glowbo": 841,
	"MT: Jade Snake Grove Jinjo": 842,
	"MT: Jade Snake Grove Near Warp Pad Egg Nest 1": 843,
	"MT: Jade Snake Grove Near Warp Pad Egg Nest 2": 844,
	"MT: Jade Snake Grove Quicksand Signpost 1": 845,
	"MT: Jade Snake Grove Quicksand Signpost 2": 846,
	"MT: Kickball Jiggy": 847,
	"MT: Kickball Mumbo Token": 848,
	"MT: Kickball Round 1 Opened": 849,
	"MT: Kickball Stadium Feather Nest 1": 850,
	"MT: Kickball Stadium Feather Nest 2": 851,
	"MT: Kickball Stadium Lobby Warp Pad Tagged": 852,
	"MT: Kickball Stadium Switch Pressed": 853,
	"MT: Kill Flies": 854,
	"MT: Left of Code Chamber Signpost": 855,
	"MT: Mumbo's Glowbo": 856,
	"MT: Mumbo's Skull Egg Nest 1": 857,
	"MT: Mumbo's Skull Egg Nest 2": 858,
	"MT: Mumbo's Skull Signpost": 859,
	"MT: Near Wumba's Wigwam Warp Pad Tagged": 860,
	"MT: Open Bottom Treasure Chamber Door": 861,
	"MT: Open Code Chamber": 862,
	"MT: Open Jade Snake Grove": 863,
	"MT: Open Prison Compound": 864,
	"MT: Open Top Treasure Chamber Door": 865,
	"MT: Outside Mumbo's Skull Note": 866,
	"MT: Outside Mumbo's Skull Warp Pad Tagged": 867,
	"MT: Outside Treasure Chamber Egg Nest 1": 868,
	"MT: Outside Treasure Chamber Egg Nest 2": 869,
	"MT: Pillar Jiggy Lowered": 870,
	"MT: Pillars Jiggy": 871,
	"MT: Pillars Signpost": 872,
	"MT: Prison Compound Cell Opened": 873,
	"MT: Prison Compound Cheato Page": 874,
	"MT: Prison Compound Entrance Egg Nest 1": 875,
	"MT: Prison Compound Entrance Egg Nest 2": 876,
	"MT: Prison Compound Jail Cell Boulder Broken": 877,
	"MT: Prison Compound Moon Switch Pressed": 878,
	"MT: Prison Compound Pillars Egg Nest 1": 879,
	"MT: Prison Compound Pillars Egg Nest 2": 880,
	"MT: Prison Compound Pillars Egg Nest 3": 881,
	"MT: Prison Compound Quicksand Jiggy": 882,
	"MT: Prison Compound Quicksand Signpost": 883,
	"MT: Prison Compound Star Switch Pressed": 884,
	"MT: Prison Compound Sun Switch Pressed": 885,
	"MT: Prison Compound Top of Prison Cell Feather Left Nest": 886,
	"MT: Prison Compound Top of Prison Cell Feather Right Nest": 887,
	"MT: Prison Compound Warp Pad Tagged": 888,
	"MT: Second Stairs Note 1": 889,
	"MT: Second Stairs Note 2": 890,
	"MT: Second Stairs Note 3": 891,
	"MT: Second Stairs Note 4": 892,
	"MT: Slighty Sacred Chamber Jiggy": 893,
	"MT: Snake Head 1": 894,
	"MT: Snake Head 2": 895,
	"MT: Snake Head 3": 896,
	"MT: Snake Head 4": 897,
	"MT: Snake Head 5": 898,
	"MT: Snake Head 6": 899,
	"MT: Ssslumber Jiggy": 900,
	"MT: Stadium Jinjo": 901,
	"MT: Targitzan Jiggy": 902,
	"MT: Targitzan Mumbo Token": 903,
	"MT: Targitzan Temple Jinjo": 904,
	"MT: Targitzan's Temple 4-Way Room Egg Nest 1": 905,
	"MT: Targitzan's Temple 4-Way Room Egg Nest 2": 906,
	"MT: Targitzan's Temple 4-Way Room Egg Nest 3": 907,
	"MT: Targitzan's Temple 4-Way Room Egg Nest 4": 908,
	"MT: Targitzan's Temple Blue Pillar Room Relic 1": 909,
	"MT: Targitzan's Temple Blue Pillar Room Relic 2": 910,
	"MT: Targitzan's Temple Blue Pillar Room Relic 3": 911,
	"MT: Targitzan's Temple Golden Egg Nest": 912,
	"MT: Targitzan's Temple Green Pillar Room Relic 1": 913,
	"MT: Targitzan's Temple Green Pillar Room Relic 2": 914,
	"MT: Targitzan's Temple Green Pillar Room Relic 3": 915,
	"MT: Targitzan's Temple Green Pillar Room Relic 4": 916,
	"MT: Targitzan's Temple Green Pillar Room Relic 5": 917,
	"MT: Targitzan's Temple Left Entrance Relic": 918,
	"MT: Targitzan's Temple Lobby Left Egg Nest 1": 919,
	"MT: Targitzan's Temple Lobby Left Egg Nest 2": 920,
	"MT: Targitzan's Temple Lobby Left Egg Nest 3": 921,
	"MT: Targitzan's Temple Lobby Right Egg Nest 1": 922,
	"MT: Targitzan's Temple Lobby Right Egg Nest 2": 923,
	"MT: Targitzan's Temple Lobby Right Egg Nest 3": 924,
	"MT: Targitzan's Temple Near Sacred Chambers Relic 1": 925,
	"MT: Targitzan's Temple Near Sacred Chambers Relic 2": 926,
	"MT: Targitzan's Temple Near Sput Sput Relic 1": 927,
	"MT: Targitzan's Temple Near Sput Sput Relic 2": 928,
	"MT: Targitzan's Temple Near Sput Sput Relic 3": 929,
	"MT: Targitzan's Temple Near Sput Sput Relic 4": 930,
	"MT: Targitzan's Temple Near Sput Sput Relic 5": 931,
	"MT: Targitzan's Temple Pillar Maze Egg Nest 1": 932,
	"MT: Targitzan's Temple Pillar Maze Egg Nest 2": 933,
	"MT: Targitzan's Temple Pillar Maze Egg Nest 3": 934,
	"MT: Targitzan's Temple Raising Slope Room Egg Nest 1": 935,
	"MT: Targitzan's Temple Raising Slope Room Egg Nest 2": 936,
	"MT: Targitzan's Temple Raising Slope Room Egg Nest 3": 937,
	"MT: Targitzan's Temple Red Pillar Room Relic 1": 938,
	"MT: Targitzan's Temple Red Pillar Room Relic 2": 939,
	"MT: Targitzan's Temple Red Pillar Room Relic 3": 940,
	"MT: Targitzan's Temple Right Entrance Relic": 941,
	"MT: Targitzan's Temple Secret Passage Near Entrance Relic 1": 942,
	"MT: Targitzan's Temple Secret Passage Near Entrance Relic 2": 943,
	"MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 1": 944,
	"MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 2": 945,
	"MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 3": 946,
	"MT: Targitzan's Temple Signpost 1": 947,
	"MT: Targitzan's Temple Signpost 2": 948,
	"MT: Third Stairs Note 1": 949,
	"MT: Third Stairs Note 2": 950,
	"MT: Third Stairs Note 3": 951,
	"MT: Third Stairs Note 4": 952,
	"MT: Top Stairs Note 1": 953,
	"MT: Top Stairs Note 2": 954,
	"MT: Top Stairs Note 3": 955,
	"MT: Top of Temple Jiggy": 956,
	"MT: Treasure Chamber Cheato Page": 957,
	"MT: Treasure Chamber Honeycomb": 958,
	"MT: Treasure Chamber Jiggy": 959,
	"MT: Treasure Chamber Unga Bunga Switch Pressed": 960,
	"MT: Treble Clef": 961,
	"MT: Water Pool Jinjo": 962,
	"MT: World Entry and Exit Warp Pad Tagged": 963,
	"MT: Wumba's Wigwam Feather Nest 1": 964,
	"MT: Wumba's Wigwam Feather Nest 2": 965,
	"SM: Attack Tutorial Field Feather Nest 1": 966,
	"SM: Attack Tutorial Field Feather Nest 2": 967,
	"SM: Attack Tutorial Field Feather Nest 3": 968,
	"SM: Base of Spiral Mountain Feather Nest 1": 969,
	"SM: Base of Spiral Mountain Feather Nest 2": 970,
	"SM: Base of Spiral Mountain Feather Nest 3": 971,
	"SM: Blue Mystery Egg": 972,
	"SM: Bottom of Attack Tutorial Field Egg Nest 1": 973,
	"SM: Bottom of Attack Tutorial Field Egg Nest 2": 974,
	"SM: Bottom of Attack Tutorial Field Egg Nest 3": 975,
	"SM: Cheato Page": 976,
	"SM: Cheato Reward 1": 977,
	"SM: Cheato Reward 2": 978,
	"SM: Cheato Reward 3": 979,
	"SM: Cheato Reward 4": 980,
	"SM: Cheato Reward 5": 981,
	"SM: Gruntilda's Lair Egg Nest 1": 982,
	"SM: Gruntilda's Lair Egg Nest 2": 983,
	"SM: Gruntilda's Lair Egg Nest 3": 984,
	"SM: Gruntilda's Lair Egg Nest 4": 985,
	"SM: Gruntilda's Lair Feather Nest 1": 986,
	"SM: Gruntilda's Lair Feather Nest 2": 987,
	"SM: Gruntilda's Lair Feather Nest 3": 988,
	"SM: Jinjo": 989,
	"SM: Near Digger Tunnel Feather Nest 1": 990,
	"SM: Near Digger Tunnel Feather Nest 2": 991,
	"SM: Near Digger Tunnel Feather Nest 3": 992,
	"SM: Pink Mystery Egg": 993,
	"SM: Platform Left of Waterfall Feather Nest 1": 994,
	"SM: Platform Left of Waterfall Feather Nest 2": 995,
	"SM: Roysten Reward 1": 996,
	"SM: Roysten Reward 2": 997,
	"SM: Spiral Mountain Feather Nest 1": 998,
	"SM: Spiral Mountain Feather Nest 2": 999,
	"SM: Spiral Mountain Feather Nest 3": 1000,
	"SM: Top-Right of Waterfall Feather Nest": 1001,
	"Scrat Healed": 1002,
	"TDL: Alcove Near Waterfall Egg Nest 1": 1003,
	"TDL: Alcove Near Waterfall Egg Nest 2": 1004,
	"TDL: Baby T-Rex Roar": 1005,
	"TDL: Behind Mumbo's Skull Glowbo": 1006,
	"TDL: Beside Rocknut Jinjo": 1007,
	"TDL: Big T. Rex Jinjo": 1008,
	"TDL: Bonfire Cavern Entrance Feather Nest": 1009,
	"TDL: Bonfire Cavern Exit Feather Nest": 1010,
	"TDL: Boulder Cheato Page": 1011,
	"TDL: Bridge Rocknut Defeated": 1012,
	"TDL: Chompas Belly Jiggy": 1013,
	"TDL: Chompas Belly Mumbo Token": 1014,
	"TDL: Code of the Dinosaurs Jiggy": 1015,
	"TDL: Dippy Jiggy": 1016,
	"TDL: Dippy Pool Filled": 1017,
	"TDL: Dippy's Pool Cheato Page": 1018,
	"TDL: Entrance Egg Nest": 1019,
	"TDL: Entrance Pillar Button Pressed": 1020,
	"TDL: Flight Pad Pillar Feather Nest 1": 1021,
	"TDL: Flight Pad Pillar Feather Nest 2": 1022,
	"TDL: Flight Pad Pillar Feather Nest 3": 1023,
	"TDL: Hatch Silo": 1024,
	"TDL: Inside The Mountain Near Cheato Page Signpost": 1025,
	"TDL: Inside The Mountain Near Top Signpost": 1026,
	"TDL: Inside The Mountain Terry Egg Hatched": 1027,
	"TDL: Inside the Mountain Cheato Page": 1028,
	"TDL: Inside the Mountain Egg Nest 1": 1029,
	"TDL: Inside the Mountain Egg Nest 2": 1030,
	"TDL: Inside the Mountain Feather Nest 1": 1031,
	"TDL: Inside the Mountain Feather Nest 2": 1032,
	"TDL: Inside the Mountain Gate Switch Pressed": 1033,
	"TDL: Inside the Mountain Path Raised": 1034,
	"TDL: Jail Cell Rocknut Defeated": 1035,
	"TDL: Lakeside Honeycomb": 1036,
	"TDL: Lakeside Note 1": 1037,
	"TDL: Lakeside Note 2": 1038,
	"TDL: Lakeside Note 3": 1039,
	"TDL: Lakeside Terry Egg Hatched": 1040,
	"TDL: Last Terry Baby Brought to Nest": 1041,
	"TDL: Left of Wall with Holes Egg Nest 1": 1042,
	"TDL: Left of Wall with Holes Egg Nest 2": 1043,
	"TDL: Mumbo's Skull Feather Nest 1": 1044,
	"TDL: Mumbo's Skull Feather Nest 2": 1045,
	"TDL: Near River Passage Entrance Egg Nest": 1046,
	"TDL: Near Shock Spring Pad Up the Mountain Egg Nest 1": 1047,
	"TDL: Near Shock Spring Pad Up the Mountain Egg Nest 2": 1048,
	"TDL: Oogle Boogle Cave Gate Opened": 1049,
	"TDL: Oogle Boogle Cave Terry Egg Hatched": 1050,
	"TDL: Oogle Boogle Egg Nest 1": 1051,
	"TDL: Oogle Boogle Egg Nest 2": 1052,
	"TDL: Oogle Boogle Feather Nest 1": 1053,
	"TDL: Oogle Boogle Feather Nest 2": 1054,
	"TDL: Oogle Boogle Tribe Jiggy": 1055,
	"TDL: Outside Mumbo Platforms Enlarged": 1056,
	"TDL: Outside Mumbo's Skull Warp Pad Tagged": 1057,
	"TDL: Outside Wumba's Wigwam Warp Pad Tagged": 1058,
	"TDL: Path to Terry Egg Nest 1": 1059,
	"TDL: Path to Terry Egg Nest 2": 1060,
	"TDL: Path to Terry Feather Nest 1": 1061,
	"TDL: Path to Terry Feather Nest 2": 1062,
	"TDL: Priceless Relic Thingy": 1063,
	"TDL: Right of Scrotty Cave Egg Nest 1": 1064,
	"TDL: Right of Scrotty Cave Egg Nest 2": 1065,
	"TDL: Right of Wall with Holes Egg Nest 1": 1066,
	"TDL: Right of Wall with Holes Egg Nest 2": 1067,
	"TDL: River Passage Feather Nest": 1068,
	"TDL: River Passage Honeycomb": 1069,
	"TDL: River Passage Note 1": 1070,
	"TDL: River Passage Note 2": 1071,
	"TDL: River Passage Note 3": 1072,
	"TDL: River Passage Note 4": 1073,
	"TDL: River Passage Signpost": 1074,
	"TDL: Roar Cage Path Note 1": 1075,
	"TDL: Roar Cage Path Note 2": 1076,
	"TDL: Roar Cage Path Note 3": 1077,
	"TDL: Roar Cage Rocknut Defeated": 1078,
	"TDL: Roar Cage Signpost": 1079,
	"TDL: Rocknut Tribe Jiggy": 1080,
	"TDL: Scrat (Sick)": 1081,
	"TDL: Scrat Back To Scrotty": 1082,
	"TDL: Scrat In Train": 1083,
	"TDL: Scrit (Small)": 1084,
	"TDL: Scrit Boulder Broken": 1085,
	"TDL: Scrit Enlarged": 1086,
	"TDL: Scrotty Jiggy": 1087,
	"TDL: Scrut (Lost)": 1088,
	"TDL: Scrut Back To Scrotty": 1089,
	"TDL: Springy Step Shoes Silo": 1090,
	"TDL: Stomping Plains Jiggy": 1091,
	"TDL: Stomping Plains Jinjo": 1092,
	"TDL: Stomping Plains Left Path Feather Nest 1": 1093,
	"TDL: Stomping Plains Left Path Feather Nest 2": 1094,
	"TDL: Stomping Plains Middle Path Feather Nest": 1095,
	"TDL: Stomping Plains Near Entrance Feather Nest": 1096,
	"TDL: Stomping Plains Right Path Feather Nest 1": 1097,
	"TDL: Stomping Plains Right Path Feather Nest 2": 1098,
	"TDL: Stomping Plains Second Footprint Feather Nest": 1099,
	"TDL: Stomping Plains Solo Banjo Gate Opened": 1100,
	"TDL: Stomping Plains Warp Pad Tagged": 1101,
	"TDL: Styracosaurus Cave Honeycomb": 1102,
	"TDL: Styracosaurus Family Cave Empty Honeycomb Boulder Broken": 1103,
	"TDL: Styracosaurus Family Cave Feather Nest 1": 1104,
	"TDL: Styracosaurus Family Cave Feather Nest 2": 1105,
	"TDL: Styracosaurus Family Cave Feather Nest 3": 1106,
	"TDL: Taxi Pack Silo": 1107,
	"TDL: Terry Defeated": 1108,
	"TDL: Terry Jiggy": 1109,
	"TDL: Terry Mumbo Token": 1110,
	"TDL: Terry's Kids Jiggy": 1111,
	"TDL: Terry's Nest Egg Nest 1": 1112,
	"TDL: Terry's Nest Egg Nest 2": 1113,
	"TDL: Terry's Nest Hole Open": 1114,
	"TDL: Top of the Mountain Egg Nest": 1115,
	"TDL: Top of the Mountain Warp Pad Tagged": 1116,
	"TDL: Train Station Egg Nest 1": 1117,
	"TDL: Train Station Egg Nest 2": 1118,
	"TDL: Train Station Feather Nest 1": 1119,
	"TDL: Train Station Feather Nest 2": 1120,
	"TDL: Train Station Left Note": 1121,
	"TDL: Train Station Middle Note": 1122,
	"TDL: Train Station Right Note": 1123,
	"TDL: Train Station Rocknut Defeated": 1124,
	"TDL: Train Switch": 1125,
	"TDL: Treble Clef": 1126,
	"TDL: Under Terry's Nest Jiggy": 1127,
	"TDL: Underwater Jinjo": 1128,
	"TDL: Underwater Jinjo Switch Pressed": 1129,
	"TDL: Unga Bunga Cave Entrance Glowbo": 1130,
	"TDL: Unga Bunga Cave Gate Near Hatch Silo Opened": 1131,
	"TDL: Unga Bunga Cave Gate Near Springy Step Shoes Opened": 1132,
	"TDL: Unga Bunga Cave Terry Egg Hatched": 1133,
	"TDL: Unga Bunga Spooked": 1134,
	"TDL: Unga Bunga's Cave Egg Nest 1": 1135,
	"TDL: Unga Bunga's Cave Egg Nest 2": 1136,
	"TDL: Unga Bunga's Cave Egg Nest 3": 1137,
	"TDL: Unga Bunga's Cave Feather Nest 1": 1138,
	"TDL: Unga Bunga's Cave Feather Nest 2": 1139,
	"TDL: Unga Bunga's Cave Feather Nest 3": 1140,
	"TDL: Waterfall Cell Rocknut Defeated": 1141,
	"TDL: World Entry and Exit Warp Pad Tagged": 1142,
	"TDL: Wumba's Wigwam Enlarged": 1143,
	"TDL: Zig-Zag Path Note 1": 1144,
	"TDL: Zig-Zag Path Note 2": 1145,
	"TDL: Zig-Zag Path Note 3": 1146,
	"Train At GGM": 1147,
	"Train At GI": 1148,
	"Train At HFP Icy Side": 1149,
	"Train At HFP Lava Side": 1150,
	"Train At IoH": 1151,
	"Train At TDL": 1152,
	"Train At WW": 1153,
	"WW: Airborne Egg Aiming Silo": 1154,
	"WW: Area 51 Egg Nest 1": 1155,
	"WW: Area 51 Egg Nest 2": 1156,
	"WW: Area 51 Gate Left Note": 1157,
	"WW: Area 51 Gate Right Note": 1158,
	"WW: Area 51 Grate Blown Up": 1159,
	"WW: Around the Tent Note 1": 1160,
	"WW: Around the Tent Note 2": 1161,
	"WW: Around the Tent Note 3": 1162,
	"WW: Around the Tent Note 4": 1163,
	"WW: Around the Tent Note 5": 1164,
	"WW: Around the Tent Note 6": 1165,
	"WW: Around the Tent Note 7": 1166,
	"WW: Around the Tent Note 8": 1167,
	"WW: Balloon Burst Jiggy": 1168,
	"WW: Balloon Burst Mumbo Token": 1169,
	"WW: Balloon Burst Won": 1170,
	"WW: Behind the Big Top Tent Warp Pad Tagged": 1171,
	"WW: Big Top Back Pack Egg Nest 1": 1172,
	"WW: Big Top Back Pack Egg Nest 2": 1173,
	"WW: Big Top Back Pack Feather Nest 1": 1174,
	"WW: Big Top Back Pack Feather Nest 2": 1175,
	"WW: Big Top Front Pack Egg Nest 1": 1176,
	"WW: Big Top Front Pack Egg Nest 2": 1177,
	"WW: Big Top Front Pack Feather Nest 1": 1178,
	"WW: Big Top Front Pack Feather Nest 2": 1179,
	"WW: Big Top Jinjo": 1180,
	"WW: Big Top Left Pack Egg Nest 1": 1181,
	"WW: Big Top Left Pack Egg Nest 2": 1182,
	"WW: Big Top Left Pack Feather Nest 1": 1183,
	"WW: Big Top Left Pack Feather Nest 2": 1184,
	"WW: Big Top Right Pack Egg Nest 1": 1185,
	"WW: Big Top Right Pack Egg Nest 2": 1186,
	"WW: Big Top Right Pack Feather Nest 1": 1187,
	"WW: Big Top Right Pack Feather Nest 2": 1188,
	"WW: Burger Stand Signpost": 1189,
	"WW: Burgers Stand Switch Pressed": 1190,
	"WW: Cactus of Strength Jiggy": 1191,
	"WW: Cactus of Strength Jinjo": 1192,
	"WW: Cactus of Strength Signpost": 1193,
	"WW: Cactus of Strength Won": 1194,
	"WW: Cave of Horrors Jinjo": 1195,
	"WW: Crazy Castle Entrance Note 1": 1196,
	"WW: Crazy Castle Entrance Note 2": 1197,
	"WW: Crazy Castle Honeycomb": 1198,
	"WW: Crazy Castle Inflated": 1199,
	"WW: Crazy Castle Stockade Egg Nest 1": 1200,
	"WW: Crazy Castle Stockade Egg Nest 2": 1201,
	"WW: Crazy Castle Stockade Grate Blown Up": 1202,
	"WW: Dive of Death Jiggy": 1203,
	"WW: Dive of Death Note 1": 1204,
	"WW: Dive of Death Note 2": 1205,
	"WW: Dodgem Dome Jiggy": 1206,
	"WW: Dodgem Dome Jinjo": 1207,
	"WW: Dodgem Dome Mumbo Token": 1208,
	"WW: Dodgem Dome Paid": 1209,
	"WW: Dodgem Dome Powered": 1210,
	"WW: Dodgem Dome Round 1 Won": 1211,
	"WW: Dodgem Dome Round 2 Won": 1212,
	"WW: Dodgem Dome Round 3 Won": 1213,
	"WW: Dodgem Dome Signpost": 1214,
	"WW: Entrance Ticket": 1215,
	"WW: Fries Stand Signpost": 1216,
	"WW: Fries Stand Switch Pressed": 1217,
	"WW: Gobi Cage Signpost": 1218,
	"WW: Gobi Freed": 1219,
	"WW: Gondola Button Pressed": 1220,
	"WW: Groggy": 1221,
	"WW: Groggy Fed": 1222,
	"WW: Groggy Quest Completed": 1223,
	"WW: Hoop Hurry Jiggy": 1224,
	"WW: Hoop Hurry Mumbo Token": 1225,
	"WW: Hoop Hurry Won": 1226,
	"WW: Inferno Entrance Paid": 1227,
	"WW: Inferno Spring Pad Button Pressed": 1228,
	"WW: Madame Grunty Signpost": 1229,
	"WW: Moggy": 1230,
	"WW: Moggy Quest Completed": 1231,
	"WW: Mr. Patch Jiggy": 1232,
	"WW: Mr. Patch Mumbo Token": 1233,
	"WW: Mrs. Boggy Jiggy": 1234,
	"WW: Mumbo Skull Honeycomb": 1235,
	"WW: Near Mrs Boggy Egg Nest 1": 1236,
	"WW: Near Mrs Boggy Egg Nest 2": 1237,
	"WW: On Big Top Support Feather Nest 1": 1238,
	"WW: On Big Top Support Feather Nest 2": 1239,
	"WW: On Big Top Support Feather Nest 3": 1240,
	"WW: On Big Top Support Feather Nest 4": 1241,
	"WW: On Big Top Support Feather Nest 5": 1242,
	"WW: On Big Top Support Feather Nest 6": 1243,
	"WW: Outside Dodgem Dome Note 1": 1244,
	"WW: Outside Dodgem Dome Note 2": 1245,
	"WW: Outside Mumbo's Skull Warp Pad Tagged": 1246,
	"WW: Outside Star Spinner Egg Nest 1": 1247,
	"WW: Outside Star Spinner Egg Nest 2": 1248,
	"WW: Outside Wumba's Wigwam Warp Pad Tagged": 1249,
	"WW: Pack Whack Silo": 1250,
	"WW: Pump Room Feather Nest 1": 1251,
	"WW: Pump Room Feather Nest 2": 1252,
	"WW: Pump Room Signpost": 1253,
	"WW: Pump Room Solo Banjo Switch": 1254,
	"WW: Pump Room Solo Kazooie Switch": 1255,
	"WW: Saucer of Peril Button Pressed": 1256,
	"WW: Saucer of Peril Cheato Page": 1257,
	"WW: Saucer of Peril Jiggy": 1258,
	"WW: Saucer of Peril Mumbo Token": 1259,
	"WW: Saucer of Peril Powered": 1260,
	"WW: Scrut Freed": 1261,
	"WW: Scrut In Train": 1262,
	"WW: Soggy": 1263,
	"WW: Soggy Quest Completed": 1264,
	"WW: Space Ticket": 1265,
	"WW: Space Zone Honeycomb": 1266,
	"WW: Space Zone Warp Pad Tagged": 1267,
	"WW: Split Up Silo": 1268,
	"WW: Spooky Ticket": 1269,
	"WW: Star Spinner Egg Nest": 1270,
	"WW: Star Spinner Feather Nest 1": 1271,
	"WW: Star Spinner Feather Nest 2": 1272,
	"WW: Star Spinner Jiggy": 1273,
	"WW: Star Spinner Powered": 1274,
	"WW: The Haunted Cavern Cheato Page": 1275,
	"WW: The Haunted Caverns Egg Nest 1": 1276,
	"WW: The Haunted Caverns Egg Nest 2": 1277,
	"WW: The Haunted Caverns Egg Nest 3": 1278,
	"WW: The Haunted Caverns Signpost": 1279,
	"WW: The Inferno Cheato Page": 1280,
	"WW: The Inferno Egg Nest 1": 1281,
	"WW: The Inferno Egg Nest 2": 1282,
	"WW: The Inferno Glowbo": 1283,
	"WW: The Inferno Jiggy": 1284,
	"WW: Train Station Egg Nest 1": 1285,
	"WW: Train Station Egg Nest 2": 1286,
	"WW: Train Switch": 1287,
	"WW: Treble Clef": 1288,
	"WW: Van Door Jinjo": 1289,
	"WW: Western Ticket": 1290,
	"WW: World Entry and Exit Warp Pad Tagged": 1291,
	"WW: Wumba's Glowbo": 1292
}

exit_name_to_id = {
	"Cauldron Keep -> IoH: Quagmire Behind Cauldron Keep Gate": 1,
	"Cloud Cuckooland -> IoH: Wasteland": 2,
	"GI Basement: AC Plant -> GI Floor 1": 3,
	"GI Basement: AC Plant Big Fan Room -> GI Basement: Waste Disposal Plant From AC Plant": 4,
	"GI Basement: AC Plant Near Repair Depot -> GI: Boss Room": 5,
	"GI Basement: Waste Disposal Plant From AC Plant -> GI Basement: AC Plant Big Fan Room": 6,
	"GI Basement: Waste Disposal Plant One Way Exit -> GI Floor 1: Ducts Near Waste Disposal Plant": 7,
	"GI Basement: Waste Disposal Plant Upper -> GI Floor 1: Top Of Waste Disposal Plant": 8,
	"GI Elevator Shaft: Floor 1 -> GI Floor 1": 9,
	"GI Elevator Shaft: Floor 2 -> GI Floor 2: Electromagnet Chamber Behind Elevator Door": 10,
	"GI Elevator Shaft: Floor 3 -> GI Floor 3: Boiler Plant Behind Elevator Door": 11,
	"GI Elevator Shaft: Floor 4 -> GI Floor 4: Behind Elevator Door": 12,
	"GI Floor 1 -> GI Basement: AC Plant": 13,
	"GI Floor 1 -> GI Elevator Shaft: Floor 1": 14,
	"GI Floor 1 -> GI Floor 1: Start Of Trash Compactor": 15,
	"GI Floor 1 -> GI Floor 1: Worker's Quarters": 16,
	"GI Floor 1 -> GI Train Station": 17,
	"GI Floor 1: Back Door Room -> GI Floor 2: Floor 1 Stairway": 18,
	"GI Floor 1: Back Door Room -> GI Outside: Behind Back Door": 19,
	"GI Floor 1: Behind Main Door -> GI Outside: Behind Main Door": 20,
	"GI Floor 1: Lower Catwalk -> GI Floor 2: Near Service Elevator": 21,
	"GI Floor 1: Middle Of Trash Compactor -> GI Floor 1: Top Of Trash Compactor": 22,
	"GI Floor 1: Start Of Trash Compactor -> GI Floor 1": 23,
	"GI Floor 1: Top Of Trash Compactor -> GI Floor 1: Middle Of Trash Compactor": 24,
	"GI Floor 1: Top Of Waste Disposal Plant -> GI Basement: Waste Disposal Plant Upper": 25,
	"GI Floor 1: Upper Catwalk -> GI Outside: Behind Floor 1 Window": 26,
	"GI Floor 1: Worker's Quarters -> GI Floor 1": 27,
	"GI Floor 2: Behind Electromagnet Chamber Door -> GI Floor 2: Electromagnet Chamber": 28,
	"GI Floor 2: Behind Grate Near Electromagnet Chamber -> GI Floor 2: Behind Grate Near Humba": 29,
	"GI Floor 2: Behind Grate Near Humba -> GI Floor 2: Behind Grate Near Electromagnet Chamber": 30,
	"GI Floor 2: Electromagnet Chamber -> GI Floor 2: Behind Electromagnet Chamber Door": 31,
	"GI Floor 2: Electromagnet Chamber Behind Elevator Door -> GI Elevator Shaft: Floor 2": 32,
	"GI Floor 2: Floor 1 Stairway -> GI Floor 1: Back Door Room": 33,
	"GI Floor 2: Near Service Elevator -> GI Floor 1: Lower Catwalk": 34,
	"GI Floor 2: Near Window With Page -> GI Outside: Behind Window Above Front Train Tunnel": 35,
	"GI Floor 2: Near Window With Unscrewable Plate -> GI Outside: Behind Window Near Back Train Tunnel": 36,
	"GI Floor 2: Near Wumba's Wigwam -> GI Floor 2: Wumba's Wigwam": 37,
	"GI Floor 2: Platform Near Floor 3 -> GI Floor 3: Floor 2 Platform": 38,
	"GI Floor 2: Wumba's Wigwam -> GI Floor 2: Near Wumba's Wigwam": 39,
	"GI Floor 3: Boiler Plant -> GI Floor 3: Top Of Boxes Near Boiler Plant": 40,
	"GI Floor 3: Boiler Plant Behind Elevator Door -> GI Elevator Shaft: Floor 3": 41,
	"GI Floor 3: Boiler Plant Behind Twinkly Packing Door -> GI Floor 3: Twinkly Packing": 42,
	"GI Floor 3: Catwalk -> GI Outside: Fire Exit Lower": 43,
	"GI Floor 3: Floor 2 Platform -> GI Floor 2: Platform Near Floor 3": 44,
	"GI Floor 3: Mumbo's Skull -> GI Floor 3: Outside Mumbo's Skull": 45,
	"GI Floor 3: Outside Mumbo's Skull -> GI Floor 2: Near Wumba's Wigwam": 46,
	"GI Floor 3: Outside Mumbo's Skull -> GI Floor 3: Mumbo's Skull": 47,
	"GI Floor 3: Top Of Boxes Near Boiler Plant -> GI Floor 3: Boiler Plant": 48,
	"GI Floor 3: Twinkly Packing -> GI Floor 3: Boiler Plant Behind Twinkly Packing Door": 49,
	"GI Floor 4: After Crushers -> GI Floor 4: Before Crushers Catwalk": 50,
	"GI Floor 4: After Crushers Lower Catwalk -> GI Floor 4: Cable Room": 51,
	"GI Floor 4: After Crushers Upper Catwalk -> GI Floor 4: Sewer Entrance": 52,
	"GI Floor 4: Before Crushers Catwalk -> GI Floor 5: Storage Area 1 Near Floor Exit": 53,
	"GI Floor 4: Behind Elevator Door -> GI Elevator Shaft: Floor 4": 54,
	"GI Floor 4: Cable Room -> GI Floor 4: After Crushers Lower Catwalk": 55,
	"GI Floor 4: Clinkers Cavern -> GI Floor 4: Sewer Entrance": 56,
	"GI Floor 4: Fire Exit Platform -> GI Outside: Fire Exit Upper": 57,
	"GI Floor 4: Sewer Entrance -> GI Floor 4: After Crushers Upper Catwalk": 58,
	"GI Floor 4: Sewer Entrance -> GI Floor 4: Clinkers Cavern": 59,
	"GI Floor 5: Storage Area 1 Catwalk -> GI Outside: Upper Roof Side Window": 60,
	"GI Floor 5: Storage Area 1 Near Floor Exit -> GI Floor 4: Before Crushers Catwalk": 61,
	"GI Floor 5: Storage Area 2 Top Of Boxes Near Exit -> GI Outside: Upper Roof": 62,
	"GI Outside: Behind Back Door -> GI Floor 1: Back Door Room": 63,
	"GI Outside: Behind Floor 1 Window -> GI Floor 1: Upper Catwalk": 64,
	"GI Outside: Behind Main Door -> GI Floor 1: Behind Main Door": 65,
	"GI Outside: Behind Window Above Front Train Tunnel -> GI Floor 2: Near Window With Page": 66,
	"GI Outside: Behind Window Near Back Train Tunnel -> GI Floor 2: Near Window With Unscrewable Plate": 67,
	"GI Outside: Fire Exit Lower -> GI Floor 3: Catwalk": 68,
	"GI Outside: Fire Exit Upper -> GI Floor 4: Fire Exit Platform": 69,
	"GI Outside: Flying -> GI Floor 3: Boiler Plant Top of Boiler": 70,
	"GI Outside: Upper Roof -> GI Floor 5: Storage Area 2 Top Of Boxes Near Exit": 71,
	"GI Outside: Upper Roof Side Window -> GI Floor 5: Storage Area 1 Catwalk": 72,
	"GI Train Station -> GI Floor 1": 73,
	"GI: Boss Room -> GI Basement: AC Plant Near Repair Depot": 74,
	"Glitter Gulch Mine -> IoH: Plateau: Leaving GGM": 75,
	"Grunty Industries -> IoH: Quagmire Behind GI Door": 76,
	"Hailfire Peaks -> IoH: Cliff Top Around HFP": 77,
	"IoH: Cliff Top -> Jolly Roger's Lagoon": 78,
	"IoH: Cliff Top Around HFP -> Hailfire Peaks": 79,
	"IoH: Pine Grove Behind Witchyworld Gate -> Witchyworld": 80,
	"IoH: Plateau: Leaving GGM -> Glitter Gulch Mine": 81,
	"IoH: Quagmire Behind Cauldron Keep Gate -> Cauldron Keep": 82,
	"IoH: Quagmire Behind GI Door -> Grunty Industries": 83,
	"IoH: Wasteland -> Cloud Cuckooland": 84,
	"IoH: Wasteland Behind TDL Teeth -> Terrydactyland": 85,
	"IoH: Wooded Hollow -> Mayahem Temple": 86,
	"Jolly Roger's Lagoon -> IoH: Cliff Top": 87,
	"MT: Kickball Stadium -> MT: Main Map": 88,
	"MT: Main Map -> MT: Mumbo's Skull": 89,
	"MT: Main Map -> MT: Targitzan's Temple Lobby": 90,
	"MT: Main Map -> MT: Treasure Chamber Bottom": 91,
	"MT: Top Platform Outside Treasure Chamber -> MT: Treasure Chamber In Front of Unga Bunga Gate": 92,
	"MT: Treasure Chamber Bottom -> MT: Main Map": 93,
	"MT: Wumba's Wigwam -> MT: Jade Snake Grove": 94,
	"Mayahem Temple -> IoH: Wooded Hollow": 95,
	"Terrydactyland -> IoH: Wasteland": 96,
	"Witchyworld -> IoH: Pine Grove Behind Witchyworld Gate": 97
}

class AP_CMD:
	NONE = 0
	HANDSHAKE = 1
	PING = 2
	PONG = 3
	STATE = 4
	INFO = 5
	OPTIONS = 6
	LOCATIONS = 7
	ITEMS = 8
	MESSAGE = 9
	DEATH_LINK = 10
	TAG_LINK = 11

class AP_STATE:
	DISCONNECTED = 0
	CONNECTING = 1
	CONNECTED = 2
	PINGED = 4
