# Automatically generated using gen_constants.py

slot_data_names = [
  "add_hints_to_archipelago",
  "auto_enable_cheats",
  "chosen_eggs",
  "chosen_goals",
  "chosen_move_silo_costs",
  "death_link",
  "dialog_character",
  "easy_canary",
  "extra_bass_clefs",
  "extra_cheato_pages",
  "extra_cheats",
  "extra_doubloons",
  "extra_egg_nests",
  "extra_empty_honeycombs",
  "extra_feather_nests",
  "extra_jiggies",
  "extra_mumbo_tokens",
  "extra_note_nests",
  "extra_treble_clefs",
  "golden_egg_nests",
  "hint_clarity",
  "instant_transform",
  "jiggywiggys_challenge_costs",
  "jiggywiggys_challenges",
  "logic_tricks",
  "max_mumbo_tokens",
  "move_hints",
  "move_silo_costs",
  "open_back_doors",
  "open_gi_front_door",
  "open_hag1",
  "open_warp_silos",
  "preset_jiggywiggys_challenge_costs",
  "preset_logic_tricks",
  "preset_victory_goals",
  "progressive_aiming",
  "progressive_aiming_list",
  "progressive_bash_attack",
  "progressive_beak_buster",
  "progressive_eggs",
  "progressive_flight",
  "progressive_flight_list",
  "progressive_shoes",
  "progressive_shoes_list",
  "progressive_water_training",
  "progressive_water_training_list",
  "replace_excess_jiggies",
  "replace_excess_mumbo_tokens",
  "replace_excess_note_nests",
  "shuffle_beans",
  "shuffle_big_top_tickets",
  "shuffle_bk_moves",
  "shuffle_boss_entrances",
  "shuffle_bt_moves",
  "shuffle_cheato_pages",
  "shuffle_cheato_rewards",
  "shuffle_chuffy",
  "shuffle_doubloons",
  "shuffle_glowbos",
  "shuffle_green_relics",
  "shuffle_honeyb_rewards",
  "shuffle_honeycombs",
  "shuffle_jiggywiggys_super_special_challenge",
  "shuffle_jinjos",
  "shuffle_nests",
  "shuffle_note_nests",
  "shuffle_signs",
  "shuffle_stop_n_swop",
  "shuffle_train_stations",
  "shuffle_treble_clefs",
  "shuffle_warp_pads",
  "shuffle_warp_silos",
  "shuffle_world_entrances",
  "shuffle_world_order",
  "sign_hints",
  "skip_klungo",
  "slip_traps",
  "speedup_minigames",
  "squish_traps",
  "starting_eggs",
  "tag_link",
  "tip_traps",
  "tower_of_tragedy",
  "transform_traps",
  "trip_traps",
  "victory_goals"
]

option_name_to_id = {
  "death_link": 0,
  "tag_link": 1,
  "preset_victory_goals": 2,
  "victory_goals_hag_1": 3,
  "victory_goals_targitzan": 4,
  "victory_goals_old_king_coal": 5,
  "victory_goals_mr_patch": 6,
  "victory_goals_lord_woo_fak_fak": 7,
  "victory_goals_terry": 8,
  "victory_goals_weldar": 9,
  "victory_goals_chilly_willy": 10,
  "victory_goals_chilli_billi": 11,
  "victory_goals_mingy_jongo": 12,
  "victory_goals_mt_kickball": 13,
  "victory_goals_ordnance_storage": 14,
  "victory_goals_hoop_hurry": 15,
  "victory_goals_dodgem_dome": 16,
  "victory_goals_saucer_of_peril": 17,
  "victory_goals_balloon_burst": 18,
  "victory_goals_mini_sub_challenge": 19,
  "victory_goals_chompas_belly": 20,
  "victory_goals_clinkers_cavern": 21,
  "victory_goals_twinkly_packing": 22,
  "victory_goals_hfp_kickball": 23,
  "victory_goals_pot_o_gold": 24,
  "victory_goals_zubbas": 25,
  "victory_goals_trash_can": 26,
  "victory_goals_canary_mary": 27,
  "victory_goals_tower_of_tragedy": 28,
  "victory_goals_white_jinjo_family": 29,
  "victory_goals_orange_jinjo_family": 30,
  "victory_goals_yellow_jinjo_family": 31,
  "victory_goals_brown_jinjo_family": 32,
  "victory_goals_green_jinjo_family": 33,
  "victory_goals_red_jinjo_family": 34,
  "victory_goals_blue_jinjo_family": 35,
  "victory_goals_purple_jinjo_family": 36,
  "victory_goals_black_jinjo_family": 37,
  "extra_mumbo_tokens": 38,
  "max_mumbo_tokens": 39,
  "replace_excess_mumbo_tokens": 40,
  "open_hag1": 41,
  "preset_logic_tricks_easy_tricks": 42,
  "preset_logic_tricks_easy_tedious_tricks": 43,
  "preset_logic_tricks_easy_glitches": 44,
  "preset_logic_tricks_hard_tricks": 45,
  "preset_logic_tricks_hard_tedious_tricks": 46,
  "preset_logic_tricks_hard_glitches": 47,
  "preset_logic_tricks_frame_perfect": 48,
  "logic_tricks_beak_barge_jump": 49,
  "logic_tricks_beak_buster_fall": 50,
  "logic_tricks_beak_buster_jump": 51,
  "logic_tricks_bill_drill_jump": 52,
  "logic_tricks_breegull_bash_fall": 53,
  "logic_tricks_air_rat_a_tat_grab": 54,
  "logic_tricks_breegull_bash_grab": 55,
  "logic_tricks_dragunda_sidle": 56,
  "logic_tricks_easy_jumps": 57,
  "logic_tricks_gi_extra_loggo_moves": 58,
  "logic_tricks_ground_rat_a_tat_rap_fall": 59,
  "logic_tricks_ground_rat_a_tat_rap_jump": 60,
  "logic_tricks_pack_whack_fall": 61,
  "logic_tricks_pack_whack_jump": 62,
  "logic_tricks_pack_whack_slope_jump": 63,
  "logic_tricks_roll_jump": 64,
  "logic_tricks_sack_pack_air_jump": 65,
  "logic_tricks_sack_pack_fall": 66,
  "logic_tricks_shack_pack_air_jump": 67,
  "logic_tricks_shack_pack_fall": 68,
  "logic_tricks_snooze_pack_fall": 69,
  "logic_tricks_taxi_pack_fall": 70,
  "logic_tricks_slope_jump": 71,
  "logic_tricks_dive_skip": 72,
  "logic_tricks_beak_bomb_tricks": 73,
  "logic_tricks_damage_boost": 74,
  "logic_tricks_damage_boost_jump": 75,
  "logic_tricks_death_warp": 76,
  "logic_tricks_easy_tedious_jumps": 77,
  "logic_tricks_extra_clockwork_usage": 78,
  "logic_tricks_fall_damage": 79,
  "logic_tricks_gi_quality_control_vent_as_banjo": 80,
  "logic_tricks_gi_guarded_jiggy_without_fighting": 81,
  "logic_tricks_instant_transform_trick": 82,
  "logic_tricks_talon_trot_smuggle": 83,
  "logic_tricks_talon_trot_smuggle_cross_world": 84,
  "logic_tricks_wonderwing_damage_boost": 85,
  "logic_tricks_wonderwing_fall": 86,
  "logic_tricks_wonderwing_jump": 87,
  "logic_tricks_bovina_with_beak_bomb": 88,
  "logic_tricks_air_rat_a_tat_rap_clip": 89,
  "logic_tricks_beak_barge_clip": 90,
  "logic_tricks_breegull_bash_clip": 91,
  "logic_tricks_free_shock_spring_pad": 92,
  "logic_tricks_taxi_pack_clip": 93,
  "logic_tricks_hard_jumps": 94,
  "logic_tricks_slide_jump": 95,
  "logic_tricks_flap_flip_slide_extension": 96,
  "logic_tricks_extra_attacks": 97,
  "logic_tricks_hard_tedious_jumps": 98,
  "logic_tricks_bovina_with_flap_flip": 99,
  "logic_tricks_beak_bomb_clips": 100,
  "logic_tricks_clip_past_pine_grove_boulder": 101,
  "logic_tricks_clockwork_warp": 102,
  "logic_tricks_talon_trot_slide_jump": 103,
  "logic_tricks_sack_pack_ending_jump": 104,
  "instant_transform": 105,
  "shuffle_bk_moves": 106,
  "shuffle_bt_moves": 107,
  "shuffle_glowbos": 108,
  "shuffle_jinjos": 109,
  "shuffle_treble_clefs": 110,
  "shuffle_note_nests": 111,
  "shuffle_honeycombs": 112,
  "shuffle_honeyb_rewards": 113,
  "shuffle_cheato_pages": 114,
  "shuffle_cheato_rewards": 115,
  "shuffle_stop_n_swop": 116,
  "shuffle_doubloons": 117,
  "shuffle_green_relics": 118,
  "shuffle_big_top_tickets": 119,
  "shuffle_beans": 120,
  "shuffle_warp_silos": 121,
  "shuffle_warp_pads": 122,
  "shuffle_signs": 123,
  "shuffle_jiggywiggys_super_special_challenge": 124,
  "shuffle_nests": 125,
  "shuffle_chuffy": 126,
  "shuffle_train_stations": 127,
  "shuffle_world_order": 128,
  "shuffle_world_entrances": 129,
  "shuffle_boss_entrances": 130,
  "progressive_eggs": 131,
  "progressive_aiming": 132,
  "progressive_flight": 133,
  "progressive_water_training": 134,
  "progressive_beak_buster": 135,
  "progressive_bash_attack": 136,
  "progressive_shoes": 137,
  "progressive_aiming_list_third_person_egg_shooting": 138,
  "progressive_aiming_list_amaze_o_gaze": 139,
  "progressive_aiming_list_egg_aim": 140,
  "progressive_aiming_list_breegull_blaster": 141,
  "progressive_flight_list_flight_pad": 142,
  "progressive_flight_list_beak_bomb": 143,
  "progressive_flight_list_airborne_egg_aiming": 144,
  "progressive_water_training_list_dive": 145,
  "progressive_water_training_list_sub_aqua_egg_aiming": 146,
  "progressive_water_training_list_talon_torpedo": 147,
  "progressive_water_training_list_double_air": 148,
  "progressive_water_training_list_fast_swimming": 149,
  "progressive_shoes_list_stilt_stride": 150,
  "progressive_shoes_list_turbo_trainers": 151,
  "progressive_shoes_list_springy_step_shoes": 152,
  "progressive_shoes_list_claw_clamber_boots": 153,
  "skip_klungo": 154,
  "tower_of_tragedy": 155,
  "speedup_minigames": 156,
  "open_gi_front_door": 157,
  "open_back_doors": 158,
  "easy_canary": 159,
  "sign_hints": 160,
  "move_hints": 161,
  "hint_clarity": 162,
  "add_hints_to_archipelago": 163,
  "replace_excess_jiggies": 164,
  "replace_excess_note_nests": 165,
  "extra_jiggies": 166,
  "extra_note_nests": 167,
  "extra_bass_clefs": 168,
  "extra_treble_clefs": 169,
  "extra_doubloons": 170,
  "extra_empty_honeycombs": 171,
  "extra_cheato_pages": 172,
  "extra_egg_nests": 173,
  "extra_feather_nests": 174,
  "trip_traps": 175,
  "slip_traps": 176,
  "tip_traps": 177,
  "transform_traps": 178,
  "golden_egg_nests": 179,
  "squish_traps": 180,
  "jiggywiggys_challenges": 181,
  "preset_jiggywiggys_challenge_costs": 182,
  "jiggywiggys_challenge_costs_challenge_1": 183,
  "jiggywiggys_challenge_costs_challenge_2": 184,
  "jiggywiggys_challenge_costs_challenge_3": 185,
  "jiggywiggys_challenge_costs_challenge_4": 186,
  "jiggywiggys_challenge_costs_challenge_5": 187,
  "jiggywiggys_challenge_costs_challenge_6": 188,
  "jiggywiggys_challenge_costs_challenge_7": 189,
  "jiggywiggys_challenge_costs_challenge_8": 190,
  "jiggywiggys_challenge_costs_challenge_9": 191,
  "jiggywiggys_challenge_costs_challenge_10": 192,
  "jiggywiggys_challenge_costs_challenge_11": 193,
  "starting_eggs_blue_eggs": 194,
  "starting_eggs_fire_eggs": 195,
  "starting_eggs_grenade_eggs": 196,
  "starting_eggs_ice_eggs": 197,
  "starting_eggs_clockwork_kazooie_eggs": 198,
  "open_warp_silos": 199,
  "move_silo_costs": 200,
  "extra_cheats": 201,
  "auto_enable_cheats_feathers": 202,
  "auto_enable_cheats_eggs": 203,
  "auto_enable_cheats_fallproof": 204,
  "auto_enable_cheats_honeyback": 205,
  "auto_enable_cheats_homing_eggs": 206,
  "dialog_character_alien": 207,
  "dialog_character_alien_child": 208,
  "dialog_character_all": 209,
  "dialog_character_banjo": 210,
  "dialog_character_banjo_kazooie": 211,
  "dialog_character_bargasaurus": 212,
  "dialog_character_beehive": 213,
  "dialog_character_bigga_foot": 214,
  "dialog_character_big_al": 215,
  "dialog_character_blobbelda": 216,
  "dialog_character_boggy": 217,
  "dialog_character_bottles": 218,
  "dialog_character_bottles_dead": 219,
  "dialog_character_bovina": 220,
  "dialog_character_canary_mary": 221,
  "dialog_character_captain_blackeye": 222,
  "dialog_character_captain_blubber": 223,
  "dialog_character_cheato": 224,
  "dialog_character_chief_bloatazin": 225,
  "dialog_character_chilli_billi": 226,
  "dialog_character_chilly_willy": 227,
  "dialog_character_chompa": 228,
  "dialog_character_chris_p_bacon": 229,
  "dialog_character_conga": 230,
  "dialog_character_dilberta": 231,
  "dialog_character_dingpot": 232,
  "dialog_character_dino_kid1": 233,
  "dialog_character_dino_kid2": 234,
  "dialog_character_dino_scrit_big": 235,
  "dialog_character_dino_scrit_small": 236,
  "dialog_character_dippy": 237,
  "dialog_character_evil_bottles": 238,
  "dialog_character_george": 239,
  "dialog_character_gi_announcer": 240,
  "dialog_character_glowbo": 241,
  "dialog_character_gobi": 242,
  "dialog_character_goggles": 243,
  "dialog_character_groggy": 244,
  "dialog_character_grunty": 245,
  "dialog_character_guffo": 246,
  "dialog_character_heggy": 247,
  "dialog_character_honeycomb": 248,
  "dialog_character_honey_b": 249,
  "dialog_character_humba": 250,
  "dialog_character_jamjars": 251,
  "dialog_character_jiggy": 252,
  "dialog_character_jiggywiggy": 253,
  "dialog_character_jiggywiggy_disciple": 254,
  "dialog_character_jinjo_black": 255,
  "dialog_character_jinjo_blue": 256,
  "dialog_character_jinjo_brown": 257,
  "dialog_character_jinjo_green": 258,
  "dialog_character_jinjo_orange": 259,
  "dialog_character_jinjo_purple": 260,
  "dialog_character_jinjo_red": 261,
  "dialog_character_jinjo_white": 262,
  "dialog_character_jinjo_yellow": 263,
  "dialog_character_jolly": 264,
  "dialog_character_kazooie": 265,
  "dialog_character_king_jingaling": 266,
  "dialog_character_king_jingaling_dead": 267,
  "dialog_character_klungo": 268,
  "dialog_character_loggo": 269,
  "dialog_character_lord_woo_fak_fak": 270,
  "dialog_character_merry_maggie": 271,
  "dialog_character_mildred": 272,
  "dialog_character_mingella": 273,
  "dialog_character_mingy_jongo": 274,
  "dialog_character_minjo_black": 275,
  "dialog_character_minjo_blue": 276,
  "dialog_character_minjo_brown": 277,
  "dialog_character_minjo_green": 278,
  "dialog_character_minjo_orange": 279,
  "dialog_character_minjo_purple": 280,
  "dialog_character_minjo_red": 281,
  "dialog_character_minjo_white": 282,
  "dialog_character_minjo_yellow": 283,
  "dialog_character_moggy": 284,
  "dialog_character_mrs_boggy": 285,
  "dialog_character_mrs_bottles": 286,
  "dialog_character_mr_fit": 287,
  "dialog_character_mr_patch": 288,
  "dialog_character_mumbo": 289,
  "dialog_character_old_king_coal": 290,
  "dialog_character_oogle_boogle": 291,
  "dialog_character_pawno": 292,
  "dialog_character_pig1": 293,
  "dialog_character_prospector": 294,
  "dialog_character_rabbit_worker1": 295,
  "dialog_character_rocknut": 296,
  "dialog_character_roysten": 297,
  "dialog_character_sabreman": 298,
  "dialog_character_safe": 299,
  "dialog_character_salty_joe": 300,
  "dialog_character_soggy": 301,
  "dialog_character_speccy": 302,
  "dialog_character_ssslumber": 303,
  "dialog_character_stonies1": 304,
  "dialog_character_styracosaurus_mom": 305,
  "dialog_character_sub": 306,
  "dialog_character_targitzan": 307,
  "dialog_character_terry": 308,
  "dialog_character_tiptup": 309,
  "dialog_character_ufo": 310,
  "dialog_character_unga_bunga": 311,
  "dialog_character_unogopaz": 312,
  "dialog_character_washer": 313,
  "dialog_character_weldar": 314,
  "dialog_character_yellow_dodgem": 315,
  "dialog_character_yellow_stony": 316,
  "dialog_character_zubba": 317,
  "chosen_eggs": 318,
  "chosen_goals_hag_1": 319,
  "chosen_goals_targitzan": 320,
  "chosen_goals_old_king_coal": 321,
  "chosen_goals_mr_patch": 322,
  "chosen_goals_lord_woo_fak_fak": 323,
  "chosen_goals_terry": 324,
  "chosen_goals_weldar": 325,
  "chosen_goals_chilly_willy": 326,
  "chosen_goals_chilli_billi": 327,
  "chosen_goals_mingy_jongo": 328,
  "chosen_goals_mt_kickball": 329,
  "chosen_goals_ordnance_storage": 330,
  "chosen_goals_hoop_hurry": 331,
  "chosen_goals_dodgem_dome": 332,
  "chosen_goals_saucer_of_peril": 333,
  "chosen_goals_balloon_burst": 334,
  "chosen_goals_mini_sub_challenge": 335,
  "chosen_goals_chompas_belly": 336,
  "chosen_goals_clinkers_cavern": 337,
  "chosen_goals_twinkly_packing": 338,
  "chosen_goals_hfp_kickball": 339,
  "chosen_goals_pot_o_gold": 340,
  "chosen_goals_zubbas": 341,
  "chosen_goals_trash_can": 342,
  "chosen_goals_canary_mary": 343,
  "chosen_goals_tower_of_tragedy": 344,
  "chosen_goals_white_jinjo_family": 345,
  "chosen_goals_orange_jinjo_family": 346,
  "chosen_goals_yellow_jinjo_family": 347,
  "chosen_goals_brown_jinjo_family": 348,
  "chosen_goals_green_jinjo_family": 349,
  "chosen_goals_red_jinjo_family": 350,
  "chosen_goals_blue_jinjo_family": 351,
  "chosen_goals_purple_jinjo_family": 352,
  "chosen_goals_black_jinjo_family": 353,
  "chosen_move_silo_costs_fire_eggs": 354,
  "chosen_move_silo_costs_grenade_eggs": 355,
  "chosen_move_silo_costs_ice_eggs": 356,
  "chosen_move_silo_costs_clockwork_kazooie_eggs": 357,
  "chosen_move_silo_costs_egg_aim": 358,
  "chosen_move_silo_costs_breegull_blaster": 359,
  "chosen_move_silo_costs_grip_grab": 360,
  "chosen_move_silo_costs_bill_drill": 361,
  "chosen_move_silo_costs_beak_bayonet": 362,
  "chosen_move_silo_costs_split_up": 363,
  "chosen_move_silo_costs_pack_whack": 364,
  "chosen_move_silo_costs_airborne_egg_aiming": 365,
  "chosen_move_silo_costs_wing_whack": 366,
  "chosen_move_silo_costs_sub_aqua_egg_aiming": 367,
  "chosen_move_silo_costs_talon_torpedo": 368,
  "chosen_move_silo_costs_springy_step_shoes": 369,
  "chosen_move_silo_costs_taxi_pack": 370,
  "chosen_move_silo_costs_hatch": 371,
  "chosen_move_silo_costs_claw_clamber_boots": 372,
  "chosen_move_silo_costs_snooze_pack": 373,
  "chosen_move_silo_costs_leg_spring": 374,
  "chosen_move_silo_costs_shack_pack": 375,
  "chosen_move_silo_costs_glide": 376,
  "chosen_move_silo_costs_sack_pack": 377
}

item_name_to_id = {
  "Air Rat-a-tat Rap": 1,
  "Airborne Egg Aiming": 2,
  "Amaze-O-Gaze": 3,
  "Baby T-Rex Roar": 4,
  "Bass Clef": 5,
  "Beak Barge": 6,
  "Beak Bayonet": 7,
  "Beak Bomb": 8,
  "Beak Buster": 9,
  "Bean": 10,
  "Big Top Ticket": 11,
  "Big-O Pants": 12,
  "Bill Drill": 13,
  "Black Jinjo": 14,
  "Blue Eggs": 15,
  "Blue Jinjo": 16,
  "Blue Mystery Egg": 17,
  "Breegull Bash": 18,
  "Breegull Blaster": 19,
  "Brown Jinjo": 20,
  "CCL: Central Cavern Warp Pad": 21,
  "CCL: World Entry And Exit Warp Pad": 22,
  "CK: Bottom Of The Tower Warp Pad": 23,
  "CK: Top Of The Tower Warp Pad": 24,
  "Cauldron Keep": 25,
  "Cheato Page": 26,
  "Cheato Reward: Eggs": 27,
  "Cheato Reward: Fallproof": 28,
  "Cheato Reward: Feathers": 29,
  "Cheato Reward: Honeyback": 30,
  "Cheato Reward: Jukebox": 31,
  "Chuffy": 32,
  "Claw Clamber Boots": 33,
  "Cliff Top Warp Silo": 34,
  "Climb": 35,
  "Clockwork Kazooie Eggs": 36,
  "Cloud Cuckooland": 37,
  "Dive": 38,
  "Double Air": 39,
  "Doubloon": 40,
  "Egg Aim": 41,
  "Egg Nest": 42,
  "Empty Honeycomb": 43,
  "Fast Swimming": 44,
  "Feather Nest": 45,
  "Fire Eggs": 46,
  "Flap Flip": 47,
  "Flight Pad": 48,
  "Flutter": 49,
  "GGM: Inside Wumba's Wigwam Warp Pad": 50,
  "GGM: Near The Train Station Warp Pad": 51,
  "GGM: Outside Mumbo's Skull Warp Pad": 52,
  "GGM: Outside The Crushing Shed Warp Pad": 53,
  "GGM: World Entry And Exit Warp Pad": 54,
  "GI Cleaned Skivvy": 55,
  "GI Floor 1: Entrance Door Warp Pad": 56,
  "GI Floor 2: Outside Wumba's Wigwam Warp Pad": 57,
  "GI Floor 3: Outside Mumbo's Skull Warp Pad": 58,
  "GI Floor 4: Near The Crushers Warp Pad": 59,
  "GI Outside: On The Roof Outside Warp Pad": 60,
  "GI: Train Station": 61,
  "Glide": 62,
  "Glitter Gulch Mine": 63,
  "Golden Egg Nest": 64,
  "Green Jinjo": 65,
  "Green Relic": 66,
  "Grenade Eggs": 67,
  "Grip Grab": 68,
  "Ground Rat-a-tat Rap": 69,
  "Grunty Industries": 70,
  "HAG-1": 71,
  "HFP: Fire Side - Lower Area (Mumbo) Warp Pad": 72,
  "HFP: Fire Side - Upper Area Warp Pad": 73,
  "HFP: Ice Side - Inside Icicle Grotto Warp Pad": 74,
  "HFP: Ice Side - Lower Area (Wumba) Warp Pad": 75,
  "HFP: Ice Side - Upper Area Warp Pad": 76,
  "HFP: Icy Side Train Station": 77,
  "HFP: Lava Side Train Station": 78,
  "Hailfire Peaks": 79,
  "Hatch": 80,
  "Health Upgrade": 81,
  "Homing Eggs": 82,
  "Humba: Bee": 83,
  "Humba: Detonator": 84,
  "Humba: Dragon": 85,
  "Humba: Money Van": 86,
  "Humba: Snowball": 87,
  "Humba: Stony": 88,
  "Humba: Sub": 89,
  "Humba: T-Rex": 90,
  "Humba: Washing Machine": 91,
  "Ice Eggs": 92,
  "Ice Key": 93,
  "IoH: Train Station": 94,
  "JRL: Atlantis Warp Pad": 95,
  "JRL: Big Fish Cavern Warp Pad": 96,
  "JRL: Lockers Cavern Warp Pad": 97,
  "JRL: Sunken Ship Warp Pad": 98,
  "JRL: Town Center Warp Pad": 99,
  "Jiggy": 100,
  "Jinjo Village Warp Silo": 101,
  "Jolly Roger's Lagoon": 102,
  "Leg Spring": 103,
  "MT: Kickball Stadium Lobby Warp Pad": 104,
  "MT: Near Wumba's Wigwam Warp Pad": 105,
  "MT: Outside Mumbo's Skull Warp Pad": 106,
  "MT: Prison Compound Warp Pad": 107,
  "MT: Snake Head": 108,
  "MT: World Entry And Exit Warp Pad": 109,
  "Mayahem Temple": 110,
  "Mumbo Token": 111,
  "Mumbo: EMP": 112,
  "Mumbo: Enlarge": 113,
  "Mumbo: Golden Goliath": 114,
  "Mumbo: Heal": 115,
  "Mumbo: Levitate": 116,
  "Mumbo: Life Force": 117,
  "Mumbo: Oxygenate": 118,
  "Mumbo: Power": 119,
  "Mumbo: Rain Dance": 120,
  "Note Nest": 121,
  "Nothing": 122,
  "Orange Jinjo": 123,
  "Pack Whack": 124,
  "Pine Grove Warp Silo": 125,
  "Pink Mystery Egg": 126,
  "Plateau Warp Silo": 127,
  "Progressive Aiming": 128,
  "Progressive Bash Attack": 129,
  "Progressive Beak Buster": 130,
  "Progressive Eggs": 131,
  "Progressive Flight": 132,
  "Progressive Shoes": 133,
  "Progressive Water Training": 134,
  "Purple Jinjo": 135,
  "Quagmire Warp Silo": 136,
  "Red Jinjo": 137,
  "Roll": 138,
  "Sack Pack": 139,
  "Shack Pack": 140,
  "Slip Trap": 141,
  "Snooze Pack": 142,
  "Split Up": 143,
  "Springy Step Shoes": 144,
  "Squish Trap": 145,
  "Stilt Stride": 146,
  "Sub-Aqua Egg Aiming": 147,
  "TDL: Outside Mumbo's Skull Warp Pad": 148,
  "TDL: Outside Wumba's Wigwam Warp Pad": 149,
  "TDL: Stomping Plains Warp Pad": 150,
  "TDL: Top Of The Mountain Warp Pad": 151,
  "TDL: Train Station": 152,
  "TDL: World Entry And Exit Warp Pad": 153,
  "Tall Jump": 154,
  "Talon Torpedo": 155,
  "Talon Trot": 156,
  "Taxi Pack": 157,
  "Terrydactyland": 158,
  "Third Person Egg Shooting": 159,
  "Tip Trap": 160,
  "Transform Trap": 161,
  "Treble Clef": 162,
  "Trip Trap": 163,
  "Turbo Trainers": 164,
  "WW: Behind The Big Top Tent Warp Pad": 165,
  "WW: Outside Mumbo's Skull Warp Pad": 166,
  "WW: Outside Wumba's Wigwam Warp Pad": 167,
  "WW: Space Zone Warp Pad": 168,
  "WW: Train Station": 169,
  "WW: World Entry And Exit Warp Pad": 170,
  "Wasteland Warp Silo": 171,
  "White Jinjo": 172,
  "Wing Whack": 173,
  "Witchyworld": 174,
  "Wonderwing": 175,
  "Wooded Hollow Warp Silo": 176,
  "Yellow Jinjo": 177
}

location_name_to_id = {
  "CCL: Behind the Trash Can Feather Nest 1": 1,
  "CCL: Behind the Trash Can Feather Nest 2": 2,
  "CCL: Behind the Trash Can Feather Nest 3": 3,
  "CCL: Behind the Trash Can Feather Nest 4": 4,
  "CCL: Blue Skull Exit Note": 5,
  "CCL: By George Feather Nest 1": 6,
  "CCL: By George Feather Nest 2": 7,
  "CCL: By George Feather Nest 3": 8,
  "CCL: By George Feather Nest 4": 9,
  "CCL: Canary Mary Cheato Page": 10,
  "CCL: Canary Mary Jiggy": 11,
  "CCL: Canary Mary Mumbo Token": 12,
  "CCL: Central Cavern Jinjo": 13,
  "CCL: Central Cavern Top Path Egg Nest 1": 14,
  "CCL: Central Cavern Top Path Egg Nest 2": 15,
  "CCL: Central Cavern Under Cheese Wedge Exit Egg Nest 1": 16,
  "CCL: Central Cavern Under Cheese Wedge Exit Egg Nest 2": 17,
  "CCL: Central Cavern Warp Pad Tagged": 18,
  "CCL: Central Cavern on Steps Near Main Entrance Egg Nest": 19,
  "CCL: Central Note 1": 20,
  "CCL: Central Note 2": 21,
  "CCL: Central Note 3": 22,
  "CCL: Cheese Wedge Exit Note": 23,
  "CCL: Cheese Wedge Jiggy": 24,
  "CCL: Cheese Wedge Jinjo": 25,
  "CCL: Dippy Pool Feather Nest 1": 26,
  "CCL: Dippy Pool Feather Nest 2": 27,
  "CCL: Dippy Pool Feather Nest 3": 28,
  "CCL: Dippy Pool Feather Nest 4": 29,
  "CCL: Dippy Pool Note": 30,
  "CCL: Dirt Patch Bean 1": 31,
  "CCL: Dirt Patch Bean 2": 32,
  "CCL: Dirt Patch Egg Nest": 33,
  "CCL: Dirt Patch Feather Nest": 34,
  "CCL: Dirt Patch Honeycomb": 35,
  "CCL: Glowbo Pool Note": 36,
  "CCL: High Jump Event Feather Nest": 37,
  "CCL: Indoors Pool Glowbo": 38,
  "CCL: Indoors Pool Underwater Signpost": 39,
  "CCL: Inside Cheese Wedge Egg Nest 1": 40,
  "CCL: Inside Cheese Wedge Egg Nest 2": 41,
  "CCL: Jelly Castle Egg Nest 1": 42,
  "CCL: Jelly Castle Egg Nest 2": 43,
  "CCL: Jelly Castle Egg Nest 3": 44,
  "CCL: Jelly Castle Egg Nest 4": 45,
  "CCL: Jelly Castle Jiggy": 46,
  "CCL: Jiggium Plant Jiggy": 47,
  "CCL: Main Entrance Note": 48,
  "CCL: Mingy Jongo Jiggy": 49,
  "CCL: Mingy Jongo Mumbo Token": 50,
  "CCL: Mingy Jongo Skull Jinjo": 51,
  "CCL: Mr Fit Jiggy": 52,
  "CCL: Mr. Fit Footrace Track Note": 53,
  "CCL: Mr. Fit High Jump Event": 54,
  "CCL: Mr. Fit Sack Race Event": 55,
  "CCL: Mr. Fit Sack Race Exit Note": 56,
  "CCL: Near Blue Skull Feather Nest 1": 57,
  "CCL: Near Blue Skull Feather Nest 2": 58,
  "CCL: Near Blue Skull Feather Nest 3": 59,
  "CCL: Near Blue Skull Feather Nest 4": 60,
  "CCL: Near Red Skull Feather Nest 1": 61,
  "CCL: Near Red Skull Feather Nest 2": 62,
  "CCL: Near Red Skull Feather Nest 3": 63,
  "CCL: Near Red Skull Feather Nest 4": 64,
  "CCL: Near Top Superstash Switch Feather Nest 1": 65,
  "CCL: Near Top Superstash Switch Feather Nest 2": 66,
  "CCL: On Rim of Glowbo Pool Signpost": 67,
  "CCL: Outdoors Pool Glowbo": 68,
  "CCL: Outside Cheese Wedge Feather Nest 1": 69,
  "CCL: Outside Cheese Wedge Feather Nest 2": 70,
  "CCL: Outside Cheese Wedge Feather Nest 3": 71,
  "CCL: Outside Cheese Wedge Feather Nest 4": 72,
  "CCL: Pot O' Gold Cheato Page": 73,
  "CCL: Pot O' Gold Honeycomb": 74,
  "CCL: Pot O' Gold Jiggy": 75,
  "CCL: Pot O' Gold Mumbo Token": 76,
  "CCL: Pot o' Gold Egg Nest 1": 77,
  "CCL: Pot o' Gold Egg Nest 2": 78,
  "CCL: Pot o' Gold Exit Note": 79,
  "CCL: Red Skull Exit Note": 80,
  "CCL: Sack Pack Silo": 81,
  "CCL: Sack Pack Silo Note 1": 82,
  "CCL: Sack Pack Silo Note 2": 83,
  "CCL: Sack Pack Silo Signpost": 84,
  "CCL: Superstash Jiggy": 85,
  "CCL: Top Entrance Feather Nest 1": 86,
  "CCL: Top Entrance Feather Nest 2": 87,
  "CCL: Top Entrance Note": 88,
  "CCL: Top Superstash Switch Note": 89,
  "CCL: Top-Left of Superstash Egg Nest 1": 90,
  "CCL: Top-Left of Superstash Egg Nest 2": 91,
  "CCL: Trash Can Egg Nest 1": 92,
  "CCL: Trash Can Egg Nest 2": 93,
  "CCL: Trash Can Honeycomb": 94,
  "CCL: Trash Can Jiggy": 95,
  "CCL: Trash Can Jinjo": 96,
  "CCL: Trash Can Mumbo Token": 97,
  "CCL: Treble Clef": 98,
  "CCL: World Entry and Exit Warp Pad Tagged": 99,
  "CCL: Wumba Jinjo": 100,
  "CCL: Wumba's Wigwam Egg Nest 1": 101,
  "CCL: Wumba's Wigwam Egg Nest 2": 102,
  "CCL: Wumba's Wigwam Signpost": 103,
  "CCL: Zubbas Cheato Page": 104,
  "CCL: Zubbas Jiggy": 105,
  "CCL: Zubbas Mumbo Token": 106,
  "CK: Bottom of the Tower Warp Pad Tagged": 107,
  "CK: Defeated HAG-1": 108,
  "CK: Top of the Tower Warp Pad Tagged": 109,
  "CK: Tower Of Tragedy Mumbo Token": 110,
  "Completion Condition": 0,
  "Debug:": 111,
  "GGM: Beak Bayonet Silo": 112,
  "GGM: Bill Drill Silo": 113,
  "GGM: Boulder Jinjo": 114,
  "GGM: Canary Cave Back-Left Egg Nest": 115,
  "GGM: Canary Cave Back-Right Feather Nest": 116,
  "GGM: Canary Cave Front-Left Feather Nest": 117,
  "GGM: Canary Cave Front-Right Egg Nest": 118,
  "GGM: Canary Mary Cheato Page": 119,
  "GGM: Canary Mary Jiggy": 120,
  "GGM: Chuffy": 121,
  "GGM: Crushing Shed Egg Nest 1": 122,
  "GGM: Crushing Shed Egg Nest 2": 123,
  "GGM: Crushing Shed Jiggy": 124,
  "GGM: Crushing Shed Jiggy Chunk 1": 125,
  "GGM: Crushing Shed Jiggy Chunk 2": 126,
  "GGM: Crushing Shed Jiggy Chunk 3": 127,
  "GGM: Defeated Chuffy": 128,
  "GGM: Dilberta Jiggy": 129,
  "GGM: Entrance Cheato Page": 130,
  "GGM: Flooded Caves Egg Nest 1": 131,
  "GGM: Flooded Caves Egg Nest 2": 132,
  "GGM: Flooded Caves Jiggy": 133,
  "GGM: Fuel Depot Back-Left Note": 134,
  "GGM: Fuel Depot Back-Right Note": 135,
  "GGM: Fuel Depot Egg Nest 1": 136,
  "GGM: Fuel Depot Egg Nest 2": 137,
  "GGM: Fuel Depot Egg Nest 3": 138,
  "GGM: Fuel Depot Feather Nest 1": 139,
  "GGM: Fuel Depot Feather Nest 2": 140,
  "GGM: Fuel Depot Feather Nest 3": 141,
  "GGM: Fuel Depot Front-Left Note": 142,
  "GGM: Fuel Depot Front-Right Note": 143,
  "GGM: Generator Cavern Egg Nest": 144,
  "GGM: Generator Cavern Jiggy": 145,
  "GGM: Generator Cavern Signpost": 146,
  "GGM: Gloomy Cavern Signpost": 147,
  "GGM: Gloomy Caverns Jail Cell Feather Nest": 148,
  "GGM: Gloomy Caverns Near Power Hut Egg Nest 1": 149,
  "GGM: Gloomy Caverns Near Power Hut Egg Nest 2": 150,
  "GGM: Gloomy Caverns Near Second Boulder Egg Nest": 151,
  "GGM: Hill by Crushing Shed Note 1": 152,
  "GGM: Hill by Crushing Shed Note 2": 153,
  "GGM: Hill by Crushing Shed Note 3": 154,
  "GGM: Hill by Crushing Shed Note 4": 155,
  "GGM: Inside Chuffy's Wagon Signpost": 156,
  "GGM: Inside Wumba's Wigwam Warp Pad Tagged": 157,
  "GGM: Jail Jinjo": 158,
  "GGM: Levitate Chuffy The Train": 159,
  "GGM: Mine Entrance 2 Glowbo": 160,
  "GGM: Mine Tracks Jinjo": 161,
  "GGM: Mumbo's Skull Feather Nest 1": 162,
  "GGM: Mumbo's Skull Feather Nest 2": 163,
  "GGM: Mumbo's Skull Feather Nest 3": 164,
  "GGM: Near Bill Drill Silo Egg Nest 1": 165,
  "GGM: Near Bill Drill Silo Egg Nest 2": 166,
  "GGM: Near Entrance Glowbo": 167,
  "GGM: Near Prospector's Hut Bottom-Left Note": 168,
  "GGM: Near Prospector's Hut Bottom-Right Note": 169,
  "GGM: Near Prospector's Hut Middle-Right Note": 170,
  "GGM: Near Prospector's Hut Top-Left Note": 171,
  "GGM: Near Prospector's Hut Top-Right Note": 172,
  "GGM: Near the Train Station Warp Pad Tagged": 173,
  "GGM: Old King Coal Jiggy": 174,
  "GGM: Old King Coal Mumbo Token": 175,
  "GGM: Ordnance Storage Jiggy": 176,
  "GGM: Ordnance Storage Lobby Egg Nest 1": 177,
  "GGM: Ordnance Storage Lobby Egg Nest 2": 178,
  "GGM: Ordnance Storage Lobby Egg Nest 3": 179,
  "GGM: Ordnance Storage Mumbo Token": 180,
  "GGM: Outside Mumbo's Skull Bottom-Right Note": 181,
  "GGM: Outside Mumbo's Skull Left Note": 182,
  "GGM: Outside Mumbo's Skull Top-Right Note": 183,
  "GGM: Outside Mumbo's Skull Warp Pad Tagged": 184,
  "GGM: Outside Ordnance Storage Egg Nest 1": 185,
  "GGM: Outside Ordnance Storage Egg Nest 2": 186,
  "GGM: Outside the Crushing Shed Warp Pad Tagged": 187,
  "GGM: Power Hut Basement Jiggy": 188,
  "GGM: Power Hut Feather Nest": 189,
  "GGM: Prospector Boulder Honeycomb": 190,
  "GGM: Prospector's Hut Egg Nest": 191,
  "GGM: Toxic Gas Cave Egg Nest": 192,
  "GGM: Toxic Gas Cave Feather Nest": 193,
  "GGM: Toxic Gas Cave Honeycomb": 194,
  "GGM: Toxic Gas Cave Jinjo": 195,
  "GGM: Toxic Gas Cave Signpost": 196,
  "GGM: Train Station Egg Nest 1": 197,
  "GGM: Train Station Egg Nest 2": 198,
  "GGM: Train Station Feather Nest 1": 199,
  "GGM: Train Station Feather Nest 2": 200,
  "GGM: Train Station Honeycomb": 201,
  "GGM: Treble Clef": 202,
  "GGM: Water Storage Cheato Page": 203,
  "GGM: Water Storage Jinjo": 204,
  "GGM: Water Storage Jinjo Tank Egg Nest": 205,
  "GGM: Waterfall Cavern Jiggy": 206,
  "GGM: Waterfall Jiggy": 207,
  "GGM: World Entry and Exit Warp Pad Tagged": 208,
  "GI Elevator Shaft: Floor 2 Egg Nest": 209,
  "GI Elevator Shaft: Floor 3 Egg Nest": 210,
  "GI Elevator Shaft: Floor 4 Egg Nest": 211,
  "GI Elevator Shaft: Signpost 1": 212,
  "GI Elevator Shaft: Signpost 2": 213,
  "GI Floor 1: Air Conditioning Plant In Front of Fan Feather Nest 1": 214,
  "GI Floor 1: Air Conditioning Plant In Front of Fan Feather Nest 2": 215,
  "GI Floor 1: Air Conditioning Plant Near Repair Depot Egg Nest 1": 216,
  "GI Floor 1: Air Conditioning Plant Near Repair Depot Egg Nest 2": 217,
  "GI Floor 1: Air Conditioning Plant Near Waste Disposal Egg Nest": 218,
  "GI Floor 1: Air Conditioning Plant Note 1": 219,
  "GI Floor 1: Air Conditioning Plant Note 2": 220,
  "GI Floor 1: Broke Loggo's Door": 221,
  "GI Floor 1: Claw Clamber Boots Silo": 222,
  "GI Floor 1: Cleaned Skivvy": 223,
  "GI Floor 1: Defeated Tintops": 224,
  "GI Floor 1: Entrance Door Warp Pad Tagged": 225,
  "GI Floor 1: Floor 1 on A/C Unit Note 1": 226,
  "GI Floor 1: Floor 1 on A/C Unit Note 2": 227,
  "GI Floor 1: Guarded Jiggy": 228,
  "GI Floor 1: High Pipe Egg Nest 1": 229,
  "GI Floor 1: High Pipe Egg Nest 2": 230,
  "GI Floor 1: Loggo Cheato Page": 231,
  "GI Floor 1: Near Waste Disposal Feather Nest 1": 232,
  "GI Floor 1: Near Waste Disposal Feather Nest 2": 233,
  "GI Floor 1: Opened Back Door": 234,
  "GI Floor 1: Opened Main Door": 235,
  "GI Floor 1: Opened Trash Compactor Jiggy Door": 236,
  "GI Floor 1: Opened Waste Disposal Plant": 237,
  "GI Floor 1: Repair Depot Cheato Page": 238,
  "GI Floor 1: Repair Depot Egg Nest 1": 239,
  "GI Floor 1: Repair Depot Egg Nest 2": 240,
  "GI Floor 1: Skivvy": 241,
  "GI Floor 1: Snooze Pack Silo": 242,
  "GI Floor 1: Top Pipe Egg Nest": 243,
  "GI Floor 1: Top of Trash Compactor Feather Nest": 244,
  "GI Floor 1: Train Station Big Box Egg Nest": 245,
  "GI Floor 1: Train Station Honeycomb": 246,
  "GI Floor 1: Train Station Medium Box Egg Nest": 247,
  "GI Floor 1: Train Station Note 1": 248,
  "GI Floor 1: Train Station Note 2": 249,
  "GI Floor 1: Train Station Note 3": 250,
  "GI Floor 1: Train Station Small Box Egg Nest": 251,
  "GI Floor 1: Trash Compactor Egg Nest 1": 252,
  "GI Floor 1: Trash Compactor Egg Nest 2": 253,
  "GI Floor 1: Trash Compactor Jiggy": 254,
  "GI Floor 1: Underwater Waste Disposal Plant Jiggy": 255,
  "GI Floor 1: Waste Disposal Jinjo Tank Egg Nest 1": 256,
  "GI Floor 1: Waste Disposal Jinjo Tank Egg Nest 2": 257,
  "GI Floor 1: Waste Disposal Plant Box Jiggy": 258,
  "GI Floor 1: Waste Disposal Plant Jinjo": 259,
  "GI Floor 1: Waste Disposal Plant Note 1": 260,
  "GI Floor 1: Waste Disposal Plant Note 2": 261,
  "GI Floor 1: Waste Disposal Water Pump Egg Nest": 262,
  "GI Floor 1: Waste Disposal Water Pump Feather Nest": 263,
  "GI Floor 1: Weldar Jiggy": 264,
  "GI Floor 1: Weldar Mumbo Token": 265,
  "GI Floor 1: Workers Quarters Signpost": 266,
  "GI Floor 1: Workers' Quarters Egg Nest": 267,
  "GI Floor 1: Workers' Quarters Feather Nest": 268,
  "GI Floor 2: Box Room Shorter Stack Note": 269,
  "GI Floor 2: Box Room Taller Stack Note": 270,
  "GI Floor 2: Broke Grate Near Electromagnet Chamber": 271,
  "GI Floor 2: Broke Grate Near Humba": 272,
  "GI Floor 2: Cleaned Skivvy": 273,
  "GI Floor 2: Delivered Battery Near Floor 3 Exit": 274,
  "GI Floor 2: Delivered Toxic Room Battery": 275,
  "GI Floor 2: EMP Electromagnet": 276,
  "GI Floor 2: Electromagnetic Chamber Egg Nest 1": 277,
  "GI Floor 2: Electromagnetic Chamber Egg Nest 2": 278,
  "GI Floor 2: Electromagnetic Chamber Feather Nest": 279,
  "GI Floor 2: Glowbo": 280,
  "GI Floor 2: In a Box Egg Nest 1": 281,
  "GI Floor 2: In a Box Egg Nest 2": 282,
  "GI Floor 2: Leg Spring Jinjo": 283,
  "GI Floor 2: Leg Spring Room Note 1": 284,
  "GI Floor 2: Leg Spring Room Note 2": 285,
  "GI Floor 2: Leg Spring Room Note 3": 286,
  "GI Floor 2: Leg Spring Silo": 287,
  "GI Floor 2: Near Cheato Page Feather Nest": 288,
  "GI Floor 2: Near Floor 1 Tunnel Egg Nest": 289,
  "GI Floor 2: Near Unscrewable Platform Feather Nest": 290,
  "GI Floor 2: On Scaffolding Egg Nest 1": 291,
  "GI Floor 2: On Scaffolding Egg Nest 2": 292,
  "GI Floor 2: On Scaffolding Egg Nest 3": 293,
  "GI Floor 2: On Scaffolding Egg Nest 4": 294,
  "GI Floor 2: On Scaffolding Egg Nest 5": 295,
  "GI Floor 2: Opened Catwalk Door": 296,
  "GI Floor 2: Opened Electromagnet Chamber": 297,
  "GI Floor 2: Opened Elevator Door": 298,
  "GI Floor 2: Opened Repair Depot": 299,
  "GI Floor 2: Outside Wumba's Wigwam Warp Pad Tagged": 300,
  "GI Floor 2: Skivvy": 301,
  "GI Floor 2: Unscrewed Plate": 302,
  "GI Floor 2: Window Cheato Page": 303,
  "GI Floor 3: Boiler Plant Jinjo": 304,
  "GI Floor 3: Boiler Plant Left Egg Nest": 305,
  "GI Floor 3: Boiler Plant Right Egg Nest": 306,
  "GI Floor 3: Cleaned Skivvy": 307,
  "GI Floor 3: Cleared Twinkly Packing": 308,
  "GI Floor 3: Delivered Battery": 309,
  "GI Floor 3: Glowbo": 310,
  "GI Floor 3: Honeycomb": 311,
  "GI Floor 3: Near Mumbo's Skull Egg Nest": 312,
  "GI Floor 3: Note 1": 313,
  "GI Floor 3: Note 2": 314,
  "GI Floor 3: On Boxes Feather Nest 1": 315,
  "GI Floor 3: On Boxes Feather Nest 2": 316,
  "GI Floor 3: On Crate Egg Nest": 317,
  "GI Floor 3: On High Box Stack Egg Nest": 318,
  "GI Floor 3: Opened Elevator Door": 319,
  "GI Floor 3: Opened Twinkly Packing Door": 320,
  "GI Floor 3: Outside Mumbo's Skull Warp Pad Tagged": 321,
  "GI Floor 3: Skivvy": 322,
  "GI Floor 3: Twinkly Packing Jiggy": 323,
  "GI Floor 3: Twinkly Packing Mumbo Token": 324,
  "GI Floor 3: Under Notes Egg Nest": 325,
  "GI Floor 3: Unscrewed Plate": 326,
  "GI Floor 4: Activated Flight Pads": 327,
  "GI Floor 4: Box Near Crushers Egg Nest": 328,
  "GI Floor 4: Cable Room": 329,
  "GI Floor 4: Cleared Clinker's Cavern": 330,
  "GI Floor 4: Clinker's Cavern Green Room Egg Nest 1": 331,
  "GI Floor 4: Clinker's Cavern Green Room Egg Nest 2": 332,
  "GI Floor 4: Clinker's Cavern Jiggy": 333,
  "GI Floor 4: Clinker's Cavern Mumbo Token": 334,
  "GI Floor 4: Clinker's Cavern Near Window Egg Nest": 335,
  "GI Floor 4: Clinker's Cavern Orange Room Egg Nest": 336,
  "GI Floor 4: Clinker's Cavern Raising Scaffolding Room Bottom Egg Nest": 337,
  "GI Floor 4: Clinker's Cavern Raising Scaffolding Room Top Egg Nest": 338,
  "GI Floor 4: Clinker's Cavern Spiral Scaffolding Room Egg Nest": 339,
  "GI Floor 4: Clinker's Cavern Valve Room Egg Nest": 340,
  "GI Floor 4: Disabled Crushers": 341,
  "GI Floor 4: EMP Wall Crushers": 342,
  "GI Floor 4: Near Battery Door Egg Nest": 343,
  "GI Floor 4: Near Fire Exit Egg Nest 1": 344,
  "GI Floor 4: Near Fire Exit Egg Nest 2": 345,
  "GI Floor 4: Near Fire Exit Egg Nest 3": 346,
  "GI Floor 4: Near Service Elevator Feather Nest 1": 347,
  "GI Floor 4: Near Service Elevator Feather Nest 2": 348,
  "GI Floor 4: Near the Crushers Warp Pad Tagged": 349,
  "GI Floor 4: Opened Cable Room Door": 350,
  "GI Floor 4: Opened Elevator Door": 351,
  "GI Floor 4: Pressed Quality Control Vent Button": 352,
  "GI Floor 4: Quality Control Egg Nest 1": 353,
  "GI Floor 4: Quality Control Egg Nest 2": 354,
  "GI Floor 4: Quality Control Egg Nest 3": 355,
  "GI Floor 4: Quality Control Jiggy": 356,
  "GI Floor 4: Quality Control Pit": 357,
  "GI Floor 4: Sewer Entrance Left Egg Nest 1": 358,
  "GI Floor 4: Sewer Entrance Left Egg Nest 2": 359,
  "GI Floor 4: Sewer Entrance Right Egg Nest 1": 360,
  "GI Floor 4: Sewer Entrance Right Egg Nest 2": 361,
  "GI Floor 4: Spawned Quality Control Jiggy": 362,
  "GI Floor 5: Big Box Stack Egg Nest": 363,
  "GI Floor 5: Box Egg Nest": 364,
  "GI Floor 5: Cleaned Skivvy": 365,
  "GI Floor 5: Jiggy": 366,
  "GI Floor 5: Jinjo": 367,
  "GI Floor 5: Skivvy": 368,
  "GI Floor 5: Small Box Stack Egg Nest": 369,
  "GI Floor 5: Unscrewed Plate": 370,
  "GI Outside: Atop Back Train Tunnel Feather Nest": 371,
  "GI Outside: Atop Front Train Tunnel Feather Nest": 372,
  "GI Outside: Broke Chimney": 373,
  "GI Outside: Broke Floor 1 Window": 374,
  "GI Outside: Broke Upper Middle Window": 375,
  "GI Outside: Broke Upper Side Window": 376,
  "GI Outside: Broke Window Above Front Train Tunnel": 377,
  "GI Outside: Broke Window Near Back Train Tunnel": 378,
  "GI Outside: Chimney Honeycomb": 379,
  "GI Outside: Cleaned Skivvy": 380,
  "GI Outside: Delivered Battery": 381,
  "GI Outside: Jinjo": 382,
  "GI Outside: On the Roof Outside Warp Pad Tagged": 383,
  "GI Outside: Roof Feather Nest 1": 384,
  "GI Outside: Roof Feather Nest 2": 385,
  "GI Outside: Roof Feather Nest 3": 386,
  "GI Outside: Signpost": 387,
  "GI Outside: Skivvy": 388,
  "GI Outside: Train Switch": 389,
  "GI Outside: Treble Clef": 390,
  "GI Worker's Quarters: Cleaned Skivvy": 391,
  "GI Worker's Quarters: Skivvy": 392,
  "GI: Defeated Weldar": 393,
  "GI: Mumbo Transform": 394,
  "GI: Skivvy Workers Jiggy": 395,
  "GI: Washer Transform": 396,
  "HFP: Aliens Jiggy": 397,
  "HFP: Alphette (Alien Kid Near Glowbo)": 398,
  "HFP: Betette (Alien Kid Near Dad)": 399,
  "HFP: Boggy Jiggy": 400,
  "HFP: Boggy's Igloo Note 1": 401,
  "HFP: Boggy's Igloo Note 2": 402,
  "HFP: Boiling Hot Pool Jinjo": 403,
  "HFP: Bottom Hot Pool Signpost": 404,
  "HFP: By Flight Pad Feather Nest 1": 405,
  "HFP: By Flight Pad Feather Nest 2": 406,
  "HFP: By Flight Pad Feather Nest 3": 407,
  "HFP: By Flight Pad Feather Nest 4": 408,
  "HFP: By Lava Side Train Switch Egg Nest": 409,
  "HFP: By Sabreman Egg Nest 1": 410,
  "HFP: By Sabreman Egg Nest 2": 411,
  "HFP: Chilli Billi Crater Egg Nest": 412,
  "HFP: Chilli Billi Mumbo Token": 413,
  "HFP: Chilly Willy Crater Egg Nest": 414,
  "HFP: Chilly Willy Mumbo Token": 415,
  "HFP: Colosseum Cheato Page": 416,
  "HFP: Colosseum Split-Up Jiggy": 417,
  "HFP: Dragon Brothers Jiggy": 418,
  "HFP: Fire Side - Lower Area (Mumbo) Warp Pad Tagged": 419,
  "HFP: Fire Side - Upper Area Warp Pad Tagged": 420,
  "HFP: Gamette (Alien Kid Above Split-Up Pads)": 421,
  "HFP: Glide Silo": 422,
  "HFP: Ice Side - Inside Icicle Grotto Warp Pad Tagged": 423,
  "HFP: Ice Side - Lower Area (Wumba) Warp Pad Tagged": 424,
  "HFP: Ice Side - Upper Area Warp Pad Tagged": 425,
  "HFP: Icicle Grotto Bottom Egg Nest 1": 426,
  "HFP: Icicle Grotto Bottom Egg Nest 2": 427,
  "HFP: Icicle Grotto Bottom Egg Nest 3": 428,
  "HFP: Icicle Grotto Cheato Page": 429,
  "HFP: Icicle Grotto Jinjo": 430,
  "HFP: Icicle Grotto Shock Spring Pad Egg Nest": 431,
  "HFP: Icicle Grotto Top Egg Nest 1": 432,
  "HFP: Icicle Grotto Top Egg Nest 2": 433,
  "HFP: Icy Side Glowbo": 434,
  "HFP: Icy Side Lower Warp Pad Egg Nest": 435,
  "HFP: Icy Side Pillar Cheato Page": 436,
  "HFP: Icy Side Station Jiggy": 437,
  "HFP: Icy Side Train Station Egg Nest": 438,
  "HFP: Icy Side Train Station Feather Nest": 439,
  "HFP: Icy Side Train Switch": 440,
  "HFP: Inside the Volcano Honeycomb": 441,
  "HFP: Inside the Volcano Jiggy": 442,
  "HFP: Kickball Colosseum Egg Nest 1": 443,
  "HFP: Kickball Colosseum Egg Nest 2": 444,
  "HFP: Kickball Colosseum Egg Nest 3": 445,
  "HFP: Kickball Colosseum Egg Nest 4": 446,
  "HFP: Kickball Colosseum Feather Nest 1": 447,
  "HFP: Kickball Colosseum Feather Nest 2": 448,
  "HFP: Kickball Jiggy": 449,
  "HFP: Kickball Mumbo Token": 450,
  "HFP: Lava Side Glowbo": 451,
  "HFP: Lava Side Honeycomb": 452,
  "HFP: Lava Side Lower Warp Pad Egg Nest 1": 453,
  "HFP: Lava Side Lower Warp Pad Egg Nest 2": 454,
  "HFP: Lava Side Train Station Egg Nest 1": 455,
  "HFP: Lava Side Train Station Egg Nest 2": 456,
  "HFP: Lava Side Train Switch": 457,
  "HFP: Lava Side: Near Ladder Note 1": 458,
  "HFP: Lava Side: Near Ladder Note 2": 459,
  "HFP: Lava Side: Top Path Note 1": 460,
  "HFP: Lava Side: Top Path Note 2": 461,
  "HFP: Lava Waterfall Jinjo": 462,
  "HFP: Lower Icy Side Warp Pad Note 1": 463,
  "HFP: Lower Icy Side Warp Pad Note 2": 464,
  "HFP: Mega Glowbo": 465,
  "HFP: Mildred Ice Cube Jinjo": 466,
  "HFP: Mumbo's Skull Feather Nest 1": 467,
  "HFP: Mumbo's Skull Feather Nest 2": 468,
  "HFP: Near Bottom Icicle Grotto Entrance Feather Nest 1": 469,
  "HFP: Near Bottom Icicle Grotto Entrance Feather Nest 2": 470,
  "HFP: Near Icy Side Pillar Egg Nest 1": 471,
  "HFP: Near Icy Side Pillar Egg Nest 2": 472,
  "HFP: Near Top Hot Pool Egg Nest 1": 473,
  "HFP: Near Top Hot Pool Egg Nest 2": 474,
  "HFP: Oil Drill Jiggy": 475,
  "HFP: Oil Drill Note 1": 476,
  "HFP: Oil Drill Note 2": 477,
  "HFP: On Shelter Near Entrance Feather Nest": 478,
  "HFP: Path to Mumbo's Skull Note 1": 479,
  "HFP: Path to Mumbo's Skull Note 2": 480,
  "HFP: Path to Shack Pack Note 1": 481,
  "HFP: Path to Shack Pack Note 2": 482,
  "HFP: Sabreman Jiggy": 483,
  "HFP: Sabreman Tent Egg Nest": 484,
  "HFP: Shack Pack Silo": 485,
  "HFP: Stomping Plains Jiggy": 486,
  "HFP: Top Hot Pool Signpost": 487,
  "HFP: Train Station Honeycomb": 488,
  "HFP: Treble Clef": 489,
  "HFP: Upper Icy Side Warp Pad Note 1": 490,
  "HFP: Upper Icy Side Warp Pad Note 2": 491,
  "HFP: Volcano Signpost 1": 492,
  "HFP: Volcano Signpost 2": 493,
  "HFP: Volcano Signpost 3": 494,
  "HFP: Windy Hole Jinjo": 495,
  "HFP: Wumba's Wigwam Feather Nest 1": 496,
  "HFP: Wumba's Wigwam Feather Nest 2": 497,
  "IoH Dragon Transform": 498,
  "IoH: Amaze-O-Gaze Goggles": 499,
  "IoH: Another Digger Tunnel Egg Nest 1": 500,
  "IoH: Another Digger Tunnel Egg Nest 2": 501,
  "IoH: Behind Jiggywiggy's Temple Signpost 1": 502,
  "IoH: Behind Jiggywiggy's Temple Signpost 2": 503,
  "IoH: Behind Jiggywiggy's Temple Signpost 3": 504,
  "IoH: Black Jinjo Family Jiggy": 505,
  "IoH: Black Jinjo Family Mumbo Token": 506,
  "IoH: Blue Jinjo Family Jiggy": 507,
  "IoH: Blue Jinjo Family Mumbo Token": 508,
  "IoH: Blue Mystery Egg Hatched": 509,
  "IoH: Bottles' House Egg Nest 1": 510,
  "IoH: Bottles' House Egg Nest 2": 511,
  "IoH: Bottles' House Feather Nest 1": 512,
  "IoH: Bottles' House Feather Nest 2": 513,
  "IoH: Bottles' House: Gate Opened": 514,
  "IoH: Brown Jinjo Family Jiggy": 515,
  "IoH: Brown Jinjo Family Mumbo Token": 516,
  "IoH: Cliff Top Bridge Switch Pressed": 517,
  "IoH: Cliff Top Feather Nest 1": 518,
  "IoH: Cliff Top Feather Nest 2": 519,
  "IoH: Cliff Top Feather Nest 3": 520,
  "IoH: Cliff Top Feather Nest 4": 521,
  "IoH: Cliff Top Glowbo": 522,
  "IoH: Cliff Top Jinjo": 523,
  "IoH: Cliff Top Near JRL Egg Nest": 524,
  "IoH: Cliff Top Near Path to Plateau Egg Nest 1": 525,
  "IoH: Cliff Top Near Path to Plateau Egg Nest 2": 526,
  "IoH: Cliff Top Signpost": 527,
  "IoH: Cliff Top Silo Tagged": 528,
  "IoH: Clockwork Kazooie Eggs Silo": 529,
  "IoH: Clockwork Silo Bottom Note": 530,
  "IoH: Clockwork Silo Top Note": 531,
  "IoH: Fire Eggs Silo": 532,
  "IoH: Green Jinjo Family Jiggy": 533,
  "IoH: Green Jinjo Family Mumbo Token": 534,
  "IoH: Grenade Eggs Silo": 535,
  "IoH: Grey Jinjo Family House Signpost": 536,
  "IoH: Honey B's Reward 1": 537,
  "IoH: Honey B's Reward 2": 538,
  "IoH: Honey B's Reward 3": 539,
  "IoH: Honey B's Reward 4": 540,
  "IoH: Honey B's Reward 5": 541,
  "IoH: Ice Eggs Silo": 542,
  "IoH: Ice Key": 543,
  "IoH: Inside the Digger Tunnel Egg Nest": 544,
  "IoH: Jiggywiggy's Temple Signpost 1": 545,
  "IoH: Jiggywiggy's Temple Signpost 2": 546,
  "IoH: Jiggywiggy's Temple Signpost 3": 547,
  "IoH: Jiggywiggy's Temple Signpost 4": 548,
  "IoH: Jiggywiggy's Temple Signpost 5": 549,
  "IoH: Jiggywiggy's Temple Signpost 6": 550,
  "IoH: Jiggywiggy's Temple Signpost 7": 551,
  "IoH: Jiggywiggy's Temple Signpost 8": 552,
  "IoH: Jinjo Village By Silo Egg Nest 1": 553,
  "IoH: Jinjo Village By Silo Egg Nest 2": 554,
  "IoH: Jinjo Village By Silo Feather Nest 1": 555,
  "IoH: Jinjo Village By Silo Feather Nest 2": 556,
  "IoH: Jinjo Village Near Shortcut Egg Nest 1": 557,
  "IoH: Jinjo Village Near Shortcut Egg Nest 2": 558,
  "IoH: Jinjo Village Outside Bottle's House Feather Nest 1": 559,
  "IoH: Jinjo Village Outside Bottle's House Feather Nest 2": 560,
  "IoH: Jinjo Village Silo Tagged": 561,
  "IoH: Jinjo Village Top Row of Houses Egg Nest 1": 562,
  "IoH: Jinjo Village Top Row of Houses Egg Nest 2": 563,
  "IoH: Jinjo Village Top Row of Houses Feather Nest 1": 564,
  "IoH: Jinjo Village Top Row of Houses Feather Nest 2": 565,
  "IoH: King Jingaling Jiggy": 566,
  "IoH: Orange Jinjo Family Jiggy": 567,
  "IoH: Orange Jinjo Family Mumbo Token": 568,
  "IoH: Outside HFP Note 1": 569,
  "IoH: Outside HFP Note 2": 570,
  "IoH: Outside HFP Note 3": 571,
  "IoH: Outside HFP Note 4": 572,
  "IoH: Outside Heggy's Egg Shed Signpost": 573,
  "IoH: Party At Bottles'": 574,
  "IoH: Pine Grove Egg Nest 1": 575,
  "IoH: Pine Grove Egg Nest 2": 576,
  "IoH: Pine Grove Egg Nest 3": 577,
  "IoH: Pine Grove Feather Nest 1": 578,
  "IoH: Pine Grove Feather Nest 2": 579,
  "IoH: Pine Grove Feather Nest 3": 580,
  "IoH: Pine Grove Note 1": 581,
  "IoH: Pine Grove Note 2": 582,
  "IoH: Pine Grove Signpost 1": 583,
  "IoH: Pine Grove Signpost 2": 584,
  "IoH: Pine Grove Signpost 3": 585,
  "IoH: Pine Grove Silo Tagged": 586,
  "IoH: Pine Grove Underwater Note 1": 587,
  "IoH: Pine Grove Underwater Note 2": 588,
  "IoH: Pink Mystery Egg Hatched": 589,
  "IoH: Plateau Dirt Pile Feather Nest 1": 590,
  "IoH: Plateau Dirt Pile Feather Nest 2": 591,
  "IoH: Plateau GGM Sign Note 1": 592,
  "IoH: Plateau GGM Sign Note 2": 593,
  "IoH: Plateau Honey B. Note 1": 594,
  "IoH: Plateau Honey B. Note 2": 595,
  "IoH: Plateau Honeycomb": 596,
  "IoH: Plateau Jinjo": 597,
  "IoH: Plateau Near Cliff Top Entrance Feather Nest": 598,
  "IoH: Plateau Near GGM Entrance Egg Nest 1": 599,
  "IoH: Plateau Near GGM Entrance Egg Nest 2": 600,
  "IoH: Plateau Near GGM Entrance Egg Nest 3": 601,
  "IoH: Plateau Near GGM Entrance Egg Nest 4": 602,
  "IoH: Plateau Silo Tagged": 603,
  "IoH: Plateau: Fire Switch": 604,
  "IoH: Plateau: Path to Cliff Top Opened": 605,
  "IoH: Purple Jinjo Family Jiggy": 606,
  "IoH: Purple Jinjo Family Mumbo Token": 607,
  "IoH: Quagmire Back Feather Nest": 608,
  "IoH: Quagmire Egg Nest 1": 609,
  "IoH: Quagmire Egg Nest 2": 610,
  "IoH: Quagmire Egg Nest 3": 611,
  "IoH: Quagmire High Feather Nest": 612,
  "IoH: Quagmire Left Feather Nest": 613,
  "IoH: Quagmire Silo Tagged": 614,
  "IoH: Quagmire Spring Pad Switch Pressed": 615,
  "IoH: Red Jinjo Family Jiggy": 616,
  "IoH: Red Jinjo Family Mumbo Token": 617,
  "IoH: Train Switch": 618,
  "IoH: Treble Clef": 619,
  "IoH: Wasteland Behind CCL Bubble Feather Nest": 620,
  "IoH: Wasteland CCL Area Note 1": 621,
  "IoH: Wasteland CCL Area Note 2": 622,
  "IoH: Wasteland Jinjo": 623,
  "IoH: Wasteland Near Crevice to CCL Feather Nest": 624,
  "IoH: Wasteland Near Digger Tunnel Egg Nest 1": 625,
  "IoH: Wasteland Near Digger Tunnel Egg Nest 2": 626,
  "IoH: Wasteland Near Digger Tunnel Egg Nest 3": 627,
  "IoH: Wasteland Next to Quagmire Entrance Feather Nest": 628,
  "IoH: Wasteland Signpost": 629,
  "IoH: Wasteland Silo Tagged": 630,
  "IoH: Wasteland TDL Entrance Feather Nest 1": 631,
  "IoH: Wasteland TDL Entrance Feather Nest 2": 632,
  "IoH: White Jinjo Family Jiggy": 633,
  "IoH: White Jinjo Family Mumbo Token": 634,
  "IoH: Wooded Hollow Jiggywiggy Challenge 1": 635,
  "IoH: Wooded Hollow Jiggywiggy Challenge 10": 636,
  "IoH: Wooded Hollow Jiggywiggy Challenge 2": 637,
  "IoH: Wooded Hollow Jiggywiggy Challenge 3": 638,
  "IoH: Wooded Hollow Jiggywiggy Challenge 4": 639,
  "IoH: Wooded Hollow Jiggywiggy Challenge 5": 640,
  "IoH: Wooded Hollow Jiggywiggy Challenge 6": 641,
  "IoH: Wooded Hollow Jiggywiggy Challenge 7": 642,
  "IoH: Wooded Hollow Jiggywiggy Challenge 8": 643,
  "IoH: Wooded Hollow Jiggywiggy Challenge 9": 644,
  "IoH: Wooded Hollow Jiggywiggy's Super Special Challenge": 645,
  "IoH: Wooded Hollow Jinjo": 646,
  "IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 1": 647,
  "IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 2": 648,
  "IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 3": 649,
  "IoH: Wooded Hollow Outside Bottles' House Feather Nest 1": 650,
  "IoH: Wooded Hollow Outside Bottles' House Feather Nest 2": 651,
  "IoH: Wooded Hollow Outside Heggy's Egg Shed Egg Nest 1": 652,
  "IoH: Wooded Hollow Outside Heggy's Egg Shed Egg Nest 2": 653,
  "IoH: Wooded Hollow Path to Plateau Signpost": 654,
  "IoH: Wooded Hollow Right of Jiggywiggy's Temple Egg Nest 1": 655,
  "IoH: Wooded Hollow Right of Jiggywiggy's Temple Egg Nest 2": 656,
  "IoH: Wooded Hollow Silo Tagged": 657,
  "IoH: Wumba's Wigwam Egg Nest 1": 658,
  "IoH: Wumba's Wigwam Egg Nest 2": 659,
  "IoH: Yellow Jinjo Family Jiggy": 660,
  "IoH: Yellow Jinjo Family Mumbo Token": 661,
  "IoH: Yellow Mystery Egg Hatched": 662,
  "JRL: Alcove Doubloon 1": 663,
  "JRL: Alcove Doubloon 2": 664,
  "JRL: Alcove Doubloon 3": 665,
  "JRL: Ancient Swimming Baths Cheato Page": 666,
  "JRL: Atlantis Egg Nest 1": 667,
  "JRL: Atlantis Egg Nest 2": 668,
  "JRL: Atlantis Egg Nest 3": 669,
  "JRL: Atlantis Honeycomb": 670,
  "JRL: Atlantis Seemee Fish Egg Nest": 671,
  "JRL: Atlantis Warp Pad Tagged": 672,
  "JRL: Big Fish Cavern Warp Pad Tagged": 673,
  "JRL: Big Fish Jinjo": 674,
  "JRL: Blubber Jinjo": 675,
  "JRL: Blubber's Hire Note 1": 676,
  "JRL: Blubber's Hire Note 2": 677,
  "JRL: Blubber's Hire Note 3": 678,
  "JRL: Blubber's Signpost": 679,
  "JRL: Blubbul Note 1": 680,
  "JRL: Blubbul Note 2": 681,
  "JRL: Captain Blackeye Doubloon 1": 682,
  "JRL: Captain Blackeye Doubloon 2": 683,
  "JRL: Chris P. Bacon Jiggy": 684,
  "JRL: Davie Jones Locker Egg Nest 1": 685,
  "JRL: Davie Jones Locker Egg Nest 2": 686,
  "JRL: Davie Jones Locker Egg Nest 3": 687,
  "JRL: Davie Jones Locker Egg Nest 4": 688,
  "JRL: Electric Eel's Lair Entrance Note 1": 689,
  "JRL: Electric Eel's Lair Entrance Note 2": 690,
  "JRL: Inside the Big Fish Feather Nest 1": 691,
  "JRL: Inside the Big Fish Feather Nest 2": 692,
  "JRL: Jolly's Gunpowder Feather Nest 1": 693,
  "JRL: Jolly's Gunpowder Feather Nest 2": 694,
  "JRL: Jolly's Near Blackeye Egg Nest 1": 695,
  "JRL: Jolly's Near Blackeye Egg Nest 2": 696,
  "JRL: Jolly's Near Sub-Aqua Egg Aiming Silo Feather Nest 1": 697,
  "JRL: Jolly's Near Sub-Aqua Egg Aiming Silo Feather Nest 2": 698,
  "JRL: Jolly's Note 1": 699,
  "JRL: Jolly's Note 2": 700,
  "JRL: Jolly's Note 3": 701,
  "JRL: Lagoon Alcove Jinjo": 702,
  "JRL: Lockers Cavern Warp Pad Tagged": 703,
  "JRL: Lockers Egg Nest 1": 704,
  "JRL: Lockers Egg Nest 2": 705,
  "JRL: Lockers Egg Nest 3": 706,
  "JRL: Merry Maggie Jiggy": 707,
  "JRL: Mini-Sub Challenge Jiggy": 708,
  "JRL: Mini-Sub Challenge Mumbo Token": 709,
  "JRL: Mumbo Skull Doubloon 1": 710,
  "JRL: Mumbo Skull Doubloon 2": 711,
  "JRL: Mumbo Skull Doubloon 3": 712,
  "JRL: Mumbo Skull Doubloon 4": 713,
  "JRL: Near Alcove Jinjo Doubloon 1": 714,
  "JRL: Near Alcove Jinjo Doubloon 2": 715,
  "JRL: Near Alcove Jinjo Doubloon 3": 716,
  "JRL: Near Alcove Jinjo Doubloon 4": 717,
  "JRL: Near Big Fish Warp Pad Egg Nest 1": 718,
  "JRL: Near Big Fish Warp Pad Egg Nest 2": 719,
  "JRL: Outside Blubber's Note": 720,
  "JRL: Outside Jolly's Note": 721,
  "JRL: Outside Pawno's Note": 722,
  "JRL: Pawno Cheato Page": 723,
  "JRL: Pawno Jiggy": 724,
  "JRL: Pawno's Emporium Egg Nest 1": 725,
  "JRL: Pawno's Emporium Egg Nest 2": 726,
  "JRL: Pawno's Emporium Egg Nest 3": 727,
  "JRL: Pawno's Emporium Glowbo": 728,
  "JRL: Pawno's Emporium Note 1": 729,
  "JRL: Pawno's Emporium Note 2": 730,
  "JRL: Pawno's Emporium Note 3": 731,
  "JRL: Pig Pool Jiggy": 732,
  "JRL: Sea Bottom Seemee Fish Egg Nest": 733,
  "JRL: Sea Bottom Seemee Fish Feather Nest": 734,
  "JRL: Seaweed Sanctum Bottom Floor Feather Nest": 735,
  "JRL: Seaweed Sanctum Jinjo": 736,
  "JRL: Seaweed Sanctum Second Floor Egg Nest 1": 737,
  "JRL: Seaweed Sanctum Second Floor Egg Nest 2": 738,
  "JRL: Seaweed Sanctum Signpost": 739,
  "JRL: Seaweed Sanctum Top Floor Feather Nest": 740,
  "JRL: Seemee Cheato Page": 741,
  "JRL: Seemee Honeycomb": 742,
  "JRL: Seemee Jiggy": 743,
  "JRL: Silo Doubloon 1": 744,
  "JRL: Silo Doubloon 2": 745,
  "JRL: Silo Doubloon 3": 746,
  "JRL: Silo Doubloon 4": 747,
  "JRL: Smuggler's Cavern Egg Nest 1": 748,
  "JRL: Smuggler's Cavern Egg Nest 2": 749,
  "JRL: Smuggler's Cavern Jiggy": 750,
  "JRL: Smuggler's Cavern Signpost": 751,
  "JRL: Sub-Aqua Egg Aiming Silo": 752,
  "JRL: Sunken Ship Egg Nest 1": 753,
  "JRL: Sunken Ship Egg Nest 2": 754,
  "JRL: Sunken Ship Jinjo": 755,
  "JRL: Sunken Ship Warp Pad Tagged": 756,
  "JRL: Talon Torpedo Silo": 757,
  "JRL: Temple of the Fishes Egg Nest 1": 758,
  "JRL: Temple of the Fishes Egg Nest 2": 759,
  "JRL: Temple of the Fishes Egg Nest 3": 760,
  "JRL: Temple of the Fishes Egg Nest 4": 761,
  "JRL: Tiptup Jiggy": 762,
  "JRL: Town Center Blubbul Egg Nest": 763,
  "JRL: Town Center Pole Doubloon 1": 764,
  "JRL: Town Center Pole Doubloon 2": 765,
  "JRL: Town Center Pole Doubloon 3": 766,
  "JRL: Town Center Pole Doubloon 4": 767,
  "JRL: Town Center Pole Doubloon 5": 768,
  "JRL: Town Center Pole Doubloon 6": 769,
  "JRL: Town Center Warp Pad Tagged": 770,
  "JRL: Toxic Pool Doubloon 1": 771,
  "JRL: Toxic Pool Doubloon 2": 772,
  "JRL: Toxic Pool Doubloon 3": 773,
  "JRL: Toxic Pool Doubloon 4": 774,
  "JRL: Treble Clef": 775,
  "JRL: UFO Jiggy": 776,
  "JRL: Under Wumba's Wigwam Glowbo": 777,
  "JRL: Underground Doubloon 1": 778,
  "JRL: Underground Doubloon 2": 779,
  "JRL: Underground Doubloon 3": 780,
  "JRL: Waste Pipe Alcove Signpost": 781,
  "JRL: Waste Pipe Honeycomb": 782,
  "JRL: Wing Whack Silo": 783,
  "JRL: Woo Fak Fak Jiggy": 784,
  "JRL: Woo Fak Fak Mumbo Token": 785,
  "JRL: Wumba's Wigwam Feather Nest": 786,
  "MT Kickball Round 1 Won": 787,
  "MT Kickball Round 2 Won": 788,
  "MT Kickball Round 3 Won": 789,
  "MT: Bovina Egg Nest 1": 790,
  "MT: Bovina Egg Nest 2": 791,
  "MT: Bovina Honeycomb": 792,
  "MT: Bovina Jiggy": 793,
  "MT: Break Flight Pad Boulder": 794,
  "MT: Breegull Blaster Silo": 795,
  "MT: Bridge Jinjo": 796,
  "MT: Egg Aim Silo": 797,
  "MT: Entrance Honeycomb": 798,
  "MT: First Stairs Note 1": 799,
  "MT: First Stairs Note 2": 800,
  "MT: First Stairs Note 3": 801,
  "MT: First Stairs Note 4": 802,
  "MT: Golden Goliath Jiggy": 803,
  "MT: Golden Goliath Signpost": 804,
  "MT: Grip Grab Silo": 805,
  "MT: In Front of Jade Snake Grove Feather Nest 1": 806,
  "MT: In Front of Jade Snake Grove Feather Nest 2": 807,
  "MT: In Front of Prison Compound Egg Nest 1": 808,
  "MT: In Front of Prison Compound Egg Nest 2": 809,
  "MT: Jade Snake Grove Above Code Chamber Egg Nest": 810,
  "MT: Jade Snake Grove Cheato Page": 811,
  "MT: Jade Snake Grove Glowbo": 812,
  "MT: Jade Snake Grove Jinjo": 813,
  "MT: Jade Snake Grove Near Warp Pad Egg Nest 1": 814,
  "MT: Jade Snake Grove Near Warp Pad Egg Nest 2": 815,
  "MT: Jade Snake Grove Quicksand Signpost 1": 816,
  "MT: Jade Snake Grove Quicksand Signpost 2": 817,
  "MT: Kickball Jiggy": 818,
  "MT: Kickball Mumbo Token": 819,
  "MT: Kickball Stadium Feather Nest 1": 820,
  "MT: Kickball Stadium Feather Nest 2": 821,
  "MT: Kickball Stadium Lobby Warp Pad Tagged": 822,
  "MT: Kickball Stadium Switch Pressed": 823,
  "MT: Kill Flies": 824,
  "MT: Left of Code Chamber Signpost": 825,
  "MT: Mumbo's Glowbo": 826,
  "MT: Mumbo's Skull Egg Nest 1": 827,
  "MT: Mumbo's Skull Egg Nest 2": 828,
  "MT: Mumbo's Skull Signpost": 829,
  "MT: Near Wumba's Wigwam Warp Pad Tagged": 830,
  "MT: Open Bottom Treasure Chamber Door": 831,
  "MT: Open Code Chamber": 832,
  "MT: Open Jade Snake Grove": 833,
  "MT: Open Prison Compound": 834,
  "MT: Open Top Treasure Chamber Door": 835,
  "MT: Outside Mumbo's Skull Note": 836,
  "MT: Outside Mumbo's Skull Warp Pad Tagged": 837,
  "MT: Outside Treasure Chamber Egg Nest 1": 838,
  "MT: Outside Treasure Chamber Egg Nest 2": 839,
  "MT: Pillar Jiggy Lowered": 840,
  "MT: Pillars Jiggy": 841,
  "MT: Pillars Signpost": 842,
  "MT: Prison Compound Cell Opened": 843,
  "MT: Prison Compound Cheato Page": 844,
  "MT: Prison Compound Entrance Egg Nest 1": 845,
  "MT: Prison Compound Entrance Egg Nest 2": 846,
  "MT: Prison Compound Jail Cell Boulder Broken": 847,
  "MT: Prison Compound Moon Switch Pressed": 848,
  "MT: Prison Compound Pillars Egg Nest 1": 849,
  "MT: Prison Compound Pillars Egg Nest 2": 850,
  "MT: Prison Compound Pillars Egg Nest 3": 851,
  "MT: Prison Compound Quicksand Jiggy": 852,
  "MT: Prison Compound Quicksand Signpost": 853,
  "MT: Prison Compound Star Switch Pressed": 854,
  "MT: Prison Compound Sun Switch Pressed": 855,
  "MT: Prison Compound Top of Prison Cell Feather Left Nest": 856,
  "MT: Prison Compound Top of Prison Cell Feather Right Nest": 857,
  "MT: Prison Compound Warp Pad Tagged": 858,
  "MT: Second Stairs Note 1": 859,
  "MT: Second Stairs Note 2": 860,
  "MT: Second Stairs Note 3": 861,
  "MT: Second Stairs Note 4": 862,
  "MT: Slighty Sacred Chamber Jiggy": 863,
  "MT: Snake Head 1": 864,
  "MT: Snake Head 2": 865,
  "MT: Snake Head 3": 866,
  "MT: Snake Head 4": 867,
  "MT: Snake Head 5": 868,
  "MT: Snake Head 6": 869,
  "MT: Ssslumber Jiggy": 870,
  "MT: Stadium Jinjo": 871,
  "MT: Targitzan Jiggy": 872,
  "MT: Targitzan Mumbo Token": 873,
  "MT: Targitzan Temple Jinjo": 874,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 1": 875,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 2": 876,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 3": 877,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 4": 878,
  "MT: Targitzan's Temple Blue Pillar Room Relic 1": 879,
  "MT: Targitzan's Temple Blue Pillar Room Relic 2": 880,
  "MT: Targitzan's Temple Blue Pillar Room Relic 3": 881,
  "MT: Targitzan's Temple Golden Egg Nest": 882,
  "MT: Targitzan's Temple Green Pillar Room Relic 1": 883,
  "MT: Targitzan's Temple Green Pillar Room Relic 2": 884,
  "MT: Targitzan's Temple Green Pillar Room Relic 3": 885,
  "MT: Targitzan's Temple Green Pillar Room Relic 4": 886,
  "MT: Targitzan's Temple Green Pillar Room Relic 5": 887,
  "MT: Targitzan's Temple Left Entrance Relic": 888,
  "MT: Targitzan's Temple Lobby Left Egg Nest 1": 889,
  "MT: Targitzan's Temple Lobby Left Egg Nest 2": 890,
  "MT: Targitzan's Temple Lobby Left Egg Nest 3": 891,
  "MT: Targitzan's Temple Lobby Right Egg Nest 1": 892,
  "MT: Targitzan's Temple Lobby Right Egg Nest 2": 893,
  "MT: Targitzan's Temple Lobby Right Egg Nest 3": 894,
  "MT: Targitzan's Temple Near Sacred Chambers Relic 1": 895,
  "MT: Targitzan's Temple Near Sacred Chambers Relic 2": 896,
  "MT: Targitzan's Temple Near Sput Sput Relic 1": 897,
  "MT: Targitzan's Temple Near Sput Sput Relic 2": 898,
  "MT: Targitzan's Temple Near Sput Sput Relic 3": 899,
  "MT: Targitzan's Temple Near Sput Sput Relic 4": 900,
  "MT: Targitzan's Temple Near Sput Sput Relic 5": 901,
  "MT: Targitzan's Temple Pillar Maze Egg Nest 1": 902,
  "MT: Targitzan's Temple Pillar Maze Egg Nest 2": 903,
  "MT: Targitzan's Temple Pillar Maze Egg Nest 3": 904,
  "MT: Targitzan's Temple Raising Slope Room Egg Nest 1": 905,
  "MT: Targitzan's Temple Raising Slope Room Egg Nest 2": 906,
  "MT: Targitzan's Temple Raising Slope Room Egg Nest 3": 907,
  "MT: Targitzan's Temple Red Pillar Room Relic 1": 908,
  "MT: Targitzan's Temple Red Pillar Room Relic 2": 909,
  "MT: Targitzan's Temple Red Pillar Room Relic 3": 910,
  "MT: Targitzan's Temple Right Entrance Relic": 911,
  "MT: Targitzan's Temple Secret Passage Near Entrance Relic 1": 912,
  "MT: Targitzan's Temple Secret Passage Near Entrance Relic 2": 913,
  "MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 1": 914,
  "MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 2": 915,
  "MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 3": 916,
  "MT: Targitzan's Temple Signpost 1": 917,
  "MT: Targitzan's Temple Signpost 2": 918,
  "MT: Third Stairs Note 1": 919,
  "MT: Third Stairs Note 2": 920,
  "MT: Third Stairs Note 3": 921,
  "MT: Third Stairs Note 4": 922,
  "MT: Top Stairs Note 1": 923,
  "MT: Top Stairs Note 2": 924,
  "MT: Top Stairs Note 3": 925,
  "MT: Top of Temple Jiggy": 926,
  "MT: Treasure Chamber Cheato Page": 927,
  "MT: Treasure Chamber Honeycomb": 928,
  "MT: Treasure Chamber Jiggy": 929,
  "MT: Treasure Chamber Unga Bunga Switch Pressed": 930,
  "MT: Treble Clef": 931,
  "MT: Water Pool Jinjo": 932,
  "MT: World Entry and Exit Warp Pad Tagged": 933,
  "MT: Wumba's Wigwam Feather Nest 1": 934,
  "MT: Wumba's Wigwam Feather Nest 2": 935,
  "SM: Attack Tutorial Field Feather Nest 1": 936,
  "SM: Attack Tutorial Field Feather Nest 2": 937,
  "SM: Attack Tutorial Field Feather Nest 3": 938,
  "SM: Base of Spiral Mountain Feather Nest 1": 939,
  "SM: Base of Spiral Mountain Feather Nest 2": 940,
  "SM: Base of Spiral Mountain Feather Nest 3": 941,
  "SM: Blue Mystery Egg": 942,
  "SM: Bottom of Attack Tutorial Field Egg Nest 1": 943,
  "SM: Bottom of Attack Tutorial Field Egg Nest 2": 944,
  "SM: Bottom of Attack Tutorial Field Egg Nest 3": 945,
  "SM: Cheato Page": 946,
  "SM: Cheato Reward 1": 947,
  "SM: Cheato Reward 2": 948,
  "SM: Cheato Reward 3": 949,
  "SM: Cheato Reward 4": 950,
  "SM: Cheato Reward 5": 951,
  "SM: Gruntilda's Lair Egg Nest 1": 952,
  "SM: Gruntilda's Lair Egg Nest 2": 953,
  "SM: Gruntilda's Lair Egg Nest 3": 954,
  "SM: Gruntilda's Lair Egg Nest 4": 955,
  "SM: Gruntilda's Lair Feather Nest 1": 956,
  "SM: Gruntilda's Lair Feather Nest 2": 957,
  "SM: Gruntilda's Lair Feather Nest 3": 958,
  "SM: Jinjo": 959,
  "SM: Near Digger Tunnel Feather Nest 1": 960,
  "SM: Near Digger Tunnel Feather Nest 2": 961,
  "SM: Near Digger Tunnel Feather Nest 3": 962,
  "SM: Pink Mystery Egg": 963,
  "SM: Platform Left of Waterfall Feather Nest 1": 964,
  "SM: Platform Left of Waterfall Feather Nest 2": 965,
  "SM: Roysten Reward 1": 966,
  "SM: Roysten Reward 2": 967,
  "SM: Spiral Mountain Feather Nest 1": 968,
  "SM: Spiral Mountain Feather Nest 2": 969,
  "SM: Spiral Mountain Feather Nest 3": 970,
  "SM: Top-Right of Waterfall Feather Nest": 971,
  "Scrat Healed": 972,
  "TDL: Alcove Near Waterfall Egg Nest 1": 973,
  "TDL: Alcove Near Waterfall Egg Nest 2": 974,
  "TDL: Baby T-Rex Roar": 975,
  "TDL: Behind Mumbo's Skull Glowbo": 976,
  "TDL: Beside Rocknut Jinjo": 977,
  "TDL: Big T. Rex Jinjo": 978,
  "TDL: Bonfire Cavern Entrance Feather Nest": 979,
  "TDL: Bonfire Cavern Exit Feather Nest": 980,
  "TDL: Boulder Cheato Page": 981,
  "TDL: Chompas Belly Jiggy": 982,
  "TDL: Chompas Belly Mumbo Token": 983,
  "TDL: Code of the Dinosaurs Jiggy": 984,
  "TDL: Dippy Jiggy": 985,
  "TDL: Dippy's Pool Cheato Page": 986,
  "TDL: Entrance Egg Nest": 987,
  "TDL: Entrance Jinjo": 988,
  "TDL: Flight Pad Pillar Feather Nest 1": 989,
  "TDL: Flight Pad Pillar Feather Nest 2": 990,
  "TDL: Flight Pad Pillar Feather Nest 3": 991,
  "TDL: Hatch Silo": 992,
  "TDL: Inside The Mountain Near Cheato Page Signpost": 993,
  "TDL: Inside The Mountain Near Top Signpost": 994,
  "TDL: Inside the Mountain Cheato Page": 995,
  "TDL: Inside the Mountain Egg Nest 1": 996,
  "TDL: Inside the Mountain Egg Nest 2": 997,
  "TDL: Inside the Mountain Feather Nest 1": 998,
  "TDL: Inside the Mountain Feather Nest 2": 999,
  "TDL: Lakeside Honeycomb": 1000,
  "TDL: Lakeside Note 1": 1001,
  "TDL: Lakeside Note 2": 1002,
  "TDL: Lakeside Note 3": 1003,
  "TDL: Left of Wall with Holes Egg Nest 1": 1004,
  "TDL: Left of Wall with Holes Egg Nest 2": 1005,
  "TDL: Mumbo's Skull Feather Nest 1": 1006,
  "TDL: Mumbo's Skull Feather Nest 2": 1007,
  "TDL: Near River Passage Entrance Egg Nest": 1008,
  "TDL: Near Shock Spring Pad Up the Mountain Egg Nest 1": 1009,
  "TDL: Near Shock Spring Pad Up the Mountain Egg Nest 2": 1010,
  "TDL: Oogle Boogle Egg Nest 1": 1011,
  "TDL: Oogle Boogle Egg Nest 2": 1012,
  "TDL: Oogle Boogle Feather Nest 1": 1013,
  "TDL: Oogle Boogle Feather Nest 2": 1014,
  "TDL: Oogle Boogle Tribe Jiggy": 1015,
  "TDL: Outside Mumbo's Skull Warp Pad Tagged": 1016,
  "TDL: Outside Wumba's Wigwam Warp Pad Tagged": 1017,
  "TDL: Path to Terry Egg Nest 1": 1018,
  "TDL: Path to Terry Egg Nest 2": 1019,
  "TDL: Path to Terry Feather Nest 1": 1020,
  "TDL: Path to Terry Feather Nest 2": 1021,
  "TDL: Priceless Relic Thingy": 1022,
  "TDL: Right of Scrotty Cave Egg Nest 1": 1023,
  "TDL: Right of Scrotty Cave Egg Nest 2": 1024,
  "TDL: Right of Wall with Holes Egg Nest 1": 1025,
  "TDL: Right of Wall with Holes Egg Nest 2": 1026,
  "TDL: River Passage Feather Nest": 1027,
  "TDL: River Passage Honeycomb": 1028,
  "TDL: River Passage Note 1": 1029,
  "TDL: River Passage Note 2": 1030,
  "TDL: River Passage Note 3": 1031,
  "TDL: River Passage Note 4": 1032,
  "TDL: River Passage Signpost": 1033,
  "TDL: Roar Cage Path Note 1": 1034,
  "TDL: Roar Cage Path Note 2": 1035,
  "TDL: Roar Cage Path Note 3": 1036,
  "TDL: Roar Cage Signpost": 1037,
  "TDL: Rocknut Tribe Jiggy": 1038,
  "TDL: Scrat (Sick)": 1039,
  "TDL: Scrit (Small)": 1040,
  "TDL: Scrotty Jiggy": 1041,
  "TDL: Scrut (Lost)": 1042,
  "TDL: Springy Step Shoes Silo": 1043,
  "TDL: Stomping Plains Jiggy": 1044,
  "TDL: Stomping Plains Jinjo": 1045,
  "TDL: Stomping Plains Left Path Feather Nest 1": 1046,
  "TDL: Stomping Plains Left Path Feather Nest 2": 1047,
  "TDL: Stomping Plains Middle Path Feather Nest": 1048,
  "TDL: Stomping Plains Near Entrance Feather Nest": 1049,
  "TDL: Stomping Plains Right Path Feather Nest 1": 1050,
  "TDL: Stomping Plains Right Path Feather Nest 2": 1051,
  "TDL: Stomping Plains Second Footprint Feather Nest": 1052,
  "TDL: Stomping Plains Warp Pad Tagged": 1053,
  "TDL: Styracosaurus Cave Honeycomb": 1054,
  "TDL: Styracosaurus Family Cave Feather Nest 1": 1055,
  "TDL: Styracosaurus Family Cave Feather Nest 2": 1056,
  "TDL: Styracosaurus Family Cave Feather Nest 3": 1057,
  "TDL: Talon Torpedo Jinjo": 1058,
  "TDL: Taxi Pack Silo": 1059,
  "TDL: Terry Jiggy": 1060,
  "TDL: Terry Mumbo Token": 1061,
  "TDL: Terry's Kids Jiggy": 1062,
  "TDL: Terry's Nest Egg Nest 1": 1063,
  "TDL: Terry's Nest Egg Nest 2": 1064,
  "TDL: Top of the Mountain Egg Nest": 1065,
  "TDL: Top of the Mountain Warp Pad Tagged": 1066,
  "TDL: Train Station Egg Nest 1": 1067,
  "TDL: Train Station Egg Nest 2": 1068,
  "TDL: Train Station Feather Nest 1": 1069,
  "TDL: Train Station Feather Nest 2": 1070,
  "TDL: Train Station Left Note": 1071,
  "TDL: Train Station Middle Note": 1072,
  "TDL: Train Station Right Note": 1073,
  "TDL: Train Switch": 1074,
  "TDL: Treble Clef": 1075,
  "TDL: Under Terry's Nest Jiggy": 1076,
  "TDL: Unga Bunga Cave Entrance Glowbo": 1077,
  "TDL: Unga Bunga's Cave Egg Nest 1": 1078,
  "TDL: Unga Bunga's Cave Egg Nest 2": 1079,
  "TDL: Unga Bunga's Cave Egg Nest 3": 1080,
  "TDL: Unga Bunga's Cave Feather Nest 1": 1081,
  "TDL: Unga Bunga's Cave Feather Nest 2": 1082,
  "TDL: Unga Bunga's Cave Feather Nest 3": 1083,
  "TDL: World Entry and Exit Warp Pad Tagged": 1084,
  "TDL: Zig-Zag Path Note 1": 1085,
  "TDL: Zig-Zag Path Note 2": 1086,
  "TDL: Zig-Zag Path Note 3": 1087,
  "Train At GGM": 1088,
  "Train At GI": 1089,
  "Train At HFP Icy Side": 1090,
  "Train At HFP Lava Side": 1091,
  "Train At IoH": 1092,
  "Train At TDL": 1093,
  "Train At WW": 1094,
  "WW: Airborne Egg Aiming Silo": 1095,
  "WW: Area 51 Egg Nest 1": 1096,
  "WW: Area 51 Egg Nest 2": 1097,
  "WW: Area 51 Gate Left Note": 1098,
  "WW: Area 51 Gate Right Note": 1099,
  "WW: Around the Tent Note 1": 1100,
  "WW: Around the Tent Note 2": 1101,
  "WW: Around the Tent Note 3": 1102,
  "WW: Around the Tent Note 4": 1103,
  "WW: Around the Tent Note 5": 1104,
  "WW: Around the Tent Note 6": 1105,
  "WW: Around the Tent Note 7": 1106,
  "WW: Around the Tent Note 8": 1107,
  "WW: Balloon Burst Jiggy": 1108,
  "WW: Balloon Burst Mumbo Token": 1109,
  "WW: Behind the Big Top Tent Warp Pad Tagged": 1110,
  "WW: Big Top Back Pack Egg Nest 1": 1111,
  "WW: Big Top Back Pack Egg Nest 2": 1112,
  "WW: Big Top Back Pack Feather Nest 1": 1113,
  "WW: Big Top Back Pack Feather Nest 2": 1114,
  "WW: Big Top Front Pack Egg Nest 1": 1115,
  "WW: Big Top Front Pack Egg Nest 2": 1116,
  "WW: Big Top Front Pack Feather Nest 1": 1117,
  "WW: Big Top Front Pack Feather Nest 2": 1118,
  "WW: Big Top Jinjo": 1119,
  "WW: Big Top Left Pack Egg Nest 1": 1120,
  "WW: Big Top Left Pack Egg Nest 2": 1121,
  "WW: Big Top Left Pack Feather Nest 1": 1122,
  "WW: Big Top Left Pack Feather Nest 2": 1123,
  "WW: Big Top Right Pack Egg Nest 1": 1124,
  "WW: Big Top Right Pack Egg Nest 2": 1125,
  "WW: Big Top Right Pack Feather Nest 1": 1126,
  "WW: Big Top Right Pack Feather Nest 2": 1127,
  "WW: Burger Stand Signpost": 1128,
  "WW: Cactus of Strength Jiggy": 1129,
  "WW: Cactus of Strength Jinjo": 1130,
  "WW: Cactus of Strength Signpost": 1131,
  "WW: Cave of Horrors Jinjo": 1132,
  "WW: Crazy Castle Entrance Note 1": 1133,
  "WW: Crazy Castle Entrance Note 2": 1134,
  "WW: Crazy Castle Honeycomb": 1135,
  "WW: Crazy Castle Stockade Egg Nest 1": 1136,
  "WW: Crazy Castle Stockade Egg Nest 2": 1137,
  "WW: Dive of Death Jiggy": 1138,
  "WW: Dive of Death Note 1": 1139,
  "WW: Dive of Death Note 2": 1140,
  "WW: Dodgem Dome Jiggy": 1141,
  "WW: Dodgem Dome Jinjo": 1142,
  "WW: Dodgem Dome Mumbo Token": 1143,
  "WW: Dodgem Dome Signpost": 1144,
  "WW: Entrance Ticket": 1145,
  "WW: Fries Stand Signpost": 1146,
  "WW: Gobi Cage Signpost": 1147,
  "WW: Groggy": 1148,
  "WW: Hoop Hurry Jiggy": 1149,
  "WW: Hoop Hurry Mumbo Token": 1150,
  "WW: Madame Grunty Signpost": 1151,
  "WW: Moggy": 1152,
  "WW: Mr. Patch Jiggy": 1153,
  "WW: Mr. Patch Mumbo Token": 1154,
  "WW: Mrs. Boggy Jiggy": 1155,
  "WW: Mumbo Skull Honeycomb": 1156,
  "WW: Near Mrs Boggy Egg Nest 1": 1157,
  "WW: Near Mrs Boggy Egg Nest 2": 1158,
  "WW: On Big Top Support Feather Nest 1": 1159,
  "WW: On Big Top Support Feather Nest 2": 1160,
  "WW: On Big Top Support Feather Nest 3": 1161,
  "WW: On Big Top Support Feather Nest 4": 1162,
  "WW: On Big Top Support Feather Nest 5": 1163,
  "WW: On Big Top Support Feather Nest 6": 1164,
  "WW: Outside Dodgem Dome Note 1": 1165,
  "WW: Outside Dodgem Dome Note 2": 1166,
  "WW: Outside Mumbo's Skull Warp Pad Tagged": 1167,
  "WW: Outside Star Spinner Egg Nest 1": 1168,
  "WW: Outside Star Spinner Egg Nest 2": 1169,
  "WW: Outside Wumba's Wigwam Warp Pad Tagged": 1170,
  "WW: Pack Whack Silo": 1171,
  "WW: Pump Room Feather Nest 1": 1172,
  "WW: Pump Room Feather Nest 2": 1173,
  "WW: Pump Room Signpost": 1174,
  "WW: Saucer of Peril Cheato Page": 1175,
  "WW: Saucer of Peril Jiggy": 1176,
  "WW: Saucer of Peril Mumbo Token": 1177,
  "WW: Soggy": 1178,
  "WW: Space Ticket": 1179,
  "WW: Space Zone Honeycomb": 1180,
  "WW: Space Zone Warp Pad Tagged": 1181,
  "WW: Split Up Silo": 1182,
  "WW: Spooky Ticket": 1183,
  "WW: Star Spinner Egg Nest": 1184,
  "WW: Star Spinner Feather Nest 1": 1185,
  "WW: Star Spinner Feather Nest 2": 1186,
  "WW: Star Spinner Jiggy": 1187,
  "WW: The Haunted Cavern Cheato Page": 1188,
  "WW: The Haunted Caverns Egg Nest 1": 1189,
  "WW: The Haunted Caverns Egg Nest 2": 1190,
  "WW: The Haunted Caverns Egg Nest 3": 1191,
  "WW: The Haunted Caverns Signpost": 1192,
  "WW: The Inferno Cheato Page": 1193,
  "WW: The Inferno Egg Nest 1": 1194,
  "WW: The Inferno Egg Nest 2": 1195,
  "WW: The Inferno Glowbo": 1196,
  "WW: The Inferno Jiggy": 1197,
  "WW: Train Station Egg Nest 1": 1198,
  "WW: Train Station Egg Nest 2": 1199,
  "WW: Train Switch": 1200,
  "WW: Treble Clef": 1201,
  "WW: Van Door Jinjo": 1202,
  "WW: Western Ticket": 1203,
  "WW: World Entry and Exit Warp Pad Tagged": 1204,
  "WW: Wumba's Glowbo": 1205
}

class AP_CMD:
	NONE = 0
	HANDSHAKE = 1
	PING = 2
	PONG = 3
	STATE = 4
	INFO = 5
	OPTIONS = 6
	LOCATIONS = 7
	ITEMS = 8
	MESSAGE = 9
	DEATH_LINK = 10
	TAG_LINK = 11

class AP_STATE:
	DISCONNECTED = 0
	CONNECTING = 1
	CONNECTED = 2
	PINGED = 4
