# Automatically generated using gen_constants.py

slot_data_names = [
  "shuffle_world_entrances",
  "replace_excess_jiggies",
  "tag_link",
  "golden_egg_nests",
  "slip_traps",
  "open_back_doors",
  "tip_traps",
  "jiggywiggys_challenges",
  "shuffle_train_stations",
  "squish_traps",
  "progressive_bash_attack",
  "preset_logic_tricks",
  "shuffle_warp_silos",
  "victory_goals",
  "dialog_character",
  "shuffle_note_nests",
  "shuffle_warp_pads",
  "progressive_shoes_list",
  "transform_traps",
  "speedup_minigames",
  "progressive_flight_list",
  "shuffle_jiggywiggys_super_special_challenge",
  "replace_excess_note_nests",
  "add_hints_to_archipelago",
  "progressive_eggs",
  "extra_empty_honeycombs",
  "move_hints",
  "extra_mumbo_tokens",
  "extra_feather_nests",
  "preset_jiggywiggys_challenge_costs",
  "shuffle_stop_n_swop",
  "shuffle_chuffy",
  "move_silo_costs",
  "shuffle_doubloons",
  "shuffle_glowbos",
  "progressive_water_training",
  "shuffle_world_order",
  "jiggywiggys_challenge_costs",
  "preset_victory_goals",
  "shuffle_nests",
  "shuffle_cheato_rewards",
  "instant_transform",
  "chosen_move_silo_costs",
  "shuffle_bt_moves",
  "max_mumbo_tokens",
  "open_hag1",
  "shuffle_beans",
  "shuffle_signs",
  "shuffle_jinjos",
  "death_link",
  "extra_cheato_pages",
  "trip_traps",
  "chosen_eggs",
  "extra_treble_clefs",
  "hint_clarity",
  "progressive_water_training_list",
  "progressive_flight",
  "progressive_shoes",
  "extra_doubloons",
  "extra_bass_clefs",
  "shuffle_treble_clefs",
  "open_warp_silos",
  "easy_canary",
  "logic_tricks",
  "extra_jiggies",
  "extra_cheats",
  "shuffle_bk_moves",
  "shuffle_honeyb_rewards",
  "skip_klungo",
  "sign_hints",
  "shuffle_boss_entrances",
  "replace_excess_mumbo_tokens",
  "extra_egg_nests",
  "starting_eggs",
  "chosen_goals",
  "open_gi_front_door",
  "shuffle_big_top_tickets",
  "shuffle_cheato_pages",
  "progressive_aiming",
  "auto_enable_cheats",
  "tower_of_tragedy",
  "progressive_beak_buster",
  "progressive_aiming_list",
  "shuffle_green_relics",
  "shuffle_honeycombs",
  "extra_note_nests"
]

option_name_to_id = {
  "death_link": 0,
  "tag_link": 1,
  "preset_victory_goals": 2,
  "victory_goals_hag_1": 3,
  "victory_goals_targitzan": 4,
  "victory_goals_old_king_coal": 5,
  "victory_goals_mr_patch": 6,
  "victory_goals_lord_woo_fak_fak": 7,
  "victory_goals_terry": 8,
  "victory_goals_weldar": 9,
  "victory_goals_chilly_willy": 10,
  "victory_goals_chilli_billi": 11,
  "victory_goals_mingy_jongo": 12,
  "victory_goals_mt_kickball": 13,
  "victory_goals_ordnance_storage": 14,
  "victory_goals_hoop_hurry": 15,
  "victory_goals_dodgem_dome": 16,
  "victory_goals_saucer_of_peril": 17,
  "victory_goals_balloon_burst": 18,
  "victory_goals_mini_sub_challenge": 19,
  "victory_goals_chompas_belly": 20,
  "victory_goals_clinkers_cavern": 21,
  "victory_goals_twinkly_packing": 22,
  "victory_goals_hfp_kickball": 23,
  "victory_goals_pot_o_gold": 24,
  "victory_goals_zubbas": 25,
  "victory_goals_trash_can": 26,
  "victory_goals_canary_mary": 27,
  "victory_goals_tower_of_tragedy": 28,
  "victory_goals_white_jinjo_family": 29,
  "victory_goals_orange_jinjo_family": 30,
  "victory_goals_yellow_jinjo_family": 31,
  "victory_goals_brown_jinjo_family": 32,
  "victory_goals_green_jinjo_family": 33,
  "victory_goals_red_jinjo_family": 34,
  "victory_goals_blue_jinjo_family": 35,
  "victory_goals_purple_jinjo_family": 36,
  "victory_goals_black_jinjo_family": 37,
  "extra_mumbo_tokens": 38,
  "max_mumbo_tokens": 39,
  "replace_excess_mumbo_tokens": 40,
  "open_hag1": 41,
  "preset_logic_tricks_easy_tricks": 42,
  "preset_logic_tricks_easy_tedious_tricks": 43,
  "preset_logic_tricks_easy_glitches": 44,
  "preset_logic_tricks_hard_tricks": 45,
  "preset_logic_tricks_hard_tedious_tricks": 46,
  "preset_logic_tricks_hard_glitches": 47,
  "preset_logic_tricks_frame_perfect": 48,
  "logic_tricks_beak_barge_jump": 49,
  "logic_tricks_beak_buster_fall": 50,
  "logic_tricks_beak_buster_jump": 51,
  "logic_tricks_bill_drill_jump": 52,
  "logic_tricks_breegull_bash_fall": 53,
  "logic_tricks_breegull_bash_grab": 54,
  "logic_tricks_dragunda_sidle": 55,
  "logic_tricks_easy_jumps": 56,
  "logic_tricks_gi_extra_loggo_moves": 57,
  "logic_tricks_ground_rat_a_tat_rap_fall": 58,
  "logic_tricks_ground_rat_a_tat_rap_jump": 59,
  "logic_tricks_pack_whack_fall": 60,
  "logic_tricks_pack_whack_jump": 61,
  "logic_tricks_roll_jump": 62,
  "logic_tricks_sack_pack_air_jump": 63,
  "logic_tricks_sack_pack_fall": 64,
  "logic_tricks_shack_pack_air_jump": 65,
  "logic_tricks_shack_pack_fall": 66,
  "logic_tricks_snooze_pack_fall": 67,
  "logic_tricks_taxi_pack_fall": 68,
  "logic_tricks_beak_bomb_tricks": 69,
  "logic_tricks_damage_boost": 70,
  "logic_tricks_damage_boost_jump": 71,
  "logic_tricks_death_warp": 72,
  "logic_tricks_easy_tedious_jumps": 73,
  "logic_tricks_extra_clockwork_usage": 74,
  "logic_tricks_fall_damage": 75,
  "logic_tricks_gi_quality_control_vent_as_banjo": 76,
  "logic_tricks_gi_guarded_jiggy_without_fighting": 77,
  "logic_tricks_instant_transform_trick": 78,
  "logic_tricks_talon_trot_smuggle": 79,
  "logic_tricks_talon_trot_smuggle_cross_world": 80,
  "logic_tricks_wonderwing_damage_boost": 81,
  "logic_tricks_wonderwing_fall": 82,
  "logic_tricks_wonderwing_jump": 83,
  "logic_tricks_air_rat_a_tat_rap_clip": 84,
  "logic_tricks_beak_barge_clip": 85,
  "logic_tricks_breegull_bash_clip": 86,
  "logic_tricks_free_shock_spring_pad": 87,
  "logic_tricks_hard_jumps": 88,
  "logic_tricks_slide_jump": 89,
  "logic_tricks_flap_flip_slide_extension": 90,
  "logic_tricks_hard_tedious_jumps": 91,
  "logic_tricks_talon_trot_slide_jump": 92,
  "logic_tricks_sack_pack_ending_jump": 93,
  "instant_transform": 94,
  "shuffle_bk_moves": 95,
  "shuffle_bt_moves": 96,
  "shuffle_glowbos": 97,
  "shuffle_jinjos": 98,
  "shuffle_treble_clefs": 99,
  "shuffle_note_nests": 100,
  "shuffle_honeycombs": 101,
  "shuffle_honeyb_rewards": 102,
  "shuffle_cheato_pages": 103,
  "shuffle_cheato_rewards": 104,
  "shuffle_stop_n_swop": 105,
  "shuffle_doubloons": 106,
  "shuffle_green_relics": 107,
  "shuffle_big_top_tickets": 108,
  "shuffle_beans": 109,
  "shuffle_warp_silos": 110,
  "shuffle_warp_pads": 111,
  "shuffle_signs": 112,
  "shuffle_jiggywiggys_super_special_challenge": 113,
  "shuffle_nests": 114,
  "shuffle_chuffy": 115,
  "shuffle_train_stations": 116,
  "shuffle_world_order": 117,
  "shuffle_world_entrances": 118,
  "shuffle_boss_entrances": 119,
  "progressive_eggs": 120,
  "progressive_aiming": 121,
  "progressive_flight": 122,
  "progressive_water_training": 123,
  "progressive_beak_buster": 124,
  "progressive_bash_attack": 125,
  "progressive_shoes": 126,
  "progressive_aiming_list_third_person_egg_shooting": 127,
  "progressive_aiming_list_amaze_o_gaze": 128,
  "progressive_aiming_list_egg_aim": 129,
  "progressive_aiming_list_breegull_blaster": 130,
  "progressive_flight_list_flight_pad": 131,
  "progressive_flight_list_beak_bomb": 132,
  "progressive_flight_list_airborne_egg_aiming": 133,
  "progressive_water_training_list_dive": 134,
  "progressive_water_training_list_sub_aqua_egg_aiming": 135,
  "progressive_water_training_list_talon_torpedo": 136,
  "progressive_water_training_list_double_air": 137,
  "progressive_water_training_list_fast_swimming": 138,
  "progressive_shoes_list_stilt_stride": 139,
  "progressive_shoes_list_turbo_trainers": 140,
  "progressive_shoes_list_springy_step_shoes": 141,
  "progressive_shoes_list_claw_clamber_boots": 142,
  "skip_klungo": 143,
  "tower_of_tragedy": 144,
  "speedup_minigames": 145,
  "open_gi_front_door": 146,
  "open_back_doors": 147,
  "easy_canary": 148,
  "sign_hints": 149,
  "move_hints": 150,
  "hint_clarity": 151,
  "add_hints_to_archipelago": 152,
  "replace_excess_jiggies": 153,
  "replace_excess_note_nests": 154,
  "extra_jiggies": 155,
  "extra_note_nests": 156,
  "extra_bass_clefs": 157,
  "extra_treble_clefs": 158,
  "extra_doubloons": 159,
  "extra_empty_honeycombs": 160,
  "extra_cheato_pages": 161,
  "extra_egg_nests": 162,
  "extra_feather_nests": 163,
  "trip_traps": 164,
  "slip_traps": 165,
  "tip_traps": 166,
  "transform_traps": 167,
  "golden_egg_nests": 168,
  "squish_traps": 169,
  "jiggywiggys_challenges": 170,
  "preset_jiggywiggys_challenge_costs": 171,
  "jiggywiggys_challenge_costs_challenge_1": 172,
  "jiggywiggys_challenge_costs_challenge_2": 173,
  "jiggywiggys_challenge_costs_challenge_3": 174,
  "jiggywiggys_challenge_costs_challenge_4": 175,
  "jiggywiggys_challenge_costs_challenge_5": 176,
  "jiggywiggys_challenge_costs_challenge_6": 177,
  "jiggywiggys_challenge_costs_challenge_7": 178,
  "jiggywiggys_challenge_costs_challenge_8": 179,
  "jiggywiggys_challenge_costs_challenge_9": 180,
  "jiggywiggys_challenge_costs_challenge_10": 181,
  "jiggywiggys_challenge_costs_challenge_11": 182,
  "starting_eggs_blue_eggs": 183,
  "starting_eggs_fire_eggs": 184,
  "starting_eggs_grenade_eggs": 185,
  "starting_eggs_ice_eggs": 186,
  "starting_eggs_clockwork_kazooie_eggs": 187,
  "open_warp_silos": 188,
  "move_silo_costs": 189,
  "extra_cheats": 190,
  "auto_enable_cheats_feathers": 191,
  "auto_enable_cheats_eggs": 192,
  "auto_enable_cheats_fallproof": 193,
  "auto_enable_cheats_honeyback": 194,
  "auto_enable_cheats_homing_eggs": 195,
  "dialog_character_alien": 196,
  "dialog_character_alien_child": 197,
  "dialog_character_all": 198,
  "dialog_character_banjo": 199,
  "dialog_character_banjo_kazooie": 200,
  "dialog_character_bargasaurus": 201,
  "dialog_character_beehive": 202,
  "dialog_character_bigga_foot": 203,
  "dialog_character_big_al": 204,
  "dialog_character_blobbelda": 205,
  "dialog_character_boggy": 206,
  "dialog_character_bottles": 207,
  "dialog_character_bottles_dead": 208,
  "dialog_character_bovina": 209,
  "dialog_character_canary_mary": 210,
  "dialog_character_captain_blackeye": 211,
  "dialog_character_captain_blubber": 212,
  "dialog_character_cheato": 213,
  "dialog_character_chief_bloatazin": 214,
  "dialog_character_chilli_billi": 215,
  "dialog_character_chilly_willy": 216,
  "dialog_character_chompa": 217,
  "dialog_character_chris_p_bacon": 218,
  "dialog_character_conga": 219,
  "dialog_character_dilberta": 220,
  "dialog_character_dingpot": 221,
  "dialog_character_dino_kid1": 222,
  "dialog_character_dino_kid2": 223,
  "dialog_character_dino_scrit_big": 224,
  "dialog_character_dino_scrit_small": 225,
  "dialog_character_dippy": 226,
  "dialog_character_evil_bottles": 227,
  "dialog_character_george": 228,
  "dialog_character_gi_announcer": 229,
  "dialog_character_glowbo": 230,
  "dialog_character_gobi": 231,
  "dialog_character_goggles": 232,
  "dialog_character_groggy": 233,
  "dialog_character_grunty": 234,
  "dialog_character_guffo": 235,
  "dialog_character_heggy": 236,
  "dialog_character_honeycomb": 237,
  "dialog_character_honey_b": 238,
  "dialog_character_humba": 239,
  "dialog_character_jamjars": 240,
  "dialog_character_jiggy": 241,
  "dialog_character_jiggywiggy": 242,
  "dialog_character_jiggywiggy_disciple": 243,
  "dialog_character_jinjo_black": 244,
  "dialog_character_jinjo_blue": 245,
  "dialog_character_jinjo_brown": 246,
  "dialog_character_jinjo_green": 247,
  "dialog_character_jinjo_orange": 248,
  "dialog_character_jinjo_purple": 249,
  "dialog_character_jinjo_red": 250,
  "dialog_character_jinjo_white": 251,
  "dialog_character_jinjo_yellow": 252,
  "dialog_character_jolly": 253,
  "dialog_character_kazooie": 254,
  "dialog_character_king_jingaling": 255,
  "dialog_character_king_jingaling_dead": 256,
  "dialog_character_klungo": 257,
  "dialog_character_loggo": 258,
  "dialog_character_lord_woo_fak_fak": 259,
  "dialog_character_merry_maggie": 260,
  "dialog_character_mildred": 261,
  "dialog_character_mingella": 262,
  "dialog_character_mingy_jongo": 263,
  "dialog_character_minjo_black": 264,
  "dialog_character_minjo_blue": 265,
  "dialog_character_minjo_brown": 266,
  "dialog_character_minjo_green": 267,
  "dialog_character_minjo_orange": 268,
  "dialog_character_minjo_purple": 269,
  "dialog_character_minjo_red": 270,
  "dialog_character_minjo_white": 271,
  "dialog_character_minjo_yellow": 272,
  "dialog_character_moggy": 273,
  "dialog_character_mrs_boggy": 274,
  "dialog_character_mrs_bottles": 275,
  "dialog_character_mr_fit": 276,
  "dialog_character_mr_patch": 277,
  "dialog_character_mumbo": 278,
  "dialog_character_old_king_coal": 279,
  "dialog_character_oogle_boogle": 280,
  "dialog_character_pawno": 281,
  "dialog_character_pig1": 282,
  "dialog_character_prospector": 283,
  "dialog_character_rabbit_worker1": 284,
  "dialog_character_rocknut": 285,
  "dialog_character_roysten": 286,
  "dialog_character_sabreman": 287,
  "dialog_character_safe": 288,
  "dialog_character_salty_joe": 289,
  "dialog_character_soggy": 290,
  "dialog_character_speccy": 291,
  "dialog_character_ssslumber": 292,
  "dialog_character_stonies1": 293,
  "dialog_character_styracosaurus_mom": 294,
  "dialog_character_sub": 295,
  "dialog_character_targitzan": 296,
  "dialog_character_terry": 297,
  "dialog_character_tiptup": 298,
  "dialog_character_ufo": 299,
  "dialog_character_unga_bunga": 300,
  "dialog_character_unogopaz": 301,
  "dialog_character_washer": 302,
  "dialog_character_weldar": 303,
  "dialog_character_yellow_dodgem": 304,
  "dialog_character_yellow_stony": 305,
  "dialog_character_zubba": 306,
  "chosen_eggs": 307,
  "chosen_goals_hag_1": 308,
  "chosen_goals_targitzan": 309,
  "chosen_goals_old_king_coal": 310,
  "chosen_goals_mr_patch": 311,
  "chosen_goals_lord_woo_fak_fak": 312,
  "chosen_goals_terry": 313,
  "chosen_goals_weldar": 314,
  "chosen_goals_chilly_willy": 315,
  "chosen_goals_chilli_billi": 316,
  "chosen_goals_mingy_jongo": 317,
  "chosen_goals_mt_kickball": 318,
  "chosen_goals_ordnance_storage": 319,
  "chosen_goals_hoop_hurry": 320,
  "chosen_goals_dodgem_dome": 321,
  "chosen_goals_saucer_of_peril": 322,
  "chosen_goals_balloon_burst": 323,
  "chosen_goals_mini_sub_challenge": 324,
  "chosen_goals_chompas_belly": 325,
  "chosen_goals_clinkers_cavern": 326,
  "chosen_goals_twinkly_packing": 327,
  "chosen_goals_hfp_kickball": 328,
  "chosen_goals_pot_o_gold": 329,
  "chosen_goals_zubbas": 330,
  "chosen_goals_trash_can": 331,
  "chosen_goals_canary_mary": 332,
  "chosen_goals_tower_of_tragedy": 333,
  "chosen_goals_white_jinjo_family": 334,
  "chosen_goals_orange_jinjo_family": 335,
  "chosen_goals_yellow_jinjo_family": 336,
  "chosen_goals_brown_jinjo_family": 337,
  "chosen_goals_green_jinjo_family": 338,
  "chosen_goals_red_jinjo_family": 339,
  "chosen_goals_blue_jinjo_family": 340,
  "chosen_goals_purple_jinjo_family": 341,
  "chosen_goals_black_jinjo_family": 342,
  "chosen_move_silo_costs_fire_eggs": 343,
  "chosen_move_silo_costs_grenade_eggs": 344,
  "chosen_move_silo_costs_ice_eggs": 345,
  "chosen_move_silo_costs_clockwork_kazooie_eggs": 346,
  "chosen_move_silo_costs_egg_aim": 347,
  "chosen_move_silo_costs_breegull_blaster": 348,
  "chosen_move_silo_costs_grip_grab": 349,
  "chosen_move_silo_costs_bill_drill": 350,
  "chosen_move_silo_costs_beak_bayonet": 351,
  "chosen_move_silo_costs_split_up": 352,
  "chosen_move_silo_costs_pack_whack": 353,
  "chosen_move_silo_costs_airborne_egg_aiming": 354,
  "chosen_move_silo_costs_wing_whack": 355,
  "chosen_move_silo_costs_sub_aqua_egg_aiming": 356,
  "chosen_move_silo_costs_talon_torpedo": 357,
  "chosen_move_silo_costs_springy_step_shoes": 358,
  "chosen_move_silo_costs_taxi_pack": 359,
  "chosen_move_silo_costs_hatch": 360,
  "chosen_move_silo_costs_claw_clamber_boots": 361,
  "chosen_move_silo_costs_snooze_pack": 362,
  "chosen_move_silo_costs_leg_spring": 363,
  "chosen_move_silo_costs_shack_pack": 364,
  "chosen_move_silo_costs_glide": 365,
  "chosen_move_silo_costs_sack_pack": 366
}

item_name_to_id = {
  "Air Rat-a-tat Rap": 1,
  "Airborne Egg Aiming": 2,
  "Amaze-O-Gaze": 3,
  "Baby T-Rex Roar": 4,
  "Bass Clef": 5,
  "Beak Barge": 6,
  "Beak Bayonet": 7,
  "Beak Bomb": 8,
  "Beak Buster": 9,
  "Bean": 10,
  "Big Top Ticket": 11,
  "Big-O Pants": 12,
  "Bill Drill": 13,
  "Black Jinjo": 14,
  "Blue Eggs": 15,
  "Blue Jinjo": 16,
  "Blue Mystery Egg": 17,
  "Breegull Bash": 18,
  "Breegull Blaster": 19,
  "Brown Jinjo": 20,
  "CCL: Central Cavern Warp Pad": 21,
  "CCL: World Entry And Exit Warp Pad": 22,
  "CK: Bottom Of The Tower Warp Pad": 23,
  "CK: Top Of The Tower Warp Pad": 24,
  "Cauldron Keep": 25,
  "Cheato Page": 26,
  "Cheato Reward: Eggs": 27,
  "Cheato Reward: Fallproof": 28,
  "Cheato Reward: Feathers": 29,
  "Cheato Reward: Honeyback": 30,
  "Cheato Reward: Jukebox": 31,
  "Chuffy": 32,
  "Claw Clamber Boots": 33,
  "Cliff Top Warp Silo": 34,
  "Climb": 35,
  "Clockwork Kazooie Eggs": 36,
  "Cloud Cuckooland": 37,
  "Dive": 38,
  "Double Air": 39,
  "Doubloon": 40,
  "Egg Aim": 41,
  "Egg Nest": 42,
  "Empty Honeycomb": 43,
  "Fast Swimming": 44,
  "Feather Nest": 45,
  "Fire Eggs": 46,
  "Flap Flip": 47,
  "Flight Pad": 48,
  "Flutter": 49,
  "GGM: Inside Wumba's Wigwam Warp Pad": 50,
  "GGM: Near The Train Station Warp Pad": 51,
  "GGM: Outside Mumbo's Skull Warp Pad": 52,
  "GGM: Outside The Crushing Shed Warp Pad": 53,
  "GGM: World Entry And Exit Warp Pad": 54,
  "GI Cleaned Skivvy": 55,
  "GI Floor 1: Entrance Door Warp Pad": 56,
  "GI Floor 2: Outside Wumba's Wigwam Warp Pad": 57,
  "GI Floor 3: Outside Mumbo's Skull Warp Pad": 58,
  "GI Floor 4: Near The Crushers Warp Pad": 59,
  "GI Outside: On The Roof Outside Warp Pad": 60,
  "GI: Train Station": 61,
  "Glide": 62,
  "Glitter Gulch Mine": 63,
  "Golden Egg Nest": 64,
  "Green Jinjo": 65,
  "Green Relic": 66,
  "Grenade Eggs": 67,
  "Grip Grab": 68,
  "Ground Rat-a-tat Rap": 69,
  "Grunty Industries": 70,
  "HAG-1": 71,
  "HFP: Fire Side - Lower Area (Mumbo) Warp Pad": 72,
  "HFP: Fire Side - Upper Area Warp Pad": 73,
  "HFP: Ice Side - Inside Icicle Grotto Warp Pad": 74,
  "HFP: Ice Side - Lower Area (Wumba) Warp Pad": 75,
  "HFP: Ice Side - Upper Area Warp Pad": 76,
  "HFP: Icy Side Train Station": 77,
  "HFP: Lava Side Train Station": 78,
  "Hailfire Peaks": 79,
  "Hatch": 80,
  "Health Upgrade": 81,
  "Homing Eggs": 82,
  "Humba: Bee": 83,
  "Humba: Detonator": 84,
  "Humba: Dragon": 85,
  "Humba: Money Van": 86,
  "Humba: Snowball": 87,
  "Humba: Stony": 88,
  "Humba: Sub": 89,
  "Humba: T-Rex": 90,
  "Humba: Washing Machine": 91,
  "Ice Eggs": 92,
  "Ice Key": 93,
  "IoH: Train Station": 94,
  "JRL: Atlantis Warp Pad": 95,
  "JRL: Big Fish Cavern Warp Pad": 96,
  "JRL: Lockers Cavern Warp Pad": 97,
  "JRL: Sunken Ship Warp Pad": 98,
  "JRL: Town Center Warp Pad": 99,
  "Jiggy": 100,
  "Jinjo Village Warp Silo": 101,
  "Jolly Roger's Lagoon": 102,
  "Leg Spring": 103,
  "MT: Kickball Stadium Lobby Warp Pad": 104,
  "MT: Near Wumba's Wigwam Warp Pad": 105,
  "MT: Outside Mumbo's Skull Warp Pad": 106,
  "MT: Prison Compound Warp Pad": 107,
  "MT: World Entry And Exit Warp Pad": 108,
  "Mayahem Temple": 109,
  "Mumbo Token": 110,
  "Mumbo: EMP": 111,
  "Mumbo: Enlarge": 112,
  "Mumbo: Golden Goliath": 113,
  "Mumbo: Heal": 114,
  "Mumbo: Levitate": 115,
  "Mumbo: Life Force": 116,
  "Mumbo: Oxygenate": 117,
  "Mumbo: Power": 118,
  "Mumbo: Rain Dance": 119,
  "Note Nest": 120,
  "Nothing": 121,
  "Orange Jinjo": 122,
  "Pack Whack": 123,
  "Pine Grove Warp Silo": 124,
  "Pink Mystery Egg": 125,
  "Plateau Warp Silo": 126,
  "Progressive Aiming": 127,
  "Progressive Bash Attack": 128,
  "Progressive Beak Buster": 129,
  "Progressive Eggs": 130,
  "Progressive Flight": 131,
  "Progressive Shoes": 132,
  "Progressive Water Training": 133,
  "Purple Jinjo": 134,
  "Quagmire Warp Silo": 135,
  "Red Jinjo": 136,
  "Roll": 137,
  "Sack Pack": 138,
  "Shack Pack": 139,
  "Slip Trap": 140,
  "Snooze Pack": 141,
  "Split Up": 142,
  "Springy Step Shoes": 143,
  "Squish Trap": 144,
  "Stilt Stride": 145,
  "Sub-Aqua Egg Aiming": 146,
  "TDL: Outside Mumbo's Skull Warp Pad": 147,
  "TDL: Outside Wumba's Wigwam Warp Pad": 148,
  "TDL: Stomping Plains Warp Pad": 149,
  "TDL: Top Of The Mountain Warp Pad": 150,
  "TDL: Train Station": 151,
  "TDL: World Entry And Exit Warp Pad": 152,
  "Tall Jump": 153,
  "Talon Torpedo": 154,
  "Talon Trot": 155,
  "Taxi Pack": 156,
  "Terrydactyland": 157,
  "Third Person Egg Shooting": 158,
  "Tip Trap": 159,
  "Transform Trap": 160,
  "Treble Clef": 161,
  "Trip Trap": 162,
  "Turbo Trainers": 163,
  "WW: Behind The Big Top Tent Warp Pad": 164,
  "WW: Outside Mumbo's Skull Warp Pad": 165,
  "WW: Outside Wumba's Wigwam Warp Pad": 166,
  "WW: Space Zone Warp Pad": 167,
  "WW: Train Station": 168,
  "WW: World Entry And Exit Warp Pad": 169,
  "Wasteland Warp Silo": 170,
  "White Jinjo": 171,
  "Wing Whack": 172,
  "Witchyworld": 173,
  "Wonderwing": 174,
  "Wooded Hollow Warp Silo": 175,
  "Yellow Jinjo": 176
}

location_name_to_id = {
  "CCL: Behind the Trash Can Feather Nest 1": 1,
  "CCL: Behind the Trash Can Feather Nest 2": 2,
  "CCL: Behind the Trash Can Feather Nest 3": 3,
  "CCL: Behind the Trash Can Feather Nest 4": 4,
  "CCL: Blue Skull Exit Note": 5,
  "CCL: By George Feather Nest 1": 6,
  "CCL: By George Feather Nest 2": 7,
  "CCL: By George Feather Nest 3": 8,
  "CCL: By George Feather Nest 4": 9,
  "CCL: Canary Mary Cheato Page": 10,
  "CCL: Canary Mary Jiggy": 11,
  "CCL: Canary Mary Mumbo Token": 12,
  "CCL: Central Cavern Jinjo": 13,
  "CCL: Central Cavern Top Path Egg Nest 1": 14,
  "CCL: Central Cavern Top Path Egg Nest 2": 15,
  "CCL: Central Cavern Under Cheese Wedge Exit Egg Nest 1": 16,
  "CCL: Central Cavern Under Cheese Wedge Exit Egg Nest 2": 17,
  "CCL: Central Cavern Warp Pad Tagged": 18,
  "CCL: Central Cavern on Steps Near Main Entrance Egg Nest": 19,
  "CCL: Central Note 1": 20,
  "CCL: Central Note 2": 21,
  "CCL: Central Note 3": 22,
  "CCL: Cheese Wedge Exit Note": 23,
  "CCL: Cheese Wedge Jiggy": 24,
  "CCL: Cheese Wedge Jinjo": 25,
  "CCL: Dippy Pool Feather Nest 1": 26,
  "CCL: Dippy Pool Feather Nest 2": 27,
  "CCL: Dippy Pool Feather Nest 3": 28,
  "CCL: Dippy Pool Feather Nest 4": 29,
  "CCL: Dippy Pool Note": 30,
  "CCL: Dirt Patch Bean 1": 31,
  "CCL: Dirt Patch Bean 2": 32,
  "CCL: Dirt Patch Egg Nest": 33,
  "CCL: Dirt Patch Feather Nest": 34,
  "CCL: Dirt Patch Honeycomb": 35,
  "CCL: Glowbo Pool Note": 36,
  "CCL: High Jump Event Feather Nest": 37,
  "CCL: Indoors Pool Glowbo": 38,
  "CCL: Indoors Pool Underwater Signpost": 39,
  "CCL: Inside Cheese Wedge Egg Nest 1": 40,
  "CCL: Inside Cheese Wedge Egg Nest 2": 41,
  "CCL: Jelly Castle Egg Nest 1": 42,
  "CCL: Jelly Castle Egg Nest 2": 43,
  "CCL: Jelly Castle Egg Nest 3": 44,
  "CCL: Jelly Castle Egg Nest 4": 45,
  "CCL: Jelly Castle Jiggy": 46,
  "CCL: Jiggium Plant Jiggy": 47,
  "CCL: Main Entrance Note": 48,
  "CCL: Mingy Jongo Jiggy": 49,
  "CCL: Mingy Jongo Mumbo Token": 50,
  "CCL: Mingy Jongo Skull Jinjo": 51,
  "CCL: Mr Fit Jiggy": 52,
  "CCL: Mr. Fit Footrace Track Note": 53,
  "CCL: Mr. Fit High Jump Event": 54,
  "CCL: Mr. Fit Sack Race Event": 55,
  "CCL: Mr. Fit Sack Race Exit Note": 56,
  "CCL: Near Blue Skull Feather Nest 1": 57,
  "CCL: Near Blue Skull Feather Nest 2": 58,
  "CCL: Near Blue Skull Feather Nest 3": 59,
  "CCL: Near Blue Skull Feather Nest 4": 60,
  "CCL: Near Red Skull Feather Nest 1": 61,
  "CCL: Near Red Skull Feather Nest 2": 62,
  "CCL: Near Red Skull Feather Nest 3": 63,
  "CCL: Near Red Skull Feather Nest 4": 64,
  "CCL: Near Top Superstash Switch Feather Nest 1": 65,
  "CCL: Near Top Superstash Switch Feather Nest 2": 66,
  "CCL: On Rim of Glowbo Pool Signpost": 67,
  "CCL: Outdoors Pool Glowbo": 68,
  "CCL: Outside Cheese Wedge Feather Nest 1": 69,
  "CCL: Outside Cheese Wedge Feather Nest 2": 70,
  "CCL: Outside Cheese Wedge Feather Nest 3": 71,
  "CCL: Outside Cheese Wedge Feather Nest 4": 72,
  "CCL: Pot O' Gold Cheato Page": 73,
  "CCL: Pot O' Gold Honeycomb": 74,
  "CCL: Pot O' Gold Jiggy": 75,
  "CCL: Pot O' Gold Mumbo Token": 76,
  "CCL: Pot o' Gold Egg Nest 1": 77,
  "CCL: Pot o' Gold Egg Nest 2": 78,
  "CCL: Pot o' Gold Exit Note": 79,
  "CCL: Red Skull Exit Note": 80,
  "CCL: Sack Pack Silo": 81,
  "CCL: Sack Pack Silo Note 1": 82,
  "CCL: Sack Pack Silo Note 2": 83,
  "CCL: Sack Pack Silo Signpost": 84,
  "CCL: Superstash Jiggy": 85,
  "CCL: Top Entrance Feather Nest 1": 86,
  "CCL: Top Entrance Feather Nest 2": 87,
  "CCL: Top Entrance Note": 88,
  "CCL: Top Superstash Switch Note": 89,
  "CCL: Top-Left of Superstash Egg Nest 1": 90,
  "CCL: Top-Left of Superstash Egg Nest 2": 91,
  "CCL: Trash Can Egg Nest 1": 92,
  "CCL: Trash Can Egg Nest 2": 93,
  "CCL: Trash Can Honeycomb": 94,
  "CCL: Trash Can Jiggy": 95,
  "CCL: Trash Can Jinjo": 96,
  "CCL: Trash Can Mumbo Token": 97,
  "CCL: Treble Clef": 98,
  "CCL: World Entry and Exit Warp Pad Tagged": 99,
  "CCL: Wumba Jinjo": 100,
  "CCL: Wumba's Wigwam Egg Nest 1": 101,
  "CCL: Wumba's Wigwam Egg Nest 2": 102,
  "CCL: Wumba's Wigwam Signpost": 103,
  "CCL: Zubbas Cheato Page": 104,
  "CCL: Zubbas Jiggy": 105,
  "CCL: Zubbas Mumbo Token": 106,
  "CK: Bottom of the Tower Warp Pad Tagged": 107,
  "CK: Defeated HAG-1": 108,
  "CK: Top of the Tower Warp Pad Tagged": 109,
  "CK: Tower Of Tragedy Mumbo Token": 110,
  "Completion Condition": 0,
  "GGM: Beak Bayonet Silo": 111,
  "GGM: Bill Drill Silo": 112,
  "GGM: Boulder Jinjo": 113,
  "GGM: Canary Cave Back-Left Egg Nest": 114,
  "GGM: Canary Cave Back-Right Feather Nest": 115,
  "GGM: Canary Cave Front-Left Feather Nest": 116,
  "GGM: Canary Cave Front-Right Egg Nest": 117,
  "GGM: Canary Mary Cheato Page": 118,
  "GGM: Canary Mary Jiggy": 119,
  "GGM: Chuffy": 120,
  "GGM: Crushing Shed Egg Nest 1": 121,
  "GGM: Crushing Shed Egg Nest 2": 122,
  "GGM: Crushing Shed Jiggy": 123,
  "GGM: Crushing Shed Jiggy Chunk 1": 124,
  "GGM: Crushing Shed Jiggy Chunk 2": 125,
  "GGM: Crushing Shed Jiggy Chunk 3": 126,
  "GGM: Defeated Chuffy": 127,
  "GGM: Dilberta Jiggy": 128,
  "GGM: Entrance Cheato Page": 129,
  "GGM: Flooded Caves Egg Nest 1": 130,
  "GGM: Flooded Caves Egg Nest 2": 131,
  "GGM: Flooded Caves Jiggy": 132,
  "GGM: Fuel Depot Back-Left Note": 133,
  "GGM: Fuel Depot Back-Right Note": 134,
  "GGM: Fuel Depot Egg Nest 1": 135,
  "GGM: Fuel Depot Egg Nest 2": 136,
  "GGM: Fuel Depot Egg Nest 3": 137,
  "GGM: Fuel Depot Feather Nest 1": 138,
  "GGM: Fuel Depot Feather Nest 2": 139,
  "GGM: Fuel Depot Feather Nest 3": 140,
  "GGM: Fuel Depot Front-Left Note": 141,
  "GGM: Fuel Depot Front-Right Note": 142,
  "GGM: Generator Cavern Egg Nest": 143,
  "GGM: Generator Cavern Jiggy": 144,
  "GGM: Generator Cavern Signpost": 145,
  "GGM: Gloomy Cavern Signpost": 146,
  "GGM: Gloomy Caverns Jail Cell Feather Nest": 147,
  "GGM: Gloomy Caverns Near Power Hut Egg Nest 1": 148,
  "GGM: Gloomy Caverns Near Power Hut Egg Nest 2": 149,
  "GGM: Gloomy Caverns Near Second Boulder Egg Nest": 150,
  "GGM: Hill by Crushing Shed Note 1": 151,
  "GGM: Hill by Crushing Shed Note 2": 152,
  "GGM: Hill by Crushing Shed Note 3": 153,
  "GGM: Hill by Crushing Shed Note 4": 154,
  "GGM: Inside Chuffy's Wagon Signpost": 155,
  "GGM: Inside Wumba's Wigwam Warp Pad Tagged": 156,
  "GGM: Jail Jinjo": 157,
  "GGM: Levitate Chuffy The Train": 158,
  "GGM: Mine Entrance 2 Glowbo": 159,
  "GGM: Mine Tracks Jinjo": 160,
  "GGM: Mumbo's Skull Feather Nest 1": 161,
  "GGM: Mumbo's Skull Feather Nest 2": 162,
  "GGM: Mumbo's Skull Feather Nest 3": 163,
  "GGM: Near Bill Drill Silo Egg Nest 1": 164,
  "GGM: Near Bill Drill Silo Egg Nest 2": 165,
  "GGM: Near Entrance Glowbo": 166,
  "GGM: Near Prospector's Hut Bottom-Left Note": 167,
  "GGM: Near Prospector's Hut Bottom-Right Note": 168,
  "GGM: Near Prospector's Hut Middle-Right Note": 169,
  "GGM: Near Prospector's Hut Top-Left Note": 170,
  "GGM: Near Prospector's Hut Top-Right Note": 171,
  "GGM: Near the Train Station Warp Pad Tagged": 172,
  "GGM: Old King Coal Jiggy": 173,
  "GGM: Old King Coal Mumbo Token": 174,
  "GGM: Ordnance Storage Jiggy": 175,
  "GGM: Ordnance Storage Lobby Egg Nest 1": 176,
  "GGM: Ordnance Storage Lobby Egg Nest 2": 177,
  "GGM: Ordnance Storage Lobby Egg Nest 3": 178,
  "GGM: Ordnance Storage Mumbo Token": 179,
  "GGM: Outside Mumbo's Skull Bottom-Right Note": 180,
  "GGM: Outside Mumbo's Skull Left Note": 181,
  "GGM: Outside Mumbo's Skull Top-Right Note": 182,
  "GGM: Outside Mumbo's Skull Warp Pad Tagged": 183,
  "GGM: Outside Ordnance Storage Egg Nest 1": 184,
  "GGM: Outside Ordnance Storage Egg Nest 2": 185,
  "GGM: Outside the Crushing Shed Warp Pad Tagged": 186,
  "GGM: Power Hut Basement Jiggy": 187,
  "GGM: Power Hut Feather Nest": 188,
  "GGM: Prospector Boulder Honeycomb": 189,
  "GGM: Prospector's Hut Egg Nest": 190,
  "GGM: Toxic Gas Cave Egg Nest": 191,
  "GGM: Toxic Gas Cave Feather Nest": 192,
  "GGM: Toxic Gas Cave Honeycomb": 193,
  "GGM: Toxic Gas Cave Jinjo": 194,
  "GGM: Toxic Gas Cave Signpost": 195,
  "GGM: Train Station Egg Nest 1": 196,
  "GGM: Train Station Egg Nest 2": 197,
  "GGM: Train Station Feather Nest 1": 198,
  "GGM: Train Station Feather Nest 2": 199,
  "GGM: Train Station Honeycomb": 200,
  "GGM: Treble Clef": 201,
  "GGM: Water Storage Cheato Page": 202,
  "GGM: Water Storage Jinjo": 203,
  "GGM: Water Storage Jinjo Tank Egg Nest": 204,
  "GGM: Waterfall Cavern Jiggy": 205,
  "GGM: Waterfall Jiggy": 206,
  "GGM: World Entry and Exit Warp Pad Tagged": 207,
  "GI Elevator Shaft: Floor 2 Egg Nest": 208,
  "GI Elevator Shaft: Floor 3 Egg Nest": 209,
  "GI Elevator Shaft: Floor 4 Egg Nest": 210,
  "GI Elevator Shaft: Signpost 1": 211,
  "GI Elevator Shaft: Signpost 2": 212,
  "GI Floor 1: Air Conditioning Plant In Front of Fan Feather Nest 1": 213,
  "GI Floor 1: Air Conditioning Plant In Front of Fan Feather Nest 2": 214,
  "GI Floor 1: Air Conditioning Plant Near Repair Depot Egg Nest 1": 215,
  "GI Floor 1: Air Conditioning Plant Near Repair Depot Egg Nest 2": 216,
  "GI Floor 1: Air Conditioning Plant Near Waste Disposal Egg Nest": 217,
  "GI Floor 1: Air Conditioning Plant Note 1": 218,
  "GI Floor 1: Air Conditioning Plant Note 2": 219,
  "GI Floor 1: Broke Loggo's Door": 220,
  "GI Floor 1: Claw Clamber Boots Silo": 221,
  "GI Floor 1: Cleaned Skivvy": 222,
  "GI Floor 1: Defeated Tintops": 223,
  "GI Floor 1: Entrance Door Warp Pad Tagged": 224,
  "GI Floor 1: Floor 1 on A/C Unit Note 1": 225,
  "GI Floor 1: Floor 1 on A/C Unit Note 2": 226,
  "GI Floor 1: Guarded Jiggy": 227,
  "GI Floor 1: High Pipe Egg Nest 1": 228,
  "GI Floor 1: High Pipe Egg Nest 2": 229,
  "GI Floor 1: Loggo Cheato Page": 230,
  "GI Floor 1: Near Waste Disposal Feather Nest 1": 231,
  "GI Floor 1: Near Waste Disposal Feather Nest 2": 232,
  "GI Floor 1: Opened Back Door": 233,
  "GI Floor 1: Opened Main Door": 234,
  "GI Floor 1: Opened Trash Compactor Jiggy Door": 235,
  "GI Floor 1: Opened Waste Disposal Plant": 236,
  "GI Floor 1: Repair Depot Cheato Page": 237,
  "GI Floor 1: Repair Depot Egg Nest 1": 238,
  "GI Floor 1: Repair Depot Egg Nest 2": 239,
  "GI Floor 1: Skivvy": 240,
  "GI Floor 1: Snooze Pack Silo": 241,
  "GI Floor 1: Top Pipe Egg Nest": 242,
  "GI Floor 1: Top of Trash Compactor Feather Nest": 243,
  "GI Floor 1: Train Station Big Box Egg Nest": 244,
  "GI Floor 1: Train Station Honeycomb": 245,
  "GI Floor 1: Train Station Medium Box Egg Nest": 246,
  "GI Floor 1: Train Station Note 1": 247,
  "GI Floor 1: Train Station Note 2": 248,
  "GI Floor 1: Train Station Note 3": 249,
  "GI Floor 1: Train Station Small Box Egg Nest": 250,
  "GI Floor 1: Trash Compactor Egg Nest 1": 251,
  "GI Floor 1: Trash Compactor Egg Nest 2": 252,
  "GI Floor 1: Trash Compactor Jiggy": 253,
  "GI Floor 1: Underwater Waste Disposal Plant Jiggy": 254,
  "GI Floor 1: Waste Disposal Jinjo Tank Egg Nest 1": 255,
  "GI Floor 1: Waste Disposal Jinjo Tank Egg Nest 2": 256,
  "GI Floor 1: Waste Disposal Plant Box Jiggy": 257,
  "GI Floor 1: Waste Disposal Plant Jinjo": 258,
  "GI Floor 1: Waste Disposal Plant Note 1": 259,
  "GI Floor 1: Waste Disposal Plant Note 2": 260,
  "GI Floor 1: Waste Disposal Water Pump Egg Nest": 261,
  "GI Floor 1: Waste Disposal Water Pump Feather Nest": 262,
  "GI Floor 1: Weldar Jiggy": 263,
  "GI Floor 1: Weldar Mumbo Token": 264,
  "GI Floor 1: Workers Quarters Signpost": 265,
  "GI Floor 1: Workers' Quarters Egg Nest": 266,
  "GI Floor 1: Workers' Quarters Feather Nest": 267,
  "GI Floor 2: Box Room Shorter Stack Note": 268,
  "GI Floor 2: Box Room Taller Stack Note": 269,
  "GI Floor 2: Broke Grate Near Electromagnet Chamber": 270,
  "GI Floor 2: Broke Grate Near Humba": 271,
  "GI Floor 2: Cleaned Skivvy": 272,
  "GI Floor 2: Delivered Battery Near Floor 3 Exit": 273,
  "GI Floor 2: Delivered Toxic Room Battery": 274,
  "GI Floor 2: EMP Electromagnet": 275,
  "GI Floor 2: Electromagnetic Chamber Egg Nest 1": 276,
  "GI Floor 2: Electromagnetic Chamber Egg Nest 2": 277,
  "GI Floor 2: Electromagnetic Chamber Feather Nest": 278,
  "GI Floor 2: Glowbo": 279,
  "GI Floor 2: In a Box Egg Nest 1": 280,
  "GI Floor 2: In a Box Egg Nest 2": 281,
  "GI Floor 2: Leg Spring Jinjo": 282,
  "GI Floor 2: Leg Spring Room Note 1": 283,
  "GI Floor 2: Leg Spring Room Note 2": 284,
  "GI Floor 2: Leg Spring Room Note 3": 285,
  "GI Floor 2: Leg Spring Silo": 286,
  "GI Floor 2: Near Cheato Page Feather Nest": 287,
  "GI Floor 2: Near Floor 1 Tunnel Egg Nest": 288,
  "GI Floor 2: Near Unscrewable Platform Feather Nest": 289,
  "GI Floor 2: On Scaffolding Egg Nest 1": 290,
  "GI Floor 2: On Scaffolding Egg Nest 2": 291,
  "GI Floor 2: On Scaffolding Egg Nest 3": 292,
  "GI Floor 2: On Scaffolding Egg Nest 4": 293,
  "GI Floor 2: On Scaffolding Egg Nest 5": 294,
  "GI Floor 2: Opened Catwalk Door": 295,
  "GI Floor 2: Opened Electromagnet Chamber": 296,
  "GI Floor 2: Opened Elevator Door": 297,
  "GI Floor 2: Opened Repair Depot": 298,
  "GI Floor 2: Outside Wumba's Wigwam Warp Pad Tagged": 299,
  "GI Floor 2: Skivvy": 300,
  "GI Floor 2: Unscrewed Plate": 301,
  "GI Floor 2: Window Cheato Page": 302,
  "GI Floor 3: Boiler Plant Jinjo": 303,
  "GI Floor 3: Boiler Plant Left Egg Nest": 304,
  "GI Floor 3: Boiler Plant Right Egg Nest": 305,
  "GI Floor 3: Cleaned Skivvy": 306,
  "GI Floor 3: Cleared Twinkly Packing": 307,
  "GI Floor 3: Delivered Battery": 308,
  "GI Floor 3: Glowbo": 309,
  "GI Floor 3: Honeycomb": 310,
  "GI Floor 3: Near Mumbo's Skull Egg Nest": 311,
  "GI Floor 3: Note 1": 312,
  "GI Floor 3: Note 2": 313,
  "GI Floor 3: On Boxes Feather Nest 1": 314,
  "GI Floor 3: On Boxes Feather Nest 2": 315,
  "GI Floor 3: On Crate Egg Nest": 316,
  "GI Floor 3: On High Box Stack Egg Nest": 317,
  "GI Floor 3: Opened Elevator Door": 318,
  "GI Floor 3: Opened Twinkly Packing Door": 319,
  "GI Floor 3: Outside Mumbo's Skull Warp Pad Tagged": 320,
  "GI Floor 3: Skivvy": 321,
  "GI Floor 3: Twinkly Packing Jiggy": 322,
  "GI Floor 3: Twinkly Packing Mumbo Token": 323,
  "GI Floor 3: Under Notes Egg Nest": 324,
  "GI Floor 3: Unscrewed Plate": 325,
  "GI Floor 4: Activated Flight Pads": 326,
  "GI Floor 4: Box Near Crushers Egg Nest": 327,
  "GI Floor 4: Cable Room": 328,
  "GI Floor 4: Cleared Clinker's Cavern": 329,
  "GI Floor 4: Clinker's Cavern Green Room Egg Nest 1": 330,
  "GI Floor 4: Clinker's Cavern Green Room Egg Nest 2": 331,
  "GI Floor 4: Clinker's Cavern Jiggy": 332,
  "GI Floor 4: Clinker's Cavern Mumbo Token": 333,
  "GI Floor 4: Clinker's Cavern Near Window Egg Nest": 334,
  "GI Floor 4: Clinker's Cavern Orange Room Egg Nest": 335,
  "GI Floor 4: Clinker's Cavern Raising Scaffolding Room Bottom Egg Nest": 336,
  "GI Floor 4: Clinker's Cavern Raising Scaffolding Room Top Egg Nest": 337,
  "GI Floor 4: Clinker's Cavern Spiral Scaffolding Room Egg Nest": 338,
  "GI Floor 4: Clinker's Cavern Valve Room Egg Nest": 339,
  "GI Floor 4: Disabled Crushers": 340,
  "GI Floor 4: EMP Wall Crushers": 341,
  "GI Floor 4: Near Battery Door Egg Nest": 342,
  "GI Floor 4: Near Fire Exit Egg Nest 1": 343,
  "GI Floor 4: Near Fire Exit Egg Nest 2": 344,
  "GI Floor 4: Near Fire Exit Egg Nest 3": 345,
  "GI Floor 4: Near Service Elevator Feather Nest 1": 346,
  "GI Floor 4: Near Service Elevator Feather Nest 2": 347,
  "GI Floor 4: Near the Crushers Warp Pad Tagged": 348,
  "GI Floor 4: Opened Cable Room Door": 349,
  "GI Floor 4: Opened Elevator Door": 350,
  "GI Floor 4: Pressed Quality Control Vent Button": 351,
  "GI Floor 4: Quality Control Egg Nest 1": 352,
  "GI Floor 4: Quality Control Egg Nest 2": 353,
  "GI Floor 4: Quality Control Egg Nest 3": 354,
  "GI Floor 4: Quality Control Jiggy": 355,
  "GI Floor 4: Quality Control Pit": 356,
  "GI Floor 4: Sewer Entrance Left Egg Nest 1": 357,
  "GI Floor 4: Sewer Entrance Left Egg Nest 2": 358,
  "GI Floor 4: Sewer Entrance Right Egg Nest 1": 359,
  "GI Floor 4: Sewer Entrance Right Egg Nest 2": 360,
  "GI Floor 4: Spawned Quality Control Jiggy": 361,
  "GI Floor 5: Big Box Stack Egg Nest": 362,
  "GI Floor 5: Box Egg Nest": 363,
  "GI Floor 5: Cleaned Skivvy": 364,
  "GI Floor 5: Jiggy": 365,
  "GI Floor 5: Jinjo": 366,
  "GI Floor 5: Skivvy": 367,
  "GI Floor 5: Small Box Stack Egg Nest": 368,
  "GI Floor 5: Unscrewed Plate": 369,
  "GI Outside: Atop Back Train Tunnel Feather Nest": 370,
  "GI Outside: Atop Front Train Tunnel Feather Nest": 371,
  "GI Outside: Broke Chimney": 372,
  "GI Outside: Broke Floor 1 Window": 373,
  "GI Outside: Broke Upper Middle Window": 374,
  "GI Outside: Broke Upper Side Window": 375,
  "GI Outside: Broke Window Above Front Train Tunnel": 376,
  "GI Outside: Broke Window Near Back Train Tunnel": 377,
  "GI Outside: Chimney Honeycomb": 378,
  "GI Outside: Cleaned Skivvy": 379,
  "GI Outside: Delivered Battery": 380,
  "GI Outside: Jinjo": 381,
  "GI Outside: On the Roof Outside Warp Pad Tagged": 382,
  "GI Outside: Roof Feather Nest 1": 383,
  "GI Outside: Roof Feather Nest 2": 384,
  "GI Outside: Roof Feather Nest 3": 385,
  "GI Outside: Signpost": 386,
  "GI Outside: Skivvy": 387,
  "GI Outside: Train Switch": 388,
  "GI Outside: Treble Clef": 389,
  "GI Worker's Quarters: Cleaned Skivvy": 390,
  "GI Worker's Quarters: Skivvy": 391,
  "GI: Defeated Weldar": 392,
  "GI: Mumbo Transform": 393,
  "GI: Skivvy Workers Jiggy": 394,
  "GI: Washer Transform": 395,
  "HFP: Aliens Jiggy": 396,
  "HFP: Alphette (Alien Kid Near Glowbo)": 397,
  "HFP: Betette (Alien Kid Near Dad)": 398,
  "HFP: Boggy Jiggy": 399,
  "HFP: Boggy's Igloo Note 1": 400,
  "HFP: Boggy's Igloo Note 2": 401,
  "HFP: Boiling Hot Pool Jinjo": 402,
  "HFP: Bottom Hot Pool Signpost": 403,
  "HFP: By Flight Pad Feather Nest 1": 404,
  "HFP: By Flight Pad Feather Nest 2": 405,
  "HFP: By Flight Pad Feather Nest 3": 406,
  "HFP: By Flight Pad Feather Nest 4": 407,
  "HFP: By Lava Side Train Switch Egg Nest": 408,
  "HFP: By Sabreman Egg Nest 1": 409,
  "HFP: By Sabreman Egg Nest 2": 410,
  "HFP: Chilli Billi Crater Egg Nest": 411,
  "HFP: Chilli Billi Mumbo Token": 412,
  "HFP: Chilly Willy Crater Egg Nest": 413,
  "HFP: Chilly Willy Mumbo Token": 414,
  "HFP: Colosseum Cheato Page": 415,
  "HFP: Colosseum Split-Up Jiggy": 416,
  "HFP: Dragon Brothers Jiggy": 417,
  "HFP: Fire Side - Lower Area (Mumbo) Warp Pad Tagged": 418,
  "HFP: Fire Side - Upper Area Warp Pad Tagged": 419,
  "HFP: Gamette (Alien Kid Above Split-Up Pads)": 420,
  "HFP: Glide Silo": 421,
  "HFP: Ice Side - Inside Icicle Grotto Warp Pad Tagged": 422,
  "HFP: Ice Side - Lower Area (Wumba) Warp Pad Tagged": 423,
  "HFP: Ice Side - Upper Area Warp Pad Tagged": 424,
  "HFP: Icicle Grotto Bottom Egg Nest 1": 425,
  "HFP: Icicle Grotto Bottom Egg Nest 2": 426,
  "HFP: Icicle Grotto Bottom Egg Nest 3": 427,
  "HFP: Icicle Grotto Cheato Page": 428,
  "HFP: Icicle Grotto Jinjo": 429,
  "HFP: Icicle Grotto Shock Spring Pad Egg Nest": 430,
  "HFP: Icicle Grotto Top Egg Nest 1": 431,
  "HFP: Icicle Grotto Top Egg Nest 2": 432,
  "HFP: Icy Side Glowbo": 433,
  "HFP: Icy Side Lower Warp Pad Egg Nest": 434,
  "HFP: Icy Side Pillar Cheato Page": 435,
  "HFP: Icy Side Station Jiggy": 436,
  "HFP: Icy Side Train Station Egg Nest": 437,
  "HFP: Icy Side Train Station Feather Nest": 438,
  "HFP: Icy Side Train Switch": 439,
  "HFP: Inside the Volcano Honeycomb": 440,
  "HFP: Inside the Volcano Jiggy": 441,
  "HFP: Kickball Colosseum Egg Nest 1": 442,
  "HFP: Kickball Colosseum Egg Nest 2": 443,
  "HFP: Kickball Colosseum Egg Nest 3": 444,
  "HFP: Kickball Colosseum Egg Nest 4": 445,
  "HFP: Kickball Colosseum Feather Nest 1": 446,
  "HFP: Kickball Colosseum Feather Nest 2": 447,
  "HFP: Kickball Jiggy": 448,
  "HFP: Kickball Mumbo Token": 449,
  "HFP: Lava Side Glowbo": 450,
  "HFP: Lava Side Honeycomb": 451,
  "HFP: Lava Side Lower Warp Pad Egg Nest 1": 452,
  "HFP: Lava Side Lower Warp Pad Egg Nest 2": 453,
  "HFP: Lava Side Train Station Egg Nest 1": 454,
  "HFP: Lava Side Train Station Egg Nest 2": 455,
  "HFP: Lava Side Train Switch": 456,
  "HFP: Lava Side: Near Ladder Note 1": 457,
  "HFP: Lava Side: Near Ladder Note 2": 458,
  "HFP: Lava Side: Top Path Note 1": 459,
  "HFP: Lava Side: Top Path Note 2": 460,
  "HFP: Lava Waterfall Jinjo": 461,
  "HFP: Lower Icy Side Warp Pad Note 1": 462,
  "HFP: Lower Icy Side Warp Pad Note 2": 463,
  "HFP: Mega Glowbo": 464,
  "HFP: Mildred Ice Cube Jinjo": 465,
  "HFP: Mumbo's Skull Feather Nest 1": 466,
  "HFP: Mumbo's Skull Feather Nest 2": 467,
  "HFP: Near Bottom Icicle Grotto Entrance Feather Nest 1": 468,
  "HFP: Near Bottom Icicle Grotto Entrance Feather Nest 2": 469,
  "HFP: Near Icy Side Pillar Egg Nest 1": 470,
  "HFP: Near Icy Side Pillar Egg Nest 2": 471,
  "HFP: Near Top Hot Pool Egg Nest 1": 472,
  "HFP: Near Top Hot Pool Egg Nest 2": 473,
  "HFP: Oil Drill Jiggy": 474,
  "HFP: Oil Drill Note 1": 475,
  "HFP: Oil Drill Note 2": 476,
  "HFP: On Shelter Near Entrance Feather Nest": 477,
  "HFP: Path to Mumbo's Skull Note 1": 478,
  "HFP: Path to Mumbo's Skull Note 2": 479,
  "HFP: Path to Shack Pack Note 1": 480,
  "HFP: Path to Shack Pack Note 2": 481,
  "HFP: Sabreman Jiggy": 482,
  "HFP: Sabreman Tent Egg Nest": 483,
  "HFP: Shack Pack Silo": 484,
  "HFP: Stomping Plains Jiggy": 485,
  "HFP: Top Hot Pool Signpost": 486,
  "HFP: Train Station Honeycomb": 487,
  "HFP: Treble Clef": 488,
  "HFP: Upper Icy Side Warp Pad Note 1": 489,
  "HFP: Upper Icy Side Warp Pad Note 2": 490,
  "HFP: Volcano Signpost 1": 491,
  "HFP: Volcano Signpost 2": 492,
  "HFP: Volcano Signpost 3": 493,
  "HFP: Windy Hole Jinjo": 494,
  "HFP: Wumba's Wigwam Feather Nest 1": 495,
  "HFP: Wumba's Wigwam Feather Nest 2": 496,
  "IoH Dragon Transform": 497,
  "IoH: Amaze-O-Gaze Goggles": 498,
  "IoH: Another Digger Tunnel Egg Nest 1": 499,
  "IoH: Another Digger Tunnel Egg Nest 2": 500,
  "IoH: Behind Jiggywiggy's Temple Signpost 1": 501,
  "IoH: Behind Jiggywiggy's Temple Signpost 2": 502,
  "IoH: Behind Jiggywiggy's Temple Signpost 3": 503,
  "IoH: Black Jinjo Family Jiggy": 504,
  "IoH: Black Jinjo Family Mumbo Token": 505,
  "IoH: Blue Jinjo Family Jiggy": 506,
  "IoH: Blue Jinjo Family Mumbo Token": 507,
  "IoH: Blue Mystery Egg Hatched": 508,
  "IoH: Bottles' House Egg Nest 1": 509,
  "IoH: Bottles' House Egg Nest 2": 510,
  "IoH: Bottles' House Feather Nest 1": 511,
  "IoH: Bottles' House Feather Nest 2": 512,
  "IoH: Brown Jinjo Family Jiggy": 513,
  "IoH: Brown Jinjo Family Mumbo Token": 514,
  "IoH: Cliff Top Feather Nest 1": 515,
  "IoH: Cliff Top Feather Nest 2": 516,
  "IoH: Cliff Top Feather Nest 3": 517,
  "IoH: Cliff Top Feather Nest 4": 518,
  "IoH: Cliff Top Glowbo": 519,
  "IoH: Cliff Top Jinjo": 520,
  "IoH: Cliff Top Near JRL Egg Nest": 521,
  "IoH: Cliff Top Near Path to Plateau Egg Nest 1": 522,
  "IoH: Cliff Top Near Path to Plateau Egg Nest 2": 523,
  "IoH: Cliff Top Signpost": 524,
  "IoH: Cliff Top Silo Tagged": 525,
  "IoH: Clockwork Kazooie Eggs Silo": 526,
  "IoH: Clockwork Silo Bottom Note": 527,
  "IoH: Clockwork Silo Top Note": 528,
  "IoH: Fire Eggs Silo": 529,
  "IoH: Green Jinjo Family Jiggy": 530,
  "IoH: Green Jinjo Family Mumbo Token": 531,
  "IoH: Grenade Eggs Silo": 532,
  "IoH: Grey Jinjo Family House Signpost": 533,
  "IoH: Honey B's Reward 1": 534,
  "IoH: Honey B's Reward 2": 535,
  "IoH: Honey B's Reward 3": 536,
  "IoH: Honey B's Reward 4": 537,
  "IoH: Honey B's Reward 5": 538,
  "IoH: Ice Eggs Silo": 539,
  "IoH: Ice Key": 540,
  "IoH: Inside the Digger Tunnel Egg Nest": 541,
  "IoH: Jiggywiggy's Temple Signpost 1": 542,
  "IoH: Jiggywiggy's Temple Signpost 2": 543,
  "IoH: Jiggywiggy's Temple Signpost 3": 544,
  "IoH: Jiggywiggy's Temple Signpost 4": 545,
  "IoH: Jiggywiggy's Temple Signpost 5": 546,
  "IoH: Jiggywiggy's Temple Signpost 6": 547,
  "IoH: Jiggywiggy's Temple Signpost 7": 548,
  "IoH: Jiggywiggy's Temple Signpost 8": 549,
  "IoH: Jinjo Village By Silo Egg Nest 1": 550,
  "IoH: Jinjo Village By Silo Egg Nest 2": 551,
  "IoH: Jinjo Village By Silo Feather Nest 1": 552,
  "IoH: Jinjo Village By Silo Feather Nest 2": 553,
  "IoH: Jinjo Village Near Shortcut Egg Nest 1": 554,
  "IoH: Jinjo Village Near Shortcut Egg Nest 2": 555,
  "IoH: Jinjo Village Outside Bottle's House Feather Nest 1": 556,
  "IoH: Jinjo Village Outside Bottle's House Feather Nest 2": 557,
  "IoH: Jinjo Village Silo Tagged": 558,
  "IoH: Jinjo Village Top Row of Houses Egg Nest 1": 559,
  "IoH: Jinjo Village Top Row of Houses Egg Nest 2": 560,
  "IoH: Jinjo Village Top Row of Houses Feather Nest 1": 561,
  "IoH: Jinjo Village Top Row of Houses Feather Nest 2": 562,
  "IoH: King Jingaling Jiggy": 563,
  "IoH: Orange Jinjo Family Jiggy": 564,
  "IoH: Orange Jinjo Family Mumbo Token": 565,
  "IoH: Outside HFP Note 1": 566,
  "IoH: Outside HFP Note 2": 567,
  "IoH: Outside HFP Note 3": 568,
  "IoH: Outside HFP Note 4": 569,
  "IoH: Outside Heggy's Egg Shed Signpost": 570,
  "IoH: Pine Grove Egg Nest 1": 571,
  "IoH: Pine Grove Egg Nest 2": 572,
  "IoH: Pine Grove Egg Nest 3": 573,
  "IoH: Pine Grove Feather Nest 1": 574,
  "IoH: Pine Grove Feather Nest 2": 575,
  "IoH: Pine Grove Feather Nest 3": 576,
  "IoH: Pine Grove Note 1": 577,
  "IoH: Pine Grove Note 2": 578,
  "IoH: Pine Grove Signpost 1": 579,
  "IoH: Pine Grove Signpost 2": 580,
  "IoH: Pine Grove Signpost 3": 581,
  "IoH: Pine Grove Silo Tagged": 582,
  "IoH: Pine Grove Underwater Note 1": 583,
  "IoH: Pine Grove Underwater Note 2": 584,
  "IoH: Pink Mystery Egg Hatched": 585,
  "IoH: Plateau Dirt Pile Feather Nest 1": 586,
  "IoH: Plateau Dirt Pile Feather Nest 2": 587,
  "IoH: Plateau GGM Sign Note 1": 588,
  "IoH: Plateau GGM Sign Note 2": 589,
  "IoH: Plateau Honey B. Note 1": 590,
  "IoH: Plateau Honey B. Note 2": 591,
  "IoH: Plateau Honeycomb": 592,
  "IoH: Plateau Jinjo": 593,
  "IoH: Plateau Near Cliff Top Entrance Feather Nest": 594,
  "IoH: Plateau Near GGM Entrance Egg Nest 1": 595,
  "IoH: Plateau Near GGM Entrance Egg Nest 2": 596,
  "IoH: Plateau Near GGM Entrance Egg Nest 3": 597,
  "IoH: Plateau Near GGM Entrance Egg Nest 4": 598,
  "IoH: Plateau Silo Tagged": 599,
  "IoH: Purple Jinjo Family Jiggy": 600,
  "IoH: Purple Jinjo Family Mumbo Token": 601,
  "IoH: Quagmire Back Feather Nest": 602,
  "IoH: Quagmire Egg Nest 1": 603,
  "IoH: Quagmire Egg Nest 2": 604,
  "IoH: Quagmire Egg Nest 3": 605,
  "IoH: Quagmire High Feather Nest": 606,
  "IoH: Quagmire Left Feather Nest": 607,
  "IoH: Quagmire Silo Tagged": 608,
  "IoH: Red Jinjo Family Jiggy": 609,
  "IoH: Red Jinjo Family Mumbo Token": 610,
  "IoH: Train Switch": 611,
  "IoH: Treble Clef": 612,
  "IoH: Wasteland Behind CCL Bubble Feather Nest": 613,
  "IoH: Wasteland CCL Area Note 1": 614,
  "IoH: Wasteland CCL Area Note 2": 615,
  "IoH: Wasteland Jinjo": 616,
  "IoH: Wasteland Near Crevice to CCL Feather Nest": 617,
  "IoH: Wasteland Near Digger Tunnel Egg Nest 1": 618,
  "IoH: Wasteland Near Digger Tunnel Egg Nest 2": 619,
  "IoH: Wasteland Near Digger Tunnel Egg Nest 3": 620,
  "IoH: Wasteland Next to Quagmire Entrance Feather Nest": 621,
  "IoH: Wasteland Signpost": 622,
  "IoH: Wasteland Silo Tagged": 623,
  "IoH: Wasteland TDL Entrance Feather Nest 1": 624,
  "IoH: Wasteland TDL Entrance Feather Nest 2": 625,
  "IoH: White Jinjo Family Jiggy": 626,
  "IoH: White Jinjo Family Mumbo Token": 627,
  "IoH: Wooded Hollow Jiggywiggy Challenge 1": 628,
  "IoH: Wooded Hollow Jiggywiggy Challenge 10": 629,
  "IoH: Wooded Hollow Jiggywiggy Challenge 2": 630,
  "IoH: Wooded Hollow Jiggywiggy Challenge 3": 631,
  "IoH: Wooded Hollow Jiggywiggy Challenge 4": 632,
  "IoH: Wooded Hollow Jiggywiggy Challenge 5": 633,
  "IoH: Wooded Hollow Jiggywiggy Challenge 6": 634,
  "IoH: Wooded Hollow Jiggywiggy Challenge 7": 635,
  "IoH: Wooded Hollow Jiggywiggy Challenge 8": 636,
  "IoH: Wooded Hollow Jiggywiggy Challenge 9": 637,
  "IoH: Wooded Hollow Jiggywiggy's Super Special Challenge": 638,
  "IoH: Wooded Hollow Jinjo": 639,
  "IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 1": 640,
  "IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 2": 641,
  "IoH: Wooded Hollow Left of Jiggywiggy's Temple Feather Nest 3": 642,
  "IoH: Wooded Hollow Outside Bottles' House Feather Nest 1": 643,
  "IoH: Wooded Hollow Outside Bottles' House Feather Nest 2": 644,
  "IoH: Wooded Hollow Outside Heggy's Egg Shed Egg Nest 1": 645,
  "IoH: Wooded Hollow Outside Heggy's Egg Shed Egg Nest 2": 646,
  "IoH: Wooded Hollow Path to Plateau Signpost": 647,
  "IoH: Wooded Hollow Right of Jiggywiggy's Temple Egg Nest 1": 648,
  "IoH: Wooded Hollow Right of Jiggywiggy's Temple Egg Nest 2": 649,
  "IoH: Wooded Hollow Silo Tagged": 650,
  "IoH: Wumba's Wigwam Egg Nest 1": 651,
  "IoH: Wumba's Wigwam Egg Nest 2": 652,
  "IoH: Yellow Jinjo Family Jiggy": 653,
  "IoH: Yellow Jinjo Family Mumbo Token": 654,
  "IoH: Yellow Mystery Egg Hatched": 655,
  "JRL: Alcove Doubloon 1": 656,
  "JRL: Alcove Doubloon 2": 657,
  "JRL: Alcove Doubloon 3": 658,
  "JRL: Ancient Swimming Baths Cheato Page": 659,
  "JRL: Atlantis Egg Nest 1": 660,
  "JRL: Atlantis Egg Nest 2": 661,
  "JRL: Atlantis Egg Nest 3": 662,
  "JRL: Atlantis Honeycomb": 663,
  "JRL: Atlantis Seemee Fish Egg Nest": 664,
  "JRL: Atlantis Warp Pad Tagged": 665,
  "JRL: Big Fish Cavern Warp Pad Tagged": 666,
  "JRL: Big Fish Jinjo": 667,
  "JRL: Blubber Jinjo": 668,
  "JRL: Blubber's Hire Note 1": 669,
  "JRL: Blubber's Hire Note 2": 670,
  "JRL: Blubber's Hire Note 3": 671,
  "JRL: Blubber's Signpost": 672,
  "JRL: Blubbul Note 1": 673,
  "JRL: Blubbul Note 2": 674,
  "JRL: Captain Blackeye Doubloon 1": 675,
  "JRL: Captain Blackeye Doubloon 2": 676,
  "JRL: Chris P. Bacon Jiggy": 677,
  "JRL: Davie Jones Locker Egg Nest 1": 678,
  "JRL: Davie Jones Locker Egg Nest 2": 679,
  "JRL: Davie Jones Locker Egg Nest 3": 680,
  "JRL: Davie Jones Locker Egg Nest 4": 681,
  "JRL: Electric Eel's Lair Entrance Note 1": 682,
  "JRL: Electric Eel's Lair Entrance Note 2": 683,
  "JRL: Inside the Big Fish Feather Nest 1": 684,
  "JRL: Inside the Big Fish Feather Nest 2": 685,
  "JRL: Jolly's Gunpowder Feather Nest 1": 686,
  "JRL: Jolly's Gunpowder Feather Nest 2": 687,
  "JRL: Jolly's Near Blackeye Egg Nest 1": 688,
  "JRL: Jolly's Near Blackeye Egg Nest 2": 689,
  "JRL: Jolly's Near Sub-Aqua Egg Aiming Silo Feather Nest 1": 690,
  "JRL: Jolly's Near Sub-Aqua Egg Aiming Silo Feather Nest 2": 691,
  "JRL: Jolly's Note 1": 692,
  "JRL: Jolly's Note 2": 693,
  "JRL: Jolly's Note 3": 694,
  "JRL: Lagoon Alcove Jinjo": 695,
  "JRL: Lockers Cavern Warp Pad Tagged": 696,
  "JRL: Lockers Egg Nest 1": 697,
  "JRL: Lockers Egg Nest 2": 698,
  "JRL: Lockers Egg Nest 3": 699,
  "JRL: Merry Maggie Jiggy": 700,
  "JRL: Mini-Sub Challenge Jiggy": 701,
  "JRL: Mini-Sub Challenge Mumbo Token": 702,
  "JRL: Mumbo Skull Doubloon 1": 703,
  "JRL: Mumbo Skull Doubloon 2": 704,
  "JRL: Mumbo Skull Doubloon 3": 705,
  "JRL: Mumbo Skull Doubloon 4": 706,
  "JRL: Near Alcove Jinjo Doubloon 1": 707,
  "JRL: Near Alcove Jinjo Doubloon 2": 708,
  "JRL: Near Alcove Jinjo Doubloon 3": 709,
  "JRL: Near Alcove Jinjo Doubloon 4": 710,
  "JRL: Near Big Fish Warp Pad Egg Nest 1": 711,
  "JRL: Near Big Fish Warp Pad Egg Nest 2": 712,
  "JRL: Outside Blubber's Note": 713,
  "JRL: Outside Jolly's Note": 714,
  "JRL: Outside Pawno's Note": 715,
  "JRL: Pawno Cheato Page": 716,
  "JRL: Pawno Jiggy": 717,
  "JRL: Pawno's Emporium Egg Nest 1": 718,
  "JRL: Pawno's Emporium Egg Nest 2": 719,
  "JRL: Pawno's Emporium Egg Nest 3": 720,
  "JRL: Pawno's Emporium Glowbo": 721,
  "JRL: Pawno's Emporium Note 1": 722,
  "JRL: Pawno's Emporium Note 2": 723,
  "JRL: Pawno's Emporium Note 3": 724,
  "JRL: Pig Pool Jiggy": 725,
  "JRL: Sea Bottom Seemee Fish Egg Nest": 726,
  "JRL: Sea Bottom Seemee Fish Feather Nest": 727,
  "JRL: Seaweed Sanctum Bottom Floor Feather Nest": 728,
  "JRL: Seaweed Sanctum Jinjo": 729,
  "JRL: Seaweed Sanctum Second Floor Egg Nest 1": 730,
  "JRL: Seaweed Sanctum Second Floor Egg Nest 2": 731,
  "JRL: Seaweed Sanctum Signpost": 732,
  "JRL: Seaweed Sanctum Top Floor Feather Nest": 733,
  "JRL: Seemee Cheato Page": 734,
  "JRL: Seemee Honeycomb": 735,
  "JRL: Seemee Jiggy": 736,
  "JRL: Silo Doubloon 1": 737,
  "JRL: Silo Doubloon 2": 738,
  "JRL: Silo Doubloon 3": 739,
  "JRL: Silo Doubloon 4": 740,
  "JRL: Smuggler's Cavern Egg Nest 1": 741,
  "JRL: Smuggler's Cavern Egg Nest 2": 742,
  "JRL: Smuggler's Cavern Jiggy": 743,
  "JRL: Smuggler's Cavern Signpost": 744,
  "JRL: Sub-Aqua Egg Aiming Silo": 745,
  "JRL: Sunken Ship Egg Nest 1": 746,
  "JRL: Sunken Ship Egg Nest 2": 747,
  "JRL: Sunken Ship Jinjo": 748,
  "JRL: Sunken Ship Warp Pad Tagged": 749,
  "JRL: Talon Torpedo Silo": 750,
  "JRL: Temple of the Fishes Egg Nest 1": 751,
  "JRL: Temple of the Fishes Egg Nest 2": 752,
  "JRL: Temple of the Fishes Egg Nest 3": 753,
  "JRL: Temple of the Fishes Egg Nest 4": 754,
  "JRL: Tiptup Jiggy": 755,
  "JRL: Town Center Blubbul Egg Nest": 756,
  "JRL: Town Center Pole Doubloon 1": 757,
  "JRL: Town Center Pole Doubloon 2": 758,
  "JRL: Town Center Pole Doubloon 3": 759,
  "JRL: Town Center Pole Doubloon 4": 760,
  "JRL: Town Center Pole Doubloon 5": 761,
  "JRL: Town Center Pole Doubloon 6": 762,
  "JRL: Town Center Warp Pad Tagged": 763,
  "JRL: Toxic Pool Doubloon 1": 764,
  "JRL: Toxic Pool Doubloon 2": 765,
  "JRL: Toxic Pool Doubloon 3": 766,
  "JRL: Toxic Pool Doubloon 4": 767,
  "JRL: Treble Clef": 768,
  "JRL: UFO Jiggy": 769,
  "JRL: Under Wumba's Wigwam Glowbo": 770,
  "JRL: Underground Doubloon 1": 771,
  "JRL: Underground Doubloon 2": 772,
  "JRL: Underground Doubloon 3": 773,
  "JRL: Waste Pipe Alcove Signpost": 774,
  "JRL: Waste Pipe Honeycomb": 775,
  "JRL: Wing Whack Silo": 776,
  "JRL: Woo Fak Fak Jiggy": 777,
  "JRL: Woo Fak Fak Mumbo Token": 778,
  "JRL: Wumba's Wigwam Feather Nest": 779,
  "MT: Bovina Egg Nest 1": 780,
  "MT: Bovina Egg Nest 2": 781,
  "MT: Bovina Honeycomb": 782,
  "MT: Bovina Jiggy": 783,
  "MT: Breegull Blaster Silo": 784,
  "MT: Bridge Jinjo": 785,
  "MT: Egg Aim Silo": 786,
  "MT: Entrance Honeycomb": 787,
  "MT: First Stairs Note 1": 788,
  "MT: First Stairs Note 2": 789,
  "MT: First Stairs Note 3": 790,
  "MT: First Stairs Note 4": 791,
  "MT: Golden Goliath Jiggy": 792,
  "MT: Golden Goliath Signpost": 793,
  "MT: Grip Grab Silo": 794,
  "MT: In Front of Jade Snake Grove Feather Nest 1": 795,
  "MT: In Front of Jade Snake Grove Feather Nest 2": 796,
  "MT: In Front of Prison Compound Egg Nest 1": 797,
  "MT: In Front of Prison Compound Egg Nest 2": 798,
  "MT: Jade Snake Grove Above Code Chamber Egg Nest": 799,
  "MT: Jade Snake Grove Cheato Page": 800,
  "MT: Jade Snake Grove Glowbo": 801,
  "MT: Jade Snake Grove Jinjo": 802,
  "MT: Jade Snake Grove Near Warp Pad Egg Nest 1": 803,
  "MT: Jade Snake Grove Near Warp Pad Egg Nest 2": 804,
  "MT: Jade Snake Grove Quicksand Signpost 1": 805,
  "MT: Jade Snake Grove Quicksand Signpost 2": 806,
  "MT: Kickball Jiggy": 807,
  "MT: Kickball Mumbo Token": 808,
  "MT: Kickball Stadium Feather Nest 1": 809,
  "MT: Kickball Stadium Feather Nest 2": 810,
  "MT: Kickball Stadium Lobby Warp Pad Tagged": 811,
  "MT: Left of Code Chamber Signpost": 812,
  "MT: Mumbo's Glowbo": 813,
  "MT: Mumbo's Skull Egg Nest 1": 814,
  "MT: Mumbo's Skull Egg Nest 2": 815,
  "MT: Mumbo's Skull Signpost": 816,
  "MT: Near Wumba's Wigwam Warp Pad Tagged": 817,
  "MT: Outside Mumbo's Skull Note": 818,
  "MT: Outside Mumbo's Skull Warp Pad Tagged": 819,
  "MT: Outside Treasure Chamber Egg Nest 1": 820,
  "MT: Outside Treasure Chamber Egg Nest 2": 821,
  "MT: Pillars Jiggy": 822,
  "MT: Pillars Signpost": 823,
  "MT: Prison Compound Cheato Page": 824,
  "MT: Prison Compound Entrance Egg Nest 1": 825,
  "MT: Prison Compound Entrance Egg Nest 2": 826,
  "MT: Prison Compound Pillars Egg Nest 1": 827,
  "MT: Prison Compound Pillars Egg Nest 2": 828,
  "MT: Prison Compound Pillars Egg Nest 3": 829,
  "MT: Prison Compound Quicksand Jiggy": 830,
  "MT: Prison Compound Quicksand Signpost": 831,
  "MT: Prison Compound Top of Prison Cell Feather Left Nest": 832,
  "MT: Prison Compound Top of Prison Cell Feather Right Nest": 833,
  "MT: Prison Compound Warp Pad Tagged": 834,
  "MT: Second Stairs Note 1": 835,
  "MT: Second Stairs Note 2": 836,
  "MT: Second Stairs Note 3": 837,
  "MT: Second Stairs Note 4": 838,
  "MT: Slightly Sacred Chamber Jiggy": 839,
  "MT: Ssslumber Jiggy": 840,
  "MT: Stadium Jinjo": 841,
  "MT: Targitzan Jiggy": 842,
  "MT: Targitzan Mumbo Token": 843,
  "MT: Targitzan Temple Jinjo": 844,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 1": 845,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 2": 846,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 3": 847,
  "MT: Targitzan's Temple 4-Way Room Egg Nest 4": 848,
  "MT: Targitzan's Temple Blue Pillar Room Relic 1": 849,
  "MT: Targitzan's Temple Blue Pillar Room Relic 2": 850,
  "MT: Targitzan's Temple Blue Pillar Room Relic 3": 851,
  "MT: Targitzan's Temple Golden Egg Nest": 852,
  "MT: Targitzan's Temple Green Pillar Room Relic 1": 853,
  "MT: Targitzan's Temple Green Pillar Room Relic 2": 854,
  "MT: Targitzan's Temple Green Pillar Room Relic 3": 855,
  "MT: Targitzan's Temple Green Pillar Room Relic 4": 856,
  "MT: Targitzan's Temple Green Pillar Room Relic 5": 857,
  "MT: Targitzan's Temple Left Entrance Relic": 858,
  "MT: Targitzan's Temple Lobby Left Egg Nest 1": 859,
  "MT: Targitzan's Temple Lobby Left Egg Nest 2": 860,
  "MT: Targitzan's Temple Lobby Left Egg Nest 3": 861,
  "MT: Targitzan's Temple Lobby Right Egg Nest 1": 862,
  "MT: Targitzan's Temple Lobby Right Egg Nest 2": 863,
  "MT: Targitzan's Temple Lobby Right Egg Nest 3": 864,
  "MT: Targitzan's Temple Near Sacred Chambers Relic 1": 865,
  "MT: Targitzan's Temple Near Sacred Chambers Relic 2": 866,
  "MT: Targitzan's Temple Near Sput Sput Relic 1": 867,
  "MT: Targitzan's Temple Near Sput Sput Relic 2": 868,
  "MT: Targitzan's Temple Near Sput Sput Relic 3": 869,
  "MT: Targitzan's Temple Near Sput Sput Relic 4": 870,
  "MT: Targitzan's Temple Near Sput Sput Relic 5": 871,
  "MT: Targitzan's Temple Pillar Maze Egg Nest 1": 872,
  "MT: Targitzan's Temple Pillar Maze Egg Nest 2": 873,
  "MT: Targitzan's Temple Pillar Maze Egg Nest 3": 874,
  "MT: Targitzan's Temple Raising Slope Room Egg Nest 1": 875,
  "MT: Targitzan's Temple Raising Slope Room Egg Nest 2": 876,
  "MT: Targitzan's Temple Raising Slope Room Egg Nest 3": 877,
  "MT: Targitzan's Temple Red Pillar Room Relic 1": 878,
  "MT: Targitzan's Temple Red Pillar Room Relic 2": 879,
  "MT: Targitzan's Temple Red Pillar Room Relic 3": 880,
  "MT: Targitzan's Temple Right Entrance Relic": 881,
  "MT: Targitzan's Temple Secret Passage Near Entrance Relic 1": 882,
  "MT: Targitzan's Temple Secret Passage Near Entrance Relic 2": 883,
  "MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 1": 884,
  "MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 2": 885,
  "MT: Targitzan's Temple Secret Passage Near Sacred Chambers Relic 3": 886,
  "MT: Targitzan's Temple Signpost 1": 887,
  "MT: Targitzan's Temple Signpost 2": 888,
  "MT: Third Stairs Note 1": 889,
  "MT: Third Stairs Note 2": 890,
  "MT: Third Stairs Note 3": 891,
  "MT: Third Stairs Note 4": 892,
  "MT: Top Stairs Note 1": 893,
  "MT: Top Stairs Note 2": 894,
  "MT: Top Stairs Note 3": 895,
  "MT: Top of Temple Jiggy": 896,
  "MT: Treasure Chamber Cheato Page": 897,
  "MT: Treasure Chamber Honeycomb": 898,
  "MT: Treasure Chamber Jiggy": 899,
  "MT: Treble Clef": 900,
  "MT: Water Pool Jinjo": 901,
  "MT: World Entry and Exit Warp Pad Tagged": 902,
  "MT: Wumba's Wigwam Feather Nest 1": 903,
  "MT: Wumba's Wigwam Feather Nest 2": 904,
  "Party At Bottles'": 905,
  "SM: Attack Tutorial Field Feather Nest 1": 906,
  "SM: Attack Tutorial Field Feather Nest 2": 907,
  "SM: Attack Tutorial Field Feather Nest 3": 908,
  "SM: Base of Spiral Mountain Feather Nest 1": 909,
  "SM: Base of Spiral Mountain Feather Nest 2": 910,
  "SM: Base of Spiral Mountain Feather Nest 3": 911,
  "SM: Blue Mystery Egg": 912,
  "SM: Bottom of Attack Tutorial Field Egg Nest 1": 913,
  "SM: Bottom of Attack Tutorial Field Egg Nest 2": 914,
  "SM: Bottom of Attack Tutorial Field Egg Nest 3": 915,
  "SM: Cheato Page": 916,
  "SM: Cheato Reward 1": 917,
  "SM: Cheato Reward 2": 918,
  "SM: Cheato Reward 3": 919,
  "SM: Cheato Reward 4": 920,
  "SM: Cheato Reward 5": 921,
  "SM: Gruntilda's Lair Egg Nest 1": 922,
  "SM: Gruntilda's Lair Egg Nest 2": 923,
  "SM: Gruntilda's Lair Egg Nest 3": 924,
  "SM: Gruntilda's Lair Egg Nest 4": 925,
  "SM: Gruntilda's Lair Feather Nest 1": 926,
  "SM: Gruntilda's Lair Feather Nest 2": 927,
  "SM: Gruntilda's Lair Feather Nest 3": 928,
  "SM: Jinjo": 929,
  "SM: Near Digger Tunnel Feather Nest 1": 930,
  "SM: Near Digger Tunnel Feather Nest 2": 931,
  "SM: Near Digger Tunnel Feather Nest 3": 932,
  "SM: Pink Mystery Egg": 933,
  "SM: Platform Left of Waterfall Feather Nest 1": 934,
  "SM: Platform Left of Waterfall Feather Nest 2": 935,
  "SM: Roysten Reward 1": 936,
  "SM: Roysten Reward 2": 937,
  "SM: Spiral Mountain Feather Nest 1": 938,
  "SM: Spiral Mountain Feather Nest 2": 939,
  "SM: Spiral Mountain Feather Nest 3": 940,
  "SM: Top-Right of Waterfall Feather Nest": 941,
  "TDL: Alcove Near Waterfall Egg Nest 1": 942,
  "TDL: Alcove Near Waterfall Egg Nest 2": 943,
  "TDL: Baby T-Rex Roar": 944,
  "TDL: Behind Mumbo's Skull Glowbo": 945,
  "TDL: Beside Rocknut Jinjo": 946,
  "TDL: Big T. Rex Jinjo": 947,
  "TDL: Bonfire Cavern Entrance Feather Nest": 948,
  "TDL: Bonfire Cavern Exit Feather Nest": 949,
  "TDL: Boulder Cheato Page": 950,
  "TDL: Chompas Belly Jiggy": 951,
  "TDL: Chompas Belly Mumbo Token": 952,
  "TDL: Code of the Dinosaurs Jiggy": 953,
  "TDL: Dippy Jiggy": 954,
  "TDL: Dippy's Pool Cheato Page": 955,
  "TDL: Entrance Egg Nest": 956,
  "TDL: Entrance Jinjo": 957,
  "TDL: Flight Pad Pillar Feather Nest 1": 958,
  "TDL: Flight Pad Pillar Feather Nest 2": 959,
  "TDL: Flight Pad Pillar Feather Nest 3": 960,
  "TDL: Hatch Silo": 961,
  "TDL: Inside The Mountain Near Cheato Page Signpost": 962,
  "TDL: Inside The Mountain Near Top Signpost": 963,
  "TDL: Inside the Mountain Cheato Page": 964,
  "TDL: Inside the Mountain Egg Nest 1": 965,
  "TDL: Inside the Mountain Egg Nest 2": 966,
  "TDL: Inside the Mountain Feather Nest 1": 967,
  "TDL: Inside the Mountain Feather Nest 2": 968,
  "TDL: Lakeside Honeycomb": 969,
  "TDL: Lakeside Note 1": 970,
  "TDL: Lakeside Note 2": 971,
  "TDL: Lakeside Note 3": 972,
  "TDL: Left of Wall with Holes Egg Nest 1": 973,
  "TDL: Left of Wall with Holes Egg Nest 2": 974,
  "TDL: Mumbo's Skull Feather Nest 1": 975,
  "TDL: Mumbo's Skull Feather Nest 2": 976,
  "TDL: Near River Passage Entrance Egg Nest": 977,
  "TDL: Near Shock Spring Pad Up the Mountain Egg Nest 1": 978,
  "TDL: Near Shock Spring Pad Up the Mountain Egg Nest 2": 979,
  "TDL: Oogle Boogle Egg Nest 1": 980,
  "TDL: Oogle Boogle Egg Nest 2": 981,
  "TDL: Oogle Boogle Feather Nest 1": 982,
  "TDL: Oogle Boogle Feather Nest 2": 983,
  "TDL: Oogle Boogle Tribe Jiggy": 984,
  "TDL: Outside Mumbo's Skull Warp Pad Tagged": 985,
  "TDL: Outside Wumba's Wigwam Warp Pad Tagged": 986,
  "TDL: Path to Terry Egg Nest 1": 987,
  "TDL: Path to Terry Egg Nest 2": 988,
  "TDL: Path to Terry Feather Nest 1": 989,
  "TDL: Path to Terry Feather Nest 2": 990,
  "TDL: Right of Scrotty Cave Egg Nest 1": 991,
  "TDL: Right of Scrotty Cave Egg Nest 2": 992,
  "TDL: Right of Wall with Holes Egg Nest 1": 993,
  "TDL: Right of Wall with Holes Egg Nest 2": 994,
  "TDL: River Passage Feather Nest": 995,
  "TDL: River Passage Honeycomb": 996,
  "TDL: River Passage Note 1": 997,
  "TDL: River Passage Note 2": 998,
  "TDL: River Passage Note 3": 999,
  "TDL: River Passage Note 4": 1000,
  "TDL: River Passage Signpost": 1001,
  "TDL: Roar Cage Path Note 1": 1002,
  "TDL: Roar Cage Path Note 2": 1003,
  "TDL: Roar Cage Path Note 3": 1004,
  "TDL: Roar Cage Signpost": 1005,
  "TDL: Rocknut Tribe Jiggy": 1006,
  "TDL: Scrat (Sick)": 1007,
  "TDL: Scrit (Small)": 1008,
  "TDL: Scrotty Jiggy": 1009,
  "TDL: Scrut (Lost)": 1010,
  "TDL: Springy Step Shoes Silo": 1011,
  "TDL: Stomping Plains Jiggy": 1012,
  "TDL: Stomping Plains Jinjo": 1013,
  "TDL: Stomping Plains Left Path Feather Nest 1": 1014,
  "TDL: Stomping Plains Left Path Feather Nest 2": 1015,
  "TDL: Stomping Plains Middle Path Feather Nest": 1016,
  "TDL: Stomping Plains Near Entrance Feather Nest": 1017,
  "TDL: Stomping Plains Right Path Feather Nest 1": 1018,
  "TDL: Stomping Plains Right Path Feather Nest 2": 1019,
  "TDL: Stomping Plains Second Footprint Feather Nest": 1020,
  "TDL: Stomping Plains Warp Pad Tagged": 1021,
  "TDL: Styracosaurus Cave Honeycomb": 1022,
  "TDL: Styracosaurus Family Cave Feather Nest 1": 1023,
  "TDL: Styracosaurus Family Cave Feather Nest 2": 1024,
  "TDL: Styracosaurus Family Cave Feather Nest 3": 1025,
  "TDL: Talon Torpedo Jinjo": 1026,
  "TDL: Taxi Pack Silo": 1027,
  "TDL: Terry Jiggy": 1028,
  "TDL: Terry Mumbo Token": 1029,
  "TDL: Terry's Kids Jiggy": 1030,
  "TDL: Terry's Nest Egg Nest 1": 1031,
  "TDL: Terry's Nest Egg Nest 2": 1032,
  "TDL: Top of the Mountain Egg Nest": 1033,
  "TDL: Top of the Mountain Warp Pad Tagged": 1034,
  "TDL: Train Station Egg Nest 1": 1035,
  "TDL: Train Station Egg Nest 2": 1036,
  "TDL: Train Station Feather Nest 1": 1037,
  "TDL: Train Station Feather Nest 2": 1038,
  "TDL: Train Station Left Note": 1039,
  "TDL: Train Station Middle Note": 1040,
  "TDL: Train Station Right Note": 1041,
  "TDL: Train Switch": 1042,
  "TDL: Treble Clef": 1043,
  "TDL: Under Terry's Nest Jiggy": 1044,
  "TDL: Unga Bunga Cave Entrance Glowbo": 1045,
  "TDL: Unga Bunga's Cave Egg Nest 1": 1046,
  "TDL: Unga Bunga's Cave Egg Nest 2": 1047,
  "TDL: Unga Bunga's Cave Egg Nest 3": 1048,
  "TDL: Unga Bunga's Cave Feather Nest 1": 1049,
  "TDL: Unga Bunga's Cave Feather Nest 2": 1050,
  "TDL: Unga Bunga's Cave Feather Nest 3": 1051,
  "TDL: World Entry and Exit Warp Pad Tagged": 1052,
  "TDL: Zig-Zag Path Note 1": 1053,
  "TDL: Zig-Zag Path Note 2": 1054,
  "TDL: Zig-Zag Path Note 3": 1055,
  "Train At GI": 1056,
  "WW: Airborne Egg Aiming Silo": 1057,
  "WW: Area 51 Egg Nest 1": 1058,
  "WW: Area 51 Egg Nest 2": 1059,
  "WW: Area 51 Gate Left Note": 1060,
  "WW: Area 51 Gate Right Note": 1061,
  "WW: Around the Tent Note 1": 1062,
  "WW: Around the Tent Note 2": 1063,
  "WW: Around the Tent Note 3": 1064,
  "WW: Around the Tent Note 4": 1065,
  "WW: Around the Tent Note 5": 1066,
  "WW: Around the Tent Note 6": 1067,
  "WW: Around the Tent Note 7": 1068,
  "WW: Around the Tent Note 8": 1069,
  "WW: Balloon Burst Jiggy": 1070,
  "WW: Balloon Burst Mumbo Token": 1071,
  "WW: Behind the Big Top Tent Warp Pad Tagged": 1072,
  "WW: Big Top Back Pack Egg Nest 1": 1073,
  "WW: Big Top Back Pack Egg Nest 2": 1074,
  "WW: Big Top Back Pack Feather Nest 1": 1075,
  "WW: Big Top Back Pack Feather Nest 2": 1076,
  "WW: Big Top Front Pack Egg Nest 1": 1077,
  "WW: Big Top Front Pack Egg Nest 2": 1078,
  "WW: Big Top Front Pack Feather Nest 1": 1079,
  "WW: Big Top Front Pack Feather Nest 2": 1080,
  "WW: Big Top Jinjo": 1081,
  "WW: Big Top Left Pack Egg Nest 1": 1082,
  "WW: Big Top Left Pack Egg Nest 2": 1083,
  "WW: Big Top Left Pack Feather Nest 1": 1084,
  "WW: Big Top Left Pack Feather Nest 2": 1085,
  "WW: Big Top Right Pack Egg Nest 1": 1086,
  "WW: Big Top Right Pack Egg Nest 2": 1087,
  "WW: Big Top Right Pack Feather Nest 1": 1088,
  "WW: Big Top Right Pack Feather Nest 2": 1089,
  "WW: Burger Stand Signpost": 1090,
  "WW: Cactus of Strength Jiggy": 1091,
  "WW: Cactus of Strength Jinjo": 1092,
  "WW: Cactus of Strength Signpost": 1093,
  "WW: Cave of Horrors Jinjo": 1094,
  "WW: Crazy Castle Entrance Note 1": 1095,
  "WW: Crazy Castle Entrance Note 2": 1096,
  "WW: Crazy Castle Honeycomb": 1097,
  "WW: Crazy Castle Stockade Egg Nest 1": 1098,
  "WW: Crazy Castle Stockade Egg Nest 2": 1099,
  "WW: Dive of Death Jiggy": 1100,
  "WW: Dive of Death Note 1": 1101,
  "WW: Dive of Death Note 2": 1102,
  "WW: Dodgem Dome Jiggy": 1103,
  "WW: Dodgem Dome Jinjo": 1104,
  "WW: Dodgem Dome Mumbo Token": 1105,
  "WW: Dodgem Dome Signpost": 1106,
  "WW: Entrance Ticket": 1107,
  "WW: Fries Stand Signpost": 1108,
  "WW: Gobi Cage Signpost": 1109,
  "WW: Groggy": 1110,
  "WW: Hoop Hurry Jiggy": 1111,
  "WW: Hoop Hurry Mumbo Token": 1112,
  "WW: Madame Grunty Signpost": 1113,
  "WW: Moggy": 1114,
  "WW: Mr. Patch Jiggy": 1115,
  "WW: Mr. Patch Mumbo Token": 1116,
  "WW: Mrs. Boggy Jiggy": 1117,
  "WW: Mumbo Skull Honeycomb": 1118,
  "WW: Near Mrs Boggy Egg Nest 1": 1119,
  "WW: Near Mrs Boggy Egg Nest 2": 1120,
  "WW: On Big Top Support Feather Nest 1": 1121,
  "WW: On Big Top Support Feather Nest 2": 1122,
  "WW: On Big Top Support Feather Nest 3": 1123,
  "WW: On Big Top Support Feather Nest 4": 1124,
  "WW: On Big Top Support Feather Nest 5": 1125,
  "WW: On Big Top Support Feather Nest 6": 1126,
  "WW: Outside Dodgem Dome Note 1": 1127,
  "WW: Outside Dodgem Dome Note 2": 1128,
  "WW: Outside Mumbo's Skull Warp Pad Tagged": 1129,
  "WW: Outside Star Spinner Egg Nest 1": 1130,
  "WW: Outside Star Spinner Egg Nest 2": 1131,
  "WW: Outside Wumba's Wigwam Warp Pad Tagged": 1132,
  "WW: Pack Whack Silo": 1133,
  "WW: Pump Room Feather Nest 1": 1134,
  "WW: Pump Room Feather Nest 2": 1135,
  "WW: Pump Room Signpost": 1136,
  "WW: Saucer of Peril Cheato Page": 1137,
  "WW: Saucer of Peril Jiggy": 1138,
  "WW: Saucer of Peril Mumbo Token": 1139,
  "WW: Soggy": 1140,
  "WW: Space Ticket": 1141,
  "WW: Space Zone Honeycomb": 1142,
  "WW: Space Zone Warp Pad Tagged": 1143,
  "WW: Split Up Silo": 1144,
  "WW: Spooky Ticket": 1145,
  "WW: Star Spinner Egg Nest": 1146,
  "WW: Star Spinner Feather Nest 1": 1147,
  "WW: Star Spinner Feather Nest 2": 1148,
  "WW: Star Spinner Jiggy": 1149,
  "WW: The Haunted Cavern Cheato Page": 1150,
  "WW: The Haunted Caverns Egg Nest 1": 1151,
  "WW: The Haunted Caverns Egg Nest 2": 1152,
  "WW: The Haunted Caverns Egg Nest 3": 1153,
  "WW: The Haunted Caverns Signpost": 1154,
  "WW: The Inferno Cheato Page": 1155,
  "WW: The Inferno Egg Nest 1": 1156,
  "WW: The Inferno Egg Nest 2": 1157,
  "WW: The Inferno Glowbo": 1158,
  "WW: The Inferno Jiggy": 1159,
  "WW: Train Station Egg Nest 1": 1160,
  "WW: Train Station Egg Nest 2": 1161,
  "WW: Train Switch": 1162,
  "WW: Treble Clef": 1163,
  "WW: Van Door Jinjo": 1164,
  "WW: Western Ticket": 1165,
  "WW: World Entry and Exit Warp Pad Tagged": 1166,
  "WW: Wumba's Glowbo": 1167
}

class AP_CMD:
  NONE = 0
  HANDSHAKE = 1
  PING = 2
  PONG = 3
  STATE = 4
  INFO = 5
  OPTIONS = 6
  LOCATIONS = 7
  ITEMS = 8
  MESSAGE = 9
  DEATH_LINK = 10
  TAG_LINK = 11

class AP_STATE:
  DISCONNECTED = 0
  CONNECTING = 1
  CONNECTED = 2
  PINGED = 4
