IOHJV = "Isle O Hags - Jinjo Village"
IOHJVKP  = "Isle O Hags - King Jingaling Palace"
IOHJVGJ  = "Isle O Hags - Green Jinjo House"
IOHJVBLKJ  = "Isle O Hags - Black Jinjo House"
IOHJVYJ  = "Isle O Hags - Yellow Jinjo House"
IOHJVBLUJ  = "Isle O Hags - Blue Jinjo House"
IOHJVBWNJ  = "Isle O Hags - Brown Jinjo House"
IOHJVOJ  = "Isle O Hags - Orange Jinjo House"
IOHJVPJ  = "Isle O Hags - Purple Jinjo House"
IOHJVRJ  = "Isle O Hags - Red Jinjo House"
IOHJVWJ  = "Isle O Hags - White Jinjo House"

IOHWH  = "Isle O Hags - Wooded Hollow"
IOHWL  = "Isle O Hags - Wasteland"
IOHQM  = "Isle O Hags - Quagmire"
IOHHB  = "Isle O Hags - Honey B's Hive"
IOHPL  = "Isle O Hags - Plateau"
IOHWW  = "Isle O Hags - Wumba's Wigwam"
IOHPG  = "Isle O Hags - Pine Grove"
IOHJT  = "Isle O Hags - Jiggywiggy Temple"
IOHCT  = "Isle O Hags - Clifftop"
IOHDC  = "Isle O Hags - Another Digger Tunnel"

SMBH = "Spiral Mountain - Banjo's House"
SMGL = "Spiral Mountain - Grunty's Lair"
SMBW = "Spiral Mountain - Behind Waterfall"
SM   = "Spiral Mountain" 
SMDT = "Sprial Mountain - Digger Tunnel"

MT = "Mayahem Temple"
MTCDC = "Mayahem Temple - Code Chamber"
MTCC = "Mayahem Temple - Column Chamber"
MTTT = "Mayahem Temple - Targitzan's Temple"
MTJSG = "Mayahem Temple - Jade Snake Grove"

GM = "Glitter Gultch Mine"
WW = "Witchy's World"
JR = "Jolly Roger's Lagoon"
TL = "Terrydactyland"
GI = "Grunty's Industries"
HP = "Hailfire Peaks"
CC = "Cloud Cuckooland"
CK = "Cauldrons Keep"
H1 = "HAG1"
