PAGES = "Kongkrete's Page"
HONEY = "Empty Honeycomb"
WJINJO = "white Jinjo"
OJINJO = "Orange Jinjo"
YJINJO = "Yellow Jinjo"
BRJINJO = "Brown Jinjo"
GJINJO = "Green Jinjo"
RJINJO = "Red Jinjo"
BLJINJO = "Blue Jinjo"
PJINJO = "Purple Jinjo"
BKJINJO = "Black Jinjo"
DOUBLOON = "Doubloon"
GLOWBO = "Glowbo"
JIGGY = "Jiggy"
TREBLE = "Treble Clef"

GGRAB       = "Grip Grab"
BBLASTER    = "Breegull Blaster"
EGGAIM      = "Egg Aim"
BDRILL      = "Bill Drill"
BBAYONET    = "Beak Bayonet"
AIREAIM     = "Airborne Egg Aiming" #TODO: Double Check
SPLITUP     = "Split Up" #TODO: Double Check
WWHACK      = "Wing Whack" #TODO: Double Check
TTORP       = "Talon Torpedo" #TODO: Double Check
AUQAIM      = "Sub-Aqua Egg Aiming" #TODO: Double Check
SHPACK      = "Shack Pack"
GLIDE       = "Glide"
SNPACK      = "Snooze Pack"
LSPRING     = "Leg Spring"
CLAWBTS     = "Claw Clamber Boots"
SPRINGB     = "Springy Step Shoes"
TAXPACK     = "Taxi Pack"
HATCH       = "Hatch"
PACKWH      = "Pack Whack"
SAPACK      = "Sack Pack"
FEGGS       = "Fire Eggs"
GEGGS       = "Grenade Eggs"
CEGGS       = "Clockwork Kazooie Eggs"
IEGGS       = "Ice Eggs"
FSWIM       = "Fast Swimming"

# Mumbo Magics
MUMBOMT = "Mumbo: Golden Goliath"
MUMBOGM = "Mumbo: Levitate"
MUMBOWW = "Mumbo: Power"
MUMBOJR = "Mumbo: Oxygenate"
MUMBOTD = "Mumbo: Enlarge"
MUMBOGI = "Mumbo: EMP"
MUMBOHP = "Mumbo: Life Force"
MUMBOCC = "Mumbo: Rain Dance"
MUMBOIH = "Mumbo: Heal"

HUMBAMT = "Humba: Stony"
HUMBAGM = "Humba: Detonator"
HUMBAWW = "Humba: Money Van"
HUMBAJR = "Humba: Sub"
HUMBATD = "Humba: T-Rex"
HUMBAGI = "Humba: Washing Machine"
HUMBAHP = "Humba: Snowball"
HUMBACC = "Humba: Bee"
HUMBAIH = "Humba: Dragon"

#Train Switches
TRAINSWIH  = "IoH: Train Station"
TRAINSWTD  = "TDL: Train Station"
TRAINSWGI  = "GI: Train Station"
TRAINSWHP1 = "HFP: Lava Side Train Station"
TRAINSWHP2 = "HFP: Icy Side Train Station"
TRAINSWWW  = "WW: Train Station"

CHUFFY = "Chuffy"

VICTORY = "Kick Around"